; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon May 25 2020 13:58:08 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA8MNH54L5ZZ:
	dc.w $0, DATA8MNH54L5ZZ_1-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_2-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_3-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_4-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_5-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_6-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_7-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_8-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_9-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_10-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_11-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_12-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_13-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_14-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_15-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_16-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_17-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_18-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_19-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_1A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_1B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_1C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_1D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_1E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_1F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_20-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_21-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_22-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_23-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_24-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_25-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_26-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_27-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_28-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_29-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_2A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_2B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_2C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_2D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_2E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_2F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_30-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_31-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_32-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_33-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_34-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_35-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_36-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_37-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_38-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_39-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_3A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_3B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_3C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_3D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_3E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_3F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_40-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_41-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_42-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_43-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_44-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_45-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_46-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_47-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_48-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_49-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_4A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_4B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_4C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_4D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_4E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_4F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_50-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_51-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_52-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_53-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_54-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_55-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_56-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_57-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_58-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_59-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_5A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_5B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_5C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_5D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_5E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_5F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_60-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_61-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_62-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_63-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_64-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_65-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_66-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_67-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_68-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_69-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_6A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_6B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_6C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_6D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_6E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_6F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_70-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_71-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_72-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_73-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_74-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_75-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_76-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_77-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_78-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_79-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_7A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_7B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_7C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_7D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_7E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_7F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_80-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_81-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_82-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_83-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_84-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_85-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_86-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_87-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_88-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_89-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_8A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_8B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_8C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_8D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_8E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_8F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_90-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_91-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_92-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_93-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_94-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_95-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_96-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_97-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_98-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_99-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_9A-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_9B-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_9C-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_9D-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_9E-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_9F-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_A0-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_A1-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_A2-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_A3-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_A4-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_A5-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_A6-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_A7-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_A8-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_A9-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_AA-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_AB-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_AC-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_AD-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_AE-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_AF-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_B0-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_B1-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_B2-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_B3-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_B4-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_B5-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_B6-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_B7-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_B8-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_B9-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_BA-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_BB-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_BC-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_BD-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_BE-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_BF-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_C0-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_C1-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_C2-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_C3-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_C4-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_C5-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_C6-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_C7-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_C8-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_C9-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_CA-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_CB-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_CC-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_CD-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_CE-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_CF-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_D0-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_D1-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_D2-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_D3-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_D4-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_D5-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_D6-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_D7-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_D8-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_D9-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_DA-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_DB-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_DC-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_DD-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_DE-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_DF-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_E0-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_E1-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_E2-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_E3-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_E4-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_E5-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_E6-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_E7-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_E8-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_E9-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_EA-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_EB-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_EC-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_ED-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_EE-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_EF-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_F0-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_F1-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_F2-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_F3-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_F4-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_F5-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_F6-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_F7-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_F8-DATA8MNH54L5ZZ, DATA8MNH54L5ZZ_F9-DATA8MNH54L5ZZ
	dc.w DATA8MNH54L5ZZ_FA-DATA8MNH54L5ZZ
DATA8MNH54L5ZZ_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $E, $0, $3, $F3
	dc.b $FC, $2, $0, $F, $EB
	dc.b $C, $4, $0, $12, $3
DATA8MNH54L5ZZ_2: dc.b $3
	dc.b $EC, $4, $0, $0, $F9
	dc.b $F4, $F, $0, $2, $F1
	dc.b $FC, $2, $0, $12, $E9
DATA8MNH54L5ZZ_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F4
	dc.b $FC, $D, $0, $6, $EC
	dc.b $C, $4, $0, $E, $F4
DATA8MNH54L5ZZ_4: dc.b $2
	dc.b $EC, $9, $0, $0, $F5
	dc.b $FC, $E, $0, $6, $ED
DATA8MNH54L5ZZ_5: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $E, $0, $3, $F3
	dc.b $FC, $1, $0, $F, $EB
	dc.b $C, $C, $0, $11, $EB
DATA8MNH54L5ZZ_6: dc.b $4
	dc.b $EA, $4, $0, $0, $FA
	dc.b $F2, $8, $0, $2, $F2
	dc.b $FA, $E, $0, $5, $F2
	dc.b $2, $1, $0, $11, $EA
DATA8MNH54L5ZZ_7: dc.b $3
	dc.b $EC, $4, $0, $0, $F7
	dc.b $F4, $E, $0, $2, $EF
	dc.b $C, $8, $0, $E, $EF
DATA8MNH54L5ZZ_8: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $8, $0, $3, $F3
	dc.b $FC, $E, $0, $6, $F3
	dc.b $FC, $0, $0, $12, $EB
DATA8MNH54L5ZZ_9: dc.b $3
	dc.b $ED, $E, $0, $0, $F2
	dc.b $5, $8, $0, $C, $F2
	dc.b $D, $5, $0, $F, $FA
DATA8MNH54L5ZZ_A: dc.b $3
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F7, $2, $0, $10, $10
	dc.b $F, $4, $0, $13, $F8
DATA8MNH54L5ZZ_B: dc.b $3
	dc.b $EF, $8, $0, $0, $F4
	dc.b $F7, $E, $0, $3, $F4
	dc.b $F, $0, $0, $F, $4
DATA8MNH54L5ZZ_C: dc.b $4
	dc.b $F0, $8, $0, $0, $F3
	dc.b $F8, $D, $0, $3, $F3
	dc.b $8, $8, $0, $B, $F3
	dc.b $10, $4, $0, $E, $FB
DATA8MNH54L5ZZ_D: dc.b $3
	dc.b $EB, $F, $0, $0, $F2
	dc.b $B, $4, $0, $10, $F2
	dc.b $13, $4, $0, $12, $FA
DATA8MNH54L5ZZ_E: dc.b $2
	dc.b $EF, $E, $0, $0, $F5
	dc.b $7, $5, $0, $C, $F5
DATA8MNH54L5ZZ_F: dc.b $3
	dc.b $F0, $8, $0, $0, $F5
	dc.b $F8, $E, $0, $3, $F5
	dc.b $10, $0, $0, $F, $5
DATA8MNH54L5ZZ_10: dc.b $3
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $E, $0, $3, $F3
	dc.b $C, $4, $0, $F, $FB
DATA8MNH54L5ZZ_11: dc.b $4
	dc.b $EE, $C, $0, $0, $F4
	dc.b $F6, $E, $0, $4, $EC
	dc.b $F6, $0, $0, $10, $C
	dc.b $E, $8, $0, $11, $FC
DATA8MNH54L5ZZ_12: dc.b $4
	dc.b $F0, $C, $0, $0, $F4
	dc.b $F8, $D, $0, $4, $EC
	dc.b $F8, $0, $0, $C, $C
	dc.b $8, $D, $0, $D, $F4
DATA8MNH54L5ZZ_13: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $FD, $1, $0, $C, $C
	dc.b $D, $4, $0, $E, $FC
DATA8MNH54L5ZZ_14: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATA8MNH54L5ZZ_15: dc.b $4
	dc.b $ED, $8, $0, $0, $F4
	dc.b $F5, $E, $0, $3, $EC
	dc.b $F5, $0, $0, $F, $C
	dc.b $D, $8, $0, $10, $FC
DATA8MNH54L5ZZ_16: dc.b $4
	dc.b $EF, $8, $0, $0, $FB
	dc.b $F7, $E, $0, $3, $F3
	dc.b $F7, $1, $0, $F, $EB
	dc.b $F, $4, $0, $11, $3
DATA8MNH54L5ZZ_17: dc.b $3
	dc.b $F2, $8, $0, $0, $F4
	dc.b $FA, $E, $0, $3, $F4
	dc.b $FA, $1, $0, $F, $EC
DATA8MNH54L5ZZ_18: dc.b $4
	dc.b $EE, $4, $0, $0, $FC
	dc.b $F6, $E, $0, $2, $EC
	dc.b $F6, $2, $0, $E, $C
	dc.b $E, $0, $0, $11, $FC
DATA8MNH54L5ZZ_19: dc.b $3
	dc.b $F0, $8, $0, $0, $EE
	dc.b $F8, $E, $0, $3, $EE
	dc.b $F8, $5, $0, $F, $E
DATA8MNH54L5ZZ_1A: dc.b $3
	dc.b $E9, $8, $0, $0, $F7
	dc.b $F1, $F, $0, $3, $EF
	dc.b $F9, $1, $0, $13, $F
DATA8MNH54L5ZZ_1B: dc.b $3
	dc.b $EB, $8, $0, $0, $F8
	dc.b $F3, $E, $0, $3, $F0
	dc.b $F3, $0, $0, $F, $10
DATA8MNH54L5ZZ_1C: dc.b $3
	dc.b $EC, $4, $0, $0, $FA
	dc.b $F4, $E, $0, $2, $F2
	dc.b $F4, $1, $0, $E, $12
DATA8MNH54L5ZZ_1D: dc.b $2
	dc.b $EE, $F, $0, $0, $EB
	dc.b $F6, $6, $0, $10, $B
DATA8MNH54L5ZZ_1E: dc.b $2
	dc.b $ED, $B, $0, $0, $EE
	dc.b $FD, $5, $0, $C, $6
DATA8MNH54L5ZZ_1F: dc.b $3
	dc.b $EB, $8, $0, $0, $F9
	dc.b $F3, $E, $0, $3, $F1
	dc.b $F3, $0, $0, $F, $11
DATA8MNH54L5ZZ_20: dc.b $3
	dc.b $EC, $8, $0, $0, $F6
	dc.b $F4, $E, $0, $3, $EE
	dc.b $F4, $1, $0, $F, $E
DATA8MNH54L5ZZ_21: dc.b $2
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $F, $0, $3, $EC
DATA8MNH54L5ZZ_22: dc.b $2
	dc.b $ED, $8, $0, $0, $F4
	dc.b $F5, $F, $0, $3, $EC
DATA8MNH54L5ZZ_23: dc.b $2
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $F, $0, $3, $EC
DATA8MNH54L5ZZ_24: dc.b $2
	dc.b $ED, $8, $0, $0, $F4
	dc.b $F5, $F, $0, $3, $EC
DATA8MNH54L5ZZ_25: dc.b $4
	dc.b $F0, $8, $0, $0, $EE
	dc.b $F8, $E, $0, $3, $EE
	dc.b $0, $1, $0, $F, $E
	dc.b $10, $8, $0, $11, $F6
DATA8MNH54L5ZZ_26: dc.b $4
	dc.b $F0, $8, $0, $0, $F1
	dc.b $F8, $E, $0, $3, $F1
	dc.b $F8, $1, $0, $F, $E9
	dc.b $10, $8, $0, $11, $F9
DATA8MNH54L5ZZ_27: dc.b $3
	dc.b $F1, $8, $0, $0, $EF
	dc.b $F9, $D, $0, $3, $EF
	dc.b $9, $9, $0, $B, $F7
DATA8MNH54L5ZZ_28: dc.b $3
	dc.b $F0, $8, $0, $0, $F1
	dc.b $F8, $F, $0, $3, $F1
	dc.b $F8, $1, $0, $13, $E9
DATA8MNH54L5ZZ_29: dc.b $2
	dc.b $F4, $2, $0, $0, $EA
	dc.b $F4, $F, $0, $3, $F2
DATA8MNH54L5ZZ_2A: dc.b $2
	dc.b $F4, $2, $0, $0, $EB
	dc.b $F4, $F, $0, $3, $F3
DATA8MNH54L5ZZ_2B: dc.b $2
	dc.b $F4, $2, $0, $0, $EA
	dc.b $F4, $F, $0, $3, $F2
DATA8MNH54L5ZZ_2C: dc.b $2
	dc.b $F4, $2, $0, $0, $EB
	dc.b $F4, $F, $0, $3, $F3
DATA8MNH54L5ZZ_2D: dc.b $4
	dc.b $EB, $4, $0, $0, $0
	dc.b $F3, $E, $0, $2, $F8
	dc.b $FB, $1, $0, $E, $F0
	dc.b $B, $C, $0, $10, $F0
DATA8MNH54L5ZZ_2E: dc.b $4
	dc.b $F0, $C, $0, $0, $F8
	dc.b $F8, $E, $0, $4, $F0
	dc.b $F8, $1, $0, $10, $10
	dc.b $10, $4, $0, $12, $F8
DATA8MNH54L5ZZ_2F: dc.b $3
	dc.b $F2, $E, $0, $0, $F9
	dc.b $FA, $1, $0, $C, $F1
	dc.b $A, $8, $0, $E, $F1
DATA8MNH54L5ZZ_30: dc.b $3
	dc.b $F0, $F, $0, $0, $F8
	dc.b $F8, $2, $0, $10, $F0
	dc.b $10, $4, $0, $13, $F8
DATA8MNH54L5ZZ_31: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $D, $0, $3, $F3
	dc.b $4, $8, $0, $B, $F3
	dc.b $C, $4, $0, $E, $FB
DATA8MNH54L5ZZ_32: dc.b $2
	dc.b $EA, $4, $0, $0, $FB
	dc.b $F2, $F, $0, $2, $F3
DATA8MNH54L5ZZ_33: dc.b $3
	dc.b $ED, $9, $0, $0, $F4
	dc.b $FD, $C, $0, $6, $F4
	dc.b $5, $8, $0, $A, $F4
DATA8MNH54L5ZZ_34: dc.b $3
	dc.b $EF, $8, $0, $0, $F3
	dc.b $F7, $E, $0, $3, $F3
	dc.b $F, $0, $0, $F, $3
DATA8MNH54L5ZZ_35: dc.b $3
	dc.b $F2, $8, $0, $0, $F4
	dc.b $FA, $D, $0, $3, $F4
	dc.b $A, $8, $0, $B, $F4
DATA8MNH54L5ZZ_36: dc.b $3
	dc.b $EC, $4, $0, $0, $FB
	dc.b $F4, $D, $0, $2, $F3
	dc.b $4, $9, $0, $A, $F3
DATA8MNH54L5ZZ_37: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $8, $0, $10, $F2
DATA8MNH54L5ZZ_38: dc.b $3
	dc.b $EB, $5, $0, $0, $FB
	dc.b $FB, $C, $0, $4, $F3
	dc.b $3, $9, $0, $8, $F3
DATA8MNH54L5ZZ_39: dc.b $2
	dc.b $F2, $E, $0, $0, $F3
	dc.b $A, $8, $0, $C, $F3
DATA8MNH54L5ZZ_3A: dc.b $2
	dc.b $F4, $D, $0, $0, $F3
	dc.b $4, $8, $0, $8, $F3
DATA8MNH54L5ZZ_3B: dc.b $3
	dc.b $F3, $D, $0, $0, $F2
	dc.b $3, $8, $0, $8, $F2
	dc.b $B, $C, $0, $B, $F2
DATA8MNH54L5ZZ_3C: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $D, $0, $9, $F4
DATA8MNH54L5ZZ_3D: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA8MNH54L5ZZ_3E: dc.b $3
	dc.b $F3, $8, $0, $0, $F4
	dc.b $FB, $D, $0, $3, $F4
	dc.b $B, $4, $0, $B, $F4
DATA8MNH54L5ZZ_3F: dc.b $2
	dc.b $F6, $D, $0, $0, $F4
	dc.b $6, $8, $0, $8, $F4
DATA8MNH54L5ZZ_40: dc.b $3
	dc.b $F2, $8, $0, $0, $F9
	dc.b $FA, $D, $0, $3, $F1
	dc.b $A, $4, $0, $B, $F9
DATA8MNH54L5ZZ_41: dc.b $2
	dc.b $EF, $E, $0, $0, $F3
	dc.b $7, $9, $0, $C, $F3
DATA8MNH54L5ZZ_42: dc.b $4
	dc.b $EC, $C, $0, $0, $F4
	dc.b $F4, $8, $0, $4, $F4
	dc.b $FC, $C, $0, $7, $F4
	dc.b $4, $9, $0, $B, $F4
DATA8MNH54L5ZZ_43: dc.b $2
	dc.b $ED, $B, $0, $0, $F4
	dc.b $D, $8, $0, $C, $F4
DATA8MNH54L5ZZ_44: dc.b $1
	dc.b $F0, $F, $0, $0, $F4
DATA8MNH54L5ZZ_45: dc.b $3
	dc.b $F2, $8, $0, $0, $F4
	dc.b $FA, $D, $0, $3, $F4
	dc.b $A, $0, $0, $B, $FC
DATA8MNH54L5ZZ_46: dc.b $2
	dc.b $F1, $9, $0, $0, $F3
	dc.b $1, $D, $0, $6, $F3
DATA8MNH54L5ZZ_47: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $E, $0, $6, $F3
DATA8MNH54L5ZZ_48: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATA8MNH54L5ZZ_49: dc.b $3
	dc.b $ED, $F, $0, $0, $F1
	dc.b $F5, $2, $0, $10, $E9
	dc.b $D, $4, $0, $13, $F9
DATA8MNH54L5ZZ_4A: dc.b $3
	dc.b $F0, $E, $0, $0, $EE
	dc.b $8, $8, $0, $C, $EE
	dc.b $10, $0, $0, $F, $EE
DATA8MNH54L5ZZ_4B: dc.b $2
	dc.b $F4, $A, $0, $0, $F4
	dc.b $C, $4, $0, $9, $F4
DATA8MNH54L5ZZ_4C: dc.b $2
	dc.b $F5, $E, $0, $0, $F0
	dc.b $D, $C, $0, $C, $F0
DATA8MNH54L5ZZ_4D: dc.b $1
	dc.b $F4, $E, $0, $0, $F3
DATA8MNH54L5ZZ_4E: dc.b $3
	dc.b $ED, $8, $0, $0, $F8
	dc.b $F5, $E, $0, $3, $F0
	dc.b $F5, $1, $0, $F, $10
DATA8MNH54L5ZZ_4F: dc.b $2
	dc.b $ED, $C, $0, $0, $F6
	dc.b $F5, $E, $0, $4, $EE
DATA8MNH54L5ZZ_50: dc.b $3
	dc.b $EE, $0, $0, $0, $4
	dc.b $F6, $E, $0, $1, $EC
	dc.b $F6, $1, $0, $D, $C
DATA8MNH54L5ZZ_51: dc.b $3
	dc.b $EC, $4, $0, $0, $1
	dc.b $F4, $A, $0, $2, $F1
	dc.b $F4, $5, $0, $B, $9
DATA8MNH54L5ZZ_52: dc.b $3
	dc.b $EF, $4, $0, $0, $F8
	dc.b $F7, $D, $0, $2, $F0
	dc.b $7, $4, $0, $A, $F8
DATA8MNH54L5ZZ_53: dc.b $3
	dc.b $EE, $8, $0, $0, $F0
	dc.b $F6, $D, $0, $3, $F0
	dc.b $6, $8, $0, $B, $F8
DATA8MNH54L5ZZ_54: dc.b $2
	dc.b $F0, $E, $0, $0, $F0
	dc.b $8, $8, $0, $C, $F0
DATA8MNH54L5ZZ_55: dc.b $3
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $C, $0, $3, $F4
	dc.b $FC, $A, $0, $7, $F4
DATA8MNH54L5ZZ_56: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATA8MNH54L5ZZ_57: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATA8MNH54L5ZZ_58: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F3
DATA8MNH54L5ZZ_59: dc.b $3
	dc.b $EC, $8, $0, $0, $F2
	dc.b $F4, $D, $0, $3, $F2
	dc.b $4, $9, $0, $B, $F2
DATA8MNH54L5ZZ_5A: dc.b $2
	dc.b $EC, $B, $0, $0, $F2
	dc.b $C, $8, $0, $C, $F2
DATA8MNH54L5ZZ_5B: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F3
DATA8MNH54L5ZZ_5C: dc.b $2
	dc.b $F5, $E, $0, $0, $E3
	dc.b $F5, $A, $0, $C, $3
DATA8MNH54L5ZZ_5D: dc.b $2
	dc.b $F5, $E, $0, $0, $EA
	dc.b $F5, $2, $0, $C, $A
DATA8MNH54L5ZZ_5E: dc.b $2
	dc.b $F5, $E, $0, $0, $EA
	dc.b $F5, $2, $0, $C, $A
DATA8MNH54L5ZZ_5F: dc.b $2
	dc.b $F5, $E, $0, $0, $E4
	dc.b $F5, $A, $0, $C, $4
DATA8MNH54L5ZZ_60: dc.b $1
	dc.b $F5, $E, $0, $0, $F2
DATA8MNH54L5ZZ_61: dc.b $1
	dc.b $F5, $E, $0, $0, $E8
DATA8MNH54L5ZZ_62: dc.b $3
	dc.b $F5, $C, $0, $0, $EF
	dc.b $FD, $D, $0, $4, $E7
	dc.b $FD, $5, $0, $C, $7
DATA8MNH54L5ZZ_63: dc.b $2
	dc.b $E3, $B, $0, $0, $F5
	dc.b $3, $A, $0, $C, $F5
DATA8MNH54L5ZZ_64: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATA8MNH54L5ZZ_65: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATA8MNH54L5ZZ_66: dc.b $2
	dc.b $E5, $B, $0, $0, $F5
	dc.b $5, $A, $0, $C, $F5
DATA8MNH54L5ZZ_67: dc.b $1
	dc.b $F0, $B, $0, $0, $F5
DATA8MNH54L5ZZ_68: dc.b $1
	dc.b $F5, $B, $0, $0, $F5
DATA8MNH54L5ZZ_69: dc.b $3
	dc.b $E8, $4, $0, $0, $FB
	dc.b $F0, $9, $0, $2, $F3
	dc.b $0, $D, $0, $8, $F3
DATA8MNH54L5ZZ_6A: dc.b $2
	dc.b $EF, $A, $0, $0, $F5
	dc.b $7, $4, $0, $9, $FD
DATA8MNH54L5ZZ_6B: dc.b $2
	dc.b $F5, $8, $0, $0, $F3
	dc.b $FD, $D, $0, $3, $F3
DATA8MNH54L5ZZ_6C: dc.b $3
	dc.b $EC, $4, $0, $0, $FA
	dc.b $F4, $E, $0, $2, $EA
	dc.b $F4, $1, $0, $E, $A
DATA8MNH54L5ZZ_6D: dc.b $2
	dc.b $F1, $F, $0, $0, $F2
	dc.b $F9, $2, $0, $10, $EA
DATA8MNH54L5ZZ_6E: dc.b $3
	dc.b $EE, $0, $0, $0, $FF
	dc.b $F6, $A, $0, $1, $EF
	dc.b $F6, $5, $0, $A, $7
DATA8MNH54L5ZZ_6F: dc.b $4
	dc.b $EF, $8, $0, $0, $F9
	dc.b $F7, $C, $0, $3, $F1
	dc.b $FF, $8, $0, $7, $F1
	dc.b $7, $C, $0, $A, $F1
DATA8MNH54L5ZZ_70: dc.b $2
	dc.b $ED, $4, $0, $0, $FE
	dc.b $F5, $A, $0, $2, $F6
DATA8MNH54L5ZZ_71: dc.b $1
	dc.b $ED, $F, $0, $0, $EF
DATA8MNH54L5ZZ_72: dc.b $2
	dc.b $EC, $7, $0, $0, $F0
	dc.b $F4, $A, $0, $8, $0
DATA8MNH54L5ZZ_73: dc.b $3
	dc.b $EF, $4, $0, $0, $FE
	dc.b $F7, $1, $0, $2, $EE
	dc.b $F7, $E, $0, $4, $F6
DATA8MNH54L5ZZ_74: dc.b $2
	dc.b $F0, $F, $0, $0, $EE
	dc.b $F8, $1, $0, $10, $E
DATA8MNH54L5ZZ_75: dc.b $2
	dc.b $ED, $0, $0, $0, $FB
	dc.b $F5, $E, $0, $1, $F3
DATA8MNH54L5ZZ_76: dc.b $3
	dc.b $F0, $8, $0, $0, $F1
	dc.b $F8, $E, $0, $3, $F1
	dc.b $F8, $0, $0, $F, $E9
DATA8MNH54L5ZZ_77: dc.b $2
	dc.b $ED, $4, $0, $0, $F7
	dc.b $F5, $E, $0, $2, $EF
DATA8MNH54L5ZZ_78: dc.b $3
	dc.b $E6, $C, $0, $0, $F1
	dc.b $EE, $A, $0, $4, $F1
	dc.b $6, $D, $0, $D, $F9
DATA8MNH54L5ZZ_79: dc.b $4
	dc.b $EC, $8, $0, $0, $E5
	dc.b $F4, $D, $0, $3, $E5
	dc.b $F4, $6, $0, $B, $5
	dc.b $4, $8, $0, $11, $ED
DATA8MNH54L5ZZ_7A: dc.b $3
	dc.b $F0, $0, $0, $0, $E6
	dc.b $F8, $E, $0, $1, $E6
	dc.b $E8, $7, $0, $D, $6
DATA8MNH54L5ZZ_7B: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $4, $0, $3, $FC
	dc.b $FC, $8, $0, $5, $F4
	dc.b $4, $E, $0, $8, $EC
DATA8MNH54L5ZZ_7C: dc.b $3
	dc.b $13, $C, $18, $0, $F0
	dc.b $FB, $A, $18, $4, $F8
	dc.b $EB, $D, $18, $D, $E8
DATA8MNH54L5ZZ_7D: dc.b $4
	dc.b $E, $8, $18, $0, $3
	dc.b $FE, $D, $18, $3, $FB
	dc.b $F6, $6, $18, $B, $EB
	dc.b $F6, $8, $18, $11, $FB
DATA8MNH54L5ZZ_7E: dc.b $3
	dc.b $8, $0, $18, $0, $13
	dc.b $F0, $E, $18, $1, $FB
	dc.b $F8, $7, $18, $D, $EB
DATA8MNH54L5ZZ_7F: dc.b $4
	dc.b $E, $8, $18, $0, $F5
	dc.b $6, $4, $18, $3, $F5
	dc.b $FE, $8, $18, $5, $F5
	dc.b $E6, $E, $18, $8, $F5
DATA8MNH54L5ZZ_80: dc.b $3
	dc.b $E8, $F, $0, $0, $EE
	dc.b $E8, $0, $0, $10, $E
	dc.b $8, $9, $0, $11, $EE
DATA8MNH54L5ZZ_81: dc.b $4
	dc.b $E1, $0, $0, $0, $FF
	dc.b $E9, $C, $0, $1, $EF
	dc.b $F1, $B, $0, $5, $EF
	dc.b $11, $8, $0, $11, $EF
DATA8MNH54L5ZZ_82: dc.b $3
	dc.b $E1, $4, $0, $0, $F4
	dc.b $E9, $E, $0, $2, $F4
	dc.b $1, $A, $0, $E, $F4
DATA8MNH54L5ZZ_83: dc.b $2
	dc.b $E7, $F, $0, $0, $EE
	dc.b $7, $9, $0, $10, $F6
DATA8MNH54L5ZZ_84: dc.b $4
	dc.b $E2, $4, $0, $0, $FC
	dc.b $EA, $9, $0, $2, $F4
	dc.b $FA, $C, $0, $8, $F4
	dc.b $2, $A, $0, $C, $F4
DATA8MNH54L5ZZ_85: dc.b $4
	dc.b $E2, $4, $0, $0, $F4
	dc.b $EA, $C, $0, $2, $F4
	dc.b $F2, $A, $0, $6, $F4
	dc.b $A, $5, $0, $F, $FC
DATA8MNH54L5ZZ_86: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATA8MNH54L5ZZ_87: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATA8MNH54L5ZZ_88: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATA8MNH54L5ZZ_89: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATA8MNH54L5ZZ_8A: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATA8MNH54L5ZZ_8B: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATA8MNH54L5ZZ_8C: dc.b $3
	dc.b $EF, $B, $0, $0, $F0
	dc.b $EF, $6, $0, $C, $8
	dc.b $F, $4, $0, $12, $F8
DATA8MNH54L5ZZ_8D: dc.b $4
	dc.b $EB, $A, $0, $0, $F2
	dc.b $EB, $5, $0, $9, $A
	dc.b $3, $D, $0, $D, $F2
	dc.b $3, $0, $0, $15, $12
DATA8MNH54L5ZZ_8E: dc.b $3
	dc.b $E8, $4, $0, $0, $F6
	dc.b $F0, $A, $0, $2, $F6
	dc.b $8, $5, $0, $B, $F6
DATA8MNH54L5ZZ_8F: dc.b $3
	dc.b $F3, $1, $0, $0, $E7
	dc.b $F3, $E, $0, $2, $EF
	dc.b $B, $4, $0, $E, $FF
DATA8MNH54L5ZZ_90: dc.b $4
	dc.b $E6, $4, $0, $0, $F9
	dc.b $EE, $A, $0, $2, $F1
	dc.b $6, $9, $0, $B, $F9
	dc.b $16, $4, $0, $11, $F9
DATA8MNH54L5ZZ_91: dc.b $2
	dc.b $E6, $B, $0, $0, $F2
	dc.b $6, $9, $0, $C, $FA
DATA8MNH54L5ZZ_92: dc.b $3
	dc.b $E6, $A, $0, $0, $F2
	dc.b $FE, $C, $0, $9, $F2
	dc.b $6, $5, $0, $D, $2
DATA8MNH54L5ZZ_93: dc.b $3
	dc.b $E6, $A, $0, $0, $F2
	dc.b $FE, $C, $0, $9, $F2
	dc.b $6, $4, $0, $D, $2
DATA8MNH54L5ZZ_94: dc.b $4
	dc.b $E9, $D, $0, $0, $F1
	dc.b $EB, $4, $0, $8, $F4
	dc.b $F3, $B, $0, $A, $F4
	dc.b $13, $8, $0, $16, $F4
DATA8MNH54L5ZZ_95: dc.b $4
	dc.b $E9, $9, $0, $0, $F4
	dc.b $EB, $4, $0, $6, $F4
	dc.b $F3, $B, $0, $8, $F4
	dc.b $13, $8, $0, $14, $F4
DATA8MNH54L5ZZ_96: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATA8MNH54L5ZZ_97: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATA8MNH54L5ZZ_98: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATA8MNH54L5ZZ_99: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATA8MNH54L5ZZ_9A: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATA8MNH54L5ZZ_9B: dc.b $2
	dc.b $F4, $8, $0, $0, $F3
	dc.b $FC, $E, $0, $3, $F3
DATA8MNH54L5ZZ_9C: dc.b $2
	dc.b $FC, $8, $0, $0, $F5
	dc.b $4, $D, $0, $3, $F5
DATA8MNH54L5ZZ_9D: dc.b $2
	dc.b $EC, $4, $0, $0, $F8
	dc.b $F4, $F, $0, $2, $F0
DATA8MNH54L5ZZ_9E: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $F, $0, $3, $F6
	dc.b $F4, $0, $0, $13, $EE
	dc.b $FC, $5, $0, $14, $E6
DATA8MNH54L5ZZ_9F: dc.b $4
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $E, $0, $3, $F0
	dc.b $FC, $1, $0, $F, $10
	dc.b $C, $8, $0, $11, $F0
DATA8MNH54L5ZZ_A0: dc.b $4
	dc.b $EC, $8, $0, $0, $F7
	dc.b $F4, $E, $0, $3, $EF
	dc.b $F4, $6, $0, $F, $F
	dc.b $C, $8, $0, $15, $EF
DATA8MNH54L5ZZ_A1: dc.b $4
	dc.b $E4, $0, $0, $0, $F6
	dc.b $EC, $E, $0, $1, $EE
	dc.b $EC, $7, $0, $D, $E
	dc.b $4, $9, $0, $15, $EE
DATA8MNH54L5ZZ_A2: dc.b $4
	dc.b $E8, $E, $0, $0, $F9
	dc.b $F0, $1, $0, $C, $19
	dc.b $0, $4, $0, $E, $F9
	dc.b $8, $9, $0, $10, $F1
DATA8MNH54L5ZZ_A3: dc.b $4
	dc.b $E6, $0, $0, $0, $FE
	dc.b $EE, $E, $0, $1, $EE
	dc.b $F6, $5, $0, $D, $E
	dc.b $6, $9, $0, $11, $EE
DATA8MNH54L5ZZ_A4: dc.b $4
	dc.b $F1, $E, $0, $0, $F1
	dc.b $F1, $1, $0, $C, $11
	dc.b $9, $8, $0, $E, $F1
	dc.b $11, $4, $0, $11, $F9
DATA8MNH54L5ZZ_A5: dc.b $4
	dc.b $E4, $4, $0, $0, $F1
	dc.b $EC, $1, $0, $2, $11
	dc.b $EC, $E, $0, $4, $F1
	dc.b $4, $9, $0, $10, $F1
DATA8MNH54L5ZZ_A6: dc.b $4
	dc.b $EC, $6, $0, $0, $11
	dc.b $EC, $E, $0, $6, $F1
	dc.b $4, $8, $0, $12, $F9
	dc.b $C, $8, $0, $15, $F1
DATA8MNH54L5ZZ_A7: dc.b $4
	dc.b $EC, $E, $0, $0, $F6
	dc.b $F4, $1, $0, $C, $16
	dc.b $4, $9, $0, $E, $EE
	dc.b $4, $4, $0, $14, $6
DATA8MNH54L5ZZ_A8: dc.b $4
	dc.b $EC, $1, $0, $0, $16
	dc.b $EC, $D, $0, $2, $F6
	dc.b $FC, $A, $0, $A, $EE
	dc.b $FC, $5, $0, $13, $6
DATA8MNH54L5ZZ_A9: dc.b $4
	dc.b $E4, $9, $0, $0, $F9
	dc.b $C, $4, $0, $6, $F9
	dc.b $F4, $E, $0, $8, $E9
	dc.b $F4, $A, $0, $14, $9
DATA8MNH54L5ZZ_AA: dc.b $4
	dc.b $E4, $4, $0, $0, $3
	dc.b $C, $4, $0, $2, $FB
	dc.b $EC, $F, $0, $4, $FB
	dc.b $F4, $6, $0, $14, $EB
DATA8MNH54L5ZZ_AB: dc.b $4
	dc.b $EE, $D, $0, $0, $F3
	dc.b $EE, $1, $0, $8, $EB
	dc.b $FE, $9, $0, $A, $F3
	dc.b $E, $C, $0, $10, $F3
DATA8MNH54L5ZZ_AC: dc.b $4
	dc.b $EE, $D, $0, $0, $EB
	dc.b $EE, $1, $0, $8, $B
	dc.b $FE, $9, $0, $A, $F3
	dc.b $E, $C, $0, $10, $F3
DATA8MNH54L5ZZ_AD: dc.b $4
	dc.b $EE, $D, $0, $0, $EB
	dc.b $EE, $1, $0, $8, $B
	dc.b $FE, $9, $0, $A, $F3
	dc.b $E, $C, $0, $10, $F3
DATA8MNH54L5ZZ_AE: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $0, $0, $C, $6
	dc.b $FC, $9, $0, $D, $6
DATA8MNH54L5ZZ_AF: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $0, $0, $C, $6
	dc.b $FC, $9, $0, $D, $6
DATA8MNH54L5ZZ_B0: dc.b $3
	dc.b $EA, $C, $0, $0, $F4
	dc.b $F2, $F, $0, $4, $EC
	dc.b $F2, $0, $0, $14, $C
DATA8MNH54L5ZZ_B1: dc.b $2
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $F, $0, $3, $F3
DATA8MNH54L5ZZ_B2: dc.b $3
	dc.b $EC, $8, $0, $0, $FB
	dc.b $F4, $F, $0, $3, $F3
	dc.b $FC, $2, $0, $13, $13
DATA8MNH54L5ZZ_B3: dc.b $2
	dc.b $EC, $4, $0, $0, $FC
	dc.b $F4, $F, $0, $2, $F4
DATA8MNH54L5ZZ_B4: dc.b $3
	dc.b $EC, $8, $0, $0, $FC
	dc.b $F4, $F, $0, $3, $F4
	dc.b $FC, $1, $0, $13, $14
DATA8MNH54L5ZZ_B5: dc.b $3
	dc.b $E6, $B, $0, $0, $F4
	dc.b $6, $8, $0, $C, $F4
	dc.b $E, $5, $0, $F, $F4
DATA8MNH54L5ZZ_B6: dc.b $3
	dc.b $E6, $B, $0, $0, $F4
	dc.b $6, $8, $0, $C, $F4
	dc.b $E, $5, $0, $F, $F4
DATA8MNH54L5ZZ_B7: dc.b $2
	dc.b $EE, $F, $0, $0, $EB
	dc.b $E, $0, $0, $10, $3
DATA8MNH54L5ZZ_B8: dc.b $1
	dc.b $F0, $F, $0, $0, $EB
DATA8MNH54L5ZZ_B9: dc.b $2
	dc.b $EC, $F, $0, $0, $EB
	dc.b $C, $4, $0, $10, $FB
DATA8MNH54L5ZZ_BA: dc.b $3
	dc.b $EC, $8, $0, $0, $EB
	dc.b $F4, $E, $0, $3, $EB
	dc.b $C, $4, $0, $F, $FB
DATA8MNH54L5ZZ_BB: dc.b $1
	dc.b $EE, $F, $0, $0, $EB
DATA8MNH54L5ZZ_BC: dc.b $1
	dc.b $EF, $F, $0, $0, $EB
DATA8MNH54L5ZZ_BD: dc.b $4
	dc.b $EC, $D, $0, $0, $F0
	dc.b $FC, $8, $0, $8, $F0
	dc.b $4, $4, $0, $B, $F8
	dc.b $C, $0, $0, $D, $0
DATA8MNH54L5ZZ_BE: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F0
DATA8MNH54L5ZZ_BF: dc.b $3
	dc.b $EC, $4, $0, $0, $FC
	dc.b $F4, $F, $0, $2, $F4
	dc.b $C, $0, $0, $12, $EC
DATA8MNH54L5ZZ_C0: dc.b $3
	dc.b $F4, $C, $0, $0, $F0
	dc.b $FC, $D, $0, $4, $E8
	dc.b $FC, $5, $0, $C, $8
DATA8MNH54L5ZZ_C1: dc.b $2
	dc.b $F4, $E, $0, $0, $F4
	dc.b $FC, $1, $0, $C, $EC
DATA8MNH54L5ZZ_C2: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATA8MNH54L5ZZ_C3: dc.b $2
	dc.b $F4, $E, $8, $0, $EC
	dc.b $FC, $1, $8, $C, $C
DATA8MNH54L5ZZ_C4: dc.b $3
	dc.b $F4, $C, $8, $0, $F0
	dc.b $FC, $D, $8, $4, $F8
	dc.b $FC, $5, $8, $C, $E8
DATA8MNH54L5ZZ_C5: dc.b $2
	dc.b $F4, $E, $0, $0, $EB
	dc.b $F4, $6, $0, $C, $B
DATA8MNH54L5ZZ_C6: dc.b $3
	dc.b $F4, $C, $0, $0, $F6
	dc.b $FC, $D, $0, $4, $EE
	dc.b $FC, $5, $0, $C, $E
DATA8MNH54L5ZZ_C7: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATA8MNH54L5ZZ_C8: dc.b $3
	dc.b $F4, $C, $8, $0, $EB
	dc.b $FC, $D, $8, $4, $F3
	dc.b $FC, $5, $8, $C, $E3
DATA8MNH54L5ZZ_C9: dc.b $2
	dc.b $F4, $E, $8, $0, $F6
	dc.b $F4, $6, $8, $C, $E6
DATA8MNH54L5ZZ_CA: dc.b $4
	dc.b $EF, $D, $0, $0, $F0
	dc.b $FF, $D, $0, $8, $E8
	dc.b $FF, $5, $0, $10, $8
	dc.b $F, $8, $0, $14, $E8
DATA8MNH54L5ZZ_CB: dc.b $4
	dc.b $E8, $E, $0, $0, $F0
	dc.b $F8, $0, $0, $C, $E8
	dc.b $0, $C, $0, $D, $E8
	dc.b $8, $5, $0, $11, $F8
DATA8MNH54L5ZZ_CC: dc.b $4
	dc.b $F3, $4, $0, $0, $FC
	dc.b $FB, $C, $0, $2, $F4
	dc.b $3, $C, $0, $6, $E4
	dc.b $3, $8, $0, $A, $4
DATA8MNH54L5ZZ_CD: dc.b $3
	dc.b $F4, $8, $0, $0, $F8
	dc.b $FC, $E, $0, $3, $F0
	dc.b $4, $1, $0, $F, $E8
DATA8MNH54L5ZZ_CE: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $C, $0, $3, $F4
	dc.b $FC, $E, $0, $7, $EC
	dc.b $FC, $0, $0, $13, $C
DATA8MNH54L5ZZ_CF: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $E, $0, $3, $F4
	dc.b $FC, $1, $0, $F, $EC
	dc.b $C, $8, $0, $11, $EC
DATA8MNH54L5ZZ_D0: dc.b $5
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $C, $0, $3, $F4
	dc.b $FC, $0, $0, $7, $EC
	dc.b $FC, $C, $0, $8, $F4
	dc.b $4, $D, $0, $C, $EC
DATA8MNH54L5ZZ_D1: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $E, $0, $3, $F4
	dc.b $FC, $0, $0, $F, $EC
	dc.b $C, $8, $0, $10, $EC
DATA8MNH54L5ZZ_D2: dc.b $2
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
DATA8MNH54L5ZZ_D3: dc.b $2
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
DATA8MNH54L5ZZ_D4: dc.b $2
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $C, $0, $C, $F1
DATA8MNH54L5ZZ_D5: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATA8MNH54L5ZZ_D6: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATA8MNH54L5ZZ_D7: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATA8MNH54L5ZZ_D8: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $D, $0, $3, $F3
	dc.b $4, $8, $0, $B, $F3
	dc.b $C, $C, $0, $E, $F3
DATA8MNH54L5ZZ_D9: dc.b $5
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $4, $8, $0, $B, $F3
	dc.b $C, $C, $0, $E, $F3
DATA8MNH54L5ZZ_DA: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $D, $0, $3, $F3
	dc.b $4, $8, $0, $B, $F3
	dc.b $C, $C, $0, $E, $F3
DATA8MNH54L5ZZ_DB: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $D, $0, $3, $F3
	dc.b $4, $8, $0, $B, $F3
	dc.b $C, $C, $0, $E, $F3
DATA8MNH54L5ZZ_DC: dc.b $3
	dc.b $EC, $8, $0, $0, $F5
	dc.b $F4, $D, $0, $3, $F5
	dc.b $4, $9, $0, $B, $F5
DATA8MNH54L5ZZ_DD: dc.b $3
	dc.b $EC, $A, $0, $0, $F6
	dc.b $F4, $5, $0, $9, $E
	dc.b $4, $9, $0, $D, $F6
DATA8MNH54L5ZZ_DE: dc.b $4
	dc.b $EC, $E, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $14
	dc.b $4, $8, $0, $E, $F4
	dc.b $C, $C, $0, $11, $F4
DATA8MNH54L5ZZ_DF: dc.b $3
	dc.b $ED, $9, $0, $0, $F1
	dc.b $FD, $D, $0, $6, $F1
	dc.b $D, $4, $0, $E, $F9
DATA8MNH54L5ZZ_E0: dc.b $3
	dc.b $F0, $8, $0, $0, $F1
	dc.b $F8, $D, $0, $3, $F1
	dc.b $8, $4, $0, $B, $F9
DATA8MNH54L5ZZ_E1: dc.b $1
	dc.b $F4, $F, $0, $0, $F0
DATA8MNH54L5ZZ_E2: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $4, $0, $C, $F3
DATA8MNH54L5ZZ_E3: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $D, $0, $9, $F4
DATA8MNH54L5ZZ_E4: dc.b $4
	dc.b $E8, $4, $0, $0, $F8
	dc.b $F0, $8, $0, $2, $F0
	dc.b $F8, $D, $0, $5, $F0
	dc.b $8, $9, $0, $D, $F8
DATA8MNH54L5ZZ_E5: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $9, $0, $C, $FC
DATA8MNH54L5ZZ_E6: dc.b $3
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $8, $0, $10, $F8
	dc.b $10, $4, $0, $13, $0
DATA8MNH54L5ZZ_E7: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $4, $0, $C, $FC
	dc.b $10, $8, $0, $E, $F4
DATA8MNH54L5ZZ_E8: dc.b $4
	dc.b $E8, $9, $0, $0, $F6
	dc.b $F8, $C, $0, $6, $EE
	dc.b $0, $8, $0, $A, $F6
	dc.b $8, $9, $0, $D, $EE
DATA8MNH54L5ZZ_E9: dc.b $3
	dc.b $E8, $9, $0, $0, $F3
	dc.b $F8, $D, $0, $6, $F3
	dc.b $8, $9, $0, $E, $F3
DATA8MNH54L5ZZ_EA: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $9, $0, $C, $F4
DATA8MNH54L5ZZ_EB: dc.b $3
	dc.b $EC, $9, $0, $0, $F4
	dc.b $FC, $C, $0, $6, $F4
	dc.b $4, $9, $0, $A, $F4
DATA8MNH54L5ZZ_EC: dc.b $3
	dc.b $EC, $C, $0, $0, $E9
	dc.b $F4, $2, $0, $4, $E9
	dc.b $F4, $F, $0, $7, $F1
DATA8MNH54L5ZZ_ED: dc.b $3
	dc.b $EC, $C, $0, $0, $EA
	dc.b $F4, $F, $0, $4, $EA
	dc.b $F4, $3, $0, $14, $A
DATA8MNH54L5ZZ_EE: dc.b $3
	dc.b $EC, $C, $0, $0, $EA
	dc.b $F4, $F, $0, $4, $EA
	dc.b $F4, $3, $0, $14, $A
DATA8MNH54L5ZZ_EF: dc.b $3
	dc.b $E8, $4, $0, $0, $F8
	dc.b $F0, $E, $0, $2, $F0
	dc.b $8, $8, $0, $E, $F0
DATA8MNH54L5ZZ_F0: dc.b $3
	dc.b $E8, $4, $0, $0, $F8
	dc.b $F0, $E, $0, $2, $F0
	dc.b $8, $4, $0, $E, $F8
DATA8MNH54L5ZZ_F1: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
DATA8MNH54L5ZZ_F2: dc.b $2
	dc.b $EB, $B, $0, $0, $F4
	dc.b $B, $0, $0, $C, $FC
DATA8MNH54L5ZZ_F3: dc.b $2
	dc.b $E8, $B, $8, $0, $F4
	dc.b $8, $8, $8, $C, $F4
DATA8MNH54L5ZZ_F4: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $4, $0, $F, $F8
DATA8MNH54L5ZZ_F5: dc.b $3
	dc.b $EB, $8, $0, $0, $F0
	dc.b $F3, $E, $0, $3, $F0
	dc.b $B, $8, $0, $F, $F0
DATA8MNH54L5ZZ_F6: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $4, $0, $10, $F8
DATA8MNH54L5ZZ_F7: dc.b $4
	dc.b $EB, $8, $0, $0, $F8
	dc.b $F3, $D, $0, $3, $F0
	dc.b $3, $8, $0, $B, $F8
	dc.b $B, $4, $0, $E, $F8
DATA8MNH54L5ZZ_F8: dc.b $3
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $4, $0, $9, $FC
	dc.b $C, $4, $0, $B, $F4
DATA8MNH54L5ZZ_F9: dc.b $4
	dc.b $EB, $8, $8, $0, $F0
	dc.b $F3, $D, $8, $3, $F0
	dc.b $3, $8, $8, $B, $F0
	dc.b $B, $4, $8, $E, $F8
DATA8MNH54L5ZZ_FA: dc.b $2
	dc.b $EB, $E, $0, $0, $F0
	dc.b $3, $9, $0, $C, $F0
	even