; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jun 22 2020 20:05:14 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAVWA45FCKH1C:
	dc.w DATAVWA45FCKH1C_0-DATAVWA45FCKH1C, DATAVWA45FCKH1C_1-DATAVWA45FCKH1C
DATAVWA45FCKH1C_0: dc.b $1
	dc.b $FC, $0, $0, $0, $FC
DATAVWA45FCKH1C_1: dc.b $1
	dc.b $FC, $0, $0, $1, $FC
	even