; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Feb 23 2019 23:15:33 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAOTBLJWPSCVB:
	dc.w DATAOTBLJWPSCVB_0-DATAOTBLJWPSCVB
DATAOTBLJWPSCVB_0: dc.b $1
	dc.b $F5, $A, $0, $4, $F5
	even