; Sprite mappings - generated by Flex - Sonic 1 format

SME_DESCx:
	dc.w CYX_Frame0-SME_DESCx, VKK_Frame1-SME_DESCx
	dc.w YGU_Frame2-SME_DESCx, IYM_Frame3-SME_DESCx


CYX_Frame0: dc.b  $A
	dc.b  $E0, $F, $0, $0, $B0
	dc.b  $0, $F, $0, $10, $B0
	dc.b  $E0, $F, $0, $20, $D0
	dc.b  $0, $F, $0, $30, $D0
	dc.b  $E0, $F, $0, $40, $F0
	dc.b  $0, $F, $0, $50, $F0
	dc.b  $E0, $F, $0, $60, $10
	dc.b  $0, $F, $0, $70, $10
	dc.b  $E0, $F, $0, $80, $30
	dc.b  $0, $F, $0, $90, $30
VKK_Frame1: dc.b  $8
	dc.b  $E0, $F, $0, $A0, $C0
	dc.b  $0, $F, $0, $B0, $C0
	dc.b  $E0, $F, $0, $C0, $E0
	dc.b  $0, $F, $0, $D0, $E0
	dc.b  $E0, $F, $0, $E0, $0
	dc.b  $0, $F, $0, $F0, $0
	dc.b  $E0, $7, $1, $0, $20
	dc.b  $0, $7, $1, $8, $20
YGU_Frame2: dc.b  $4
	dc.b  $F4, $E, $1, $10, $C8
	dc.b  $F4, $E, $1, $1C, $E8
	dc.b  $F4, $E, $1, $28, $8
	dc.b  $F4, $6, $1, $34, $28
IYM_Frame3: dc.b  $5
	dc.b  $F4, $E, $1, $3A, $B0
	dc.b  $F4, $E, $1, $46, $D0
	dc.b  $F4, $E, $1, $52, $F0
	dc.b  $F4, $E, $1, $5E, $10
	dc.b  $F4, $E, $1, $6A, $30
