; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Feb 23 2019 21:03:25 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAFGAX88CNW4Q:
	dc.w DATAFGAX88CNW4Q_0-DATAFGAX88CNW4Q, DATAFGAX88CNW4Q_1-DATAFGAX88CNW4Q
DATAFGAX88CNW4Q_0: dc.b $1
	dc.b $FC, $0, $0, $0, $FC
DATAFGAX88CNW4Q_1: dc.b $1
	dc.b $FC, $0, $0, $1, $FC
	even