; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Feb 22 2019 11:59:19 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA7Y7CT88O0C3:
	dc.w DATA7Y7CT88O0C3_0-DATA7Y7CT88O0C3, DATA7Y7CT88O0C3_1-DATA7Y7CT88O0C3
	dc.w DATA7Y7CT88O0C3_2-DATA7Y7CT88O0C3, DATA7Y7CT88O0C3_3-DATA7Y7CT88O0C3
DATA7Y7CT88O0C3_0: dc.b $3
	dc.b $FC, $C, $0, $0, $D8
	dc.b $FC, $C, $0, $4, $F8
	dc.b $FC, $4, $0, $8, $18
DATA7Y7CT88O0C3_1: dc.b $2
	dc.b $FC, $C, $0, $A, $E4
	dc.b $FC, $8, $0, $E, $4
DATA7Y7CT88O0C3_2: dc.b $3
	dc.b $FC, $C, $0, $11, $D0
	dc.b $FC, $C, $0, $15, $F0
	dc.b $FC, $C, $0, $19, $10
DATA7Y7CT88O0C3_3: dc.b $0
	even