; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Apr 01 2020 18:20:03 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATANH6OIXUYJOG:
	dc.w DATANH6OIXUYJOG_0-DATANH6OIXUYJOG, DATANH6OIXUYJOG_1-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_2-DATANH6OIXUYJOG, DATANH6OIXUYJOG_3-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_4-DATANH6OIXUYJOG, DATANH6OIXUYJOG_5-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_6-DATANH6OIXUYJOG, DATANH6OIXUYJOG_7-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_8-DATANH6OIXUYJOG, DATANH6OIXUYJOG_9-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_A-DATANH6OIXUYJOG, DATANH6OIXUYJOG_B-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_C-DATANH6OIXUYJOG, DATANH6OIXUYJOG_D-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_E-DATANH6OIXUYJOG, DATANH6OIXUYJOG_F-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_10-DATANH6OIXUYJOG, DATANH6OIXUYJOG_11-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_12-DATANH6OIXUYJOG, DATANH6OIXUYJOG_13-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_14-DATANH6OIXUYJOG, DATANH6OIXUYJOG_15-DATANH6OIXUYJOG
	dc.w DATANH6OIXUYJOG_16-DATANH6OIXUYJOG
DATANH6OIXUYJOG_0: dc.b $3
	dc.b $FC, $C, $0, $0, $D8
	dc.b $FC, $0, $0, $1, $F8
	dc.b $FC, $C, $0, $4, $8
DATANH6OIXUYJOG_1: dc.b $2
	dc.b $FC, $C, $0, $8, $E4
	dc.b $FC, $8, $0, $C, $4
DATANH6OIXUYJOG_2: dc.b $3
	dc.b $FC, $C, $0, $F, $D0
	dc.b $FC, $C, $0, $13, $F0
	dc.b $FC, $C, $0, $17, $10
DATANH6OIXUYJOG_3: dc.b $0
DATANH6OIXUYJOG_4: dc.b $3
	dc.b $FC, $C, $0, $1B, $A4
	dc.b $FC, $C, $0, $1F, $C4
	dc.b $FC, $0, $0, $3, $E4
DATANH6OIXUYJOG_5: dc.b $2
	dc.b $FC, $C, $0, $2B, $34
	dc.b $FC, $0, $0, $19, $54
DATANH6OIXUYJOG_6: dc.b $2
	dc.b $FC, $C, $0, $24, $A4
	dc.b $FC, $8, $0, $28, $C4
DATANH6OIXUYJOG_7: dc.b $1
	dc.b $FC, $C, $0, $69, $3C
DATANH6OIXUYJOG_8: dc.b $2
	dc.b $FC, $C, $0, $45, $A4
	dc.b $FC, $4, $0, $C, $C4
DATANH6OIXUYJOG_9: dc.b $3
	dc.b $FC, $0, $0, $49, $34
	dc.b $FC, $0, $60, $4A, $44
	dc.b $FC, $0, $60, $4B, $54
DATANH6OIXUYJOG_A: dc.b $3
	dc.b $FC, $8, $0, $4C, $A4
	dc.b $FC, $C, $0, $4F, $C4
	dc.b $FC, $4, $0, $1E, $E4
DATANH6OIXUYJOG_B: dc.b $3
	dc.b $FC, $8, $0, $53, $4
	dc.b $FC, $8, $60, $56, $24
	dc.b $FC, $8, $60, $59, $44
DATANH6OIXUYJOG_C: dc.b $3
	dc.b $FC, $C, $0, $5C, $A4
	dc.b $FC, $C, $0, $60, $CC
	dc.b $FC, $0, $0, $58, $EC
DATANH6OIXUYJOG_D: dc.b $2
	dc.b $FC, $4, $0, $64, $2C
	dc.b $FC, $8, $60, $66, $44
DATANH6OIXUYJOG_E: dc.b $2
	dc.b $FC, $C, $0, $2F, $34
	dc.b $FC, $0, $0, $0, $54
DATANH6OIXUYJOG_F: dc.b $2
	dc.b $FC, $C, $0, $33, $1C
	dc.b $FC, $C, $0, $37, $3C
DATANH6OIXUYJOG_10: dc.b $2
	dc.b $FC, $C, $0, $3B, $2C
	dc.b $FC, $4, $0, $3F, $4C
DATANH6OIXUYJOG_11: dc.b $2
	dc.b $FC, $C, $0, $41, $2C
	dc.b $FC, $4, $0, $22, $4C
DATANH6OIXUYJOG_12: dc.b $3
	dc.b $FC, $0, $60, $49, $34
	dc.b $FC, $0, $0, $4A, $44
	dc.b $FC, $0, $60, $4B, $54
DATANH6OIXUYJOG_13: dc.b $3
	dc.b $FC, $0, $60, $49, $34
	dc.b $FC, $0, $60, $4A, $44
	dc.b $FC, $0, $0, $4B, $54
DATANH6OIXUYJOG_14: dc.b $3
	dc.b $FC, $8, $60, $53, $4
	dc.b $FC, $8, $0, $56, $24
	dc.b $FC, $8, $60, $59, $44
DATANH6OIXUYJOG_15: dc.b $3
	dc.b $FC, $8, $60, $53, $4
	dc.b $FC, $8, $60, $56, $24
	dc.b $FC, $8, $0, $59, $44
DATANH6OIXUYJOG_16: dc.b $2
	dc.b $FC, $4, $60, $64, $2C
	dc.b $FC, $8, $0, $66, $44
	even