; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Mar 06 2020 20:54:42 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA21RS2ZI26L9:
	dc.w DATA21RS2ZI26L9_0-DATA21RS2ZI26L9
DATA21RS2ZI26L9_0: dc.b $1
	dc.b $F4, $A, $18, $4, $F4
	even