; Sprite mappings - generated by Flex - Sonic 1 format

_Mapping:
	dc.w TUH_Frame0-_Mapping, NYC_Frame1-_Mapping
	dc.w XZW_Frame2-_Mapping, OOJ_Frame3-_Mapping
	dc.w NQR_Frame4-_Mapping, ZJM_Frame5-_Mapping
	dc.w DOF_Frame6-_Mapping

TUH_Frame0: dc.b  $2
	dc.b  $F4, $6, $0, $2, $F0
	dc.b  $F4, $6, $8, $2, $0
NYC_Frame1: dc.b  $2
	dc.b  $FC, $4, $0, $0, $F0
	dc.b  $FC, $4, $8, $0, $0
XZW_Frame2: dc.b  $1
	dc.b  $FC, $4, $0, $8, $F8
OOJ_Frame3: dc.b  $2
	dc.b  $FC, $0, $0, $A, $F8
	dc.b  $FC, $0, $8, $A, $0
NQR_Frame4: dc.b  $1
	dc.b  $FC, $4, $8, $8, $F8
ZJM_Frame5: dc.b  $1
	dc.b  $FC, $0, $0, $B, $FC
DOF_Frame6: dc.b  $1
	dc.b  $F8, $5, $0, $C, $F8
