; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed May 13 2020 22:53:37 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5O4ZMDKT62M:
	dc.w DATA5O4ZMDKT62M_0-DATA5O4ZMDKT62M, DATA5O4ZMDKT62M_1-DATA5O4ZMDKT62M
	dc.w DATA5O4ZMDKT62M_2-DATA5O4ZMDKT62M, DATA5O4ZMDKT62M_3-DATA5O4ZMDKT62M
	dc.w DATA5O4ZMDKT62M_4-DATA5O4ZMDKT62M
DATA5O4ZMDKT62M_0: dc.b $4
	dc.b $0, $0, $0, $0, $0
	dc.b $0, $0, $8, $0, $F8
	dc.b $F8, $0, $10, $0, $0
	dc.b $F8, $0, $18, $0, $F8
DATA5O4ZMDKT62M_1: dc.b $1
	dc.b $F0, $F, $0, $1, $F0
DATA5O4ZMDKT62M_2: dc.b $1
	dc.b $F0, $F, $0, $11, $F0
DATA5O4ZMDKT62M_3: dc.b $2
	dc.b $F0, $7, $0, $21, $F0
	dc.b $F0, $7, $18, $21, $0
DATA5O4ZMDKT62M_4: dc.b $2
	dc.b $F0, $7, $0, $29, $F0
	dc.b $F0, $7, $18, $29, $0
	even