; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed May 13 2020 22:50:43 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA9G5ZZOFP1P7:
	dc.w DATA9G5ZZOFP1P7_0-DATA9G5ZZOFP1P7, DATA9G5ZZOFP1P7_1-DATA9G5ZZOFP1P7
	dc.w DATA9G5ZZOFP1P7_2-DATA9G5ZZOFP1P7, DATA9G5ZZOFP1P7_3-DATA9G5ZZOFP1P7
	dc.w DATA9G5ZZOFP1P7_4-DATA9G5ZZOFP1P7, DATA9G5ZZOFP1P7_5-DATA9G5ZZOFP1P7
DATA9G5ZZOFP1P7_0: dc.b $1
	dc.b $F9, $5, $0, $5B, $F8
DATA9G5ZZOFP1P7_1: dc.b $1
	dc.b $EE, $A, $0, $49, $F4
DATA9G5ZZOFP1P7_2: dc.b $1
	dc.b $E6, $B, $0, $31, $F4
DATA9G5ZZOFP1P7_3: dc.b $1
	dc.b $E6, $B, $0, $3D, $F4
DATA9G5ZZOFP1P7_4: dc.b $1
	dc.b $EE, $A, $0, $52, $F4
DATA9G5ZZOFP1P7_5: dc.b $1
	dc.b $F9, $9, $0, $5F, $F4
	even