; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Apr 29 2020 15:58:50 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA20O2C2JRI87:
	dc.w DATA20O2C2JRI87_0-DATA20O2C2JRI87, DATA20O2C2JRI87_1-DATA20O2C2JRI87
	dc.w DATA20O2C2JRI87_2-DATA20O2C2JRI87, DATA20O2C2JRI87_3-DATA20O2C2JRI87
	dc.w DATA20O2C2JRI87_4-DATA20O2C2JRI87, DATA20O2C2JRI87_5-DATA20O2C2JRI87
	dc.w DATA20O2C2JRI87_6-DATA20O2C2JRI87, DATA20O2C2JRI87_7-DATA20O2C2JRI87
DATA20O2C2JRI87_0: dc.b $2
	dc.b $F0, $7, $0, $0, $F0
	dc.b $F0, $7, $0, $0, $0
DATA20O2C2JRI87_1: dc.b $4
	dc.b $F0, $7, $0, $0, $E0
	dc.b $F0, $7, $0, $0, $F0
	dc.b $F0, $7, $0, $0, $0
	dc.b $F0, $7, $0, $0, $10
DATA20O2C2JRI87_2: dc.b $6
	dc.b $F0, $7, $0, $0, $D0
	dc.b $F0, $7, $0, $0, $E0
	dc.b $F0, $7, $0, $0, $F0
	dc.b $F0, $7, $0, $0, $0
	dc.b $F0, $7, $0, $0, $10
	dc.b $F0, $7, $0, $0, $20
DATA20O2C2JRI87_3: dc.b $8
	dc.b $F0, $7, $0, $0, $C0
	dc.b $F0, $7, $0, $0, $D0
	dc.b $F0, $7, $0, $0, $E0
	dc.b $F0, $7, $0, $0, $F0
	dc.b $F0, $7, $0, $0, $0
	dc.b $F0, $7, $0, $0, $10
	dc.b $F0, $7, $0, $0, $20
	dc.b $F0, $7, $0, $0, $30
DATA20O2C2JRI87_4: dc.b $2
	dc.b $F0, $D, $0, $8, $F0
	dc.b $0, $D, $0, $8, $F0
DATA20O2C2JRI87_5: dc.b $4
	dc.b $E0, $D, $0, $8, $F0
	dc.b $F0, $D, $0, $8, $F0
	dc.b $0, $D, $0, $8, $F0
	dc.b $10, $D, $0, $8, $F0
DATA20O2C2JRI87_6: dc.b $6
	dc.b $D0, $D, $0, $8, $F0
	dc.b $E0, $D, $0, $8, $F0
	dc.b $F0, $D, $0, $8, $F0
	dc.b $0, $D, $0, $8, $F0
	dc.b $10, $D, $0, $8, $F0
	dc.b $20, $D, $0, $8, $F0
DATA20O2C2JRI87_7: dc.b $8
	dc.b $C0, $D, $0, $8, $F0
	dc.b $D0, $D, $0, $8, $F0
	dc.b $E0, $D, $0, $8, $F0
	dc.b $F0, $D, $0, $8, $F0
	dc.b $0, $D, $0, $8, $F0
	dc.b $10, $D, $0, $8, $F0
	dc.b $20, $D, $0, $8, $F0
	dc.b $30, $D, $0, $8, $F0
	even