; Sprite mappings - generated by Flex - Sonic 1 format

_Mapping99:
	dc.w JXL_Frame0-_Mapping99, VXT_Frame1-_Mapping99
	dc.w HWJ_Frame2-_Mapping99

JXL_Frame0: dc.b  $7
	dc.b  $EC, $C, $0, $0, $F0
	dc.b  $F4, $D, $0, $4, $E8
	dc.b  $4, $4, $0, $C, $E8
	dc.b  $F4, $4, $0, $E, $8
	dc.b  $4, $9, $0, $10, $F8
	dc.b  $4, $0, $0, $15, $10
	dc.b  $FC, $4, $0, $16, $8
VXT_Frame1: dc.b  $7
	dc.b  $ED, $C, $0, $0, $F0
	dc.b  $F5, $D, $0, $4, $E8
	dc.b  $5, $4, $0, $C, $E8
	dc.b  $F5, $4, $0, $E, $8
	dc.b  $5, $9, $0, $18, $F8
	dc.b  $FD, $4, $0, $1E, $8
	dc.b  $5, $0, $0, $20, $10
HWJ_Frame2: dc.b  $7
	dc.b  $EC, $C, $0, $0, $F0
	dc.b  $F4, $D, $0, $4, $E8
	dc.b  $4, $4, $0, $C, $E8
	dc.b  $F4, $4, $0, $E, $8
	dc.b  $4, $9, $0, $21, $F8
	dc.b  $FC, $4, $0, $27, $8
	dc.b  $4, $0, $0, $29, $10
