; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu May 07 2020 18:43:21 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAK9CIX9UD3QI:
	dc.w DATAK9CIX9UD3QI_0-DATAK9CIX9UD3QI, DATAK9CIX9UD3QI_1-DATAK9CIX9UD3QI
	dc.w DATAK9CIX9UD3QI_2-DATAK9CIX9UD3QI, DATAK9CIX9UD3QI_3-DATAK9CIX9UD3QI
	dc.w DATAK9CIX9UD3QI_4-DATAK9CIX9UD3QI, DATAK9CIX9UD3QI_5-DATAK9CIX9UD3QI
	dc.w DATAK9CIX9UD3QI_6-DATAK9CIX9UD3QI, DATAK9CIX9UD3QI_7-DATAK9CIX9UD3QI
	dc.w DATAK9CIX9UD3QI_8-DATAK9CIX9UD3QI, DATAK9CIX9UD3QI_9-DATAK9CIX9UD3QI
	dc.w DATAK9CIX9UD3QI_A-DATAK9CIX9UD3QI
DATAK9CIX9UD3QI_0: dc.b $2
	dc.b $F8, $C, $0, $0, $F0
	dc.b $0, $4, $0, $4, $F8
DATAK9CIX9UD3QI_1: dc.b $1
	dc.b $0, $C, $0, $0, $F0
DATAK9CIX9UD3QI_2: dc.b $2
	dc.b $E8, $C, $0, $0, $F0
	dc.b $F0, $6, $0, $6, $F8
DATAK9CIX9UD3QI_3: dc.b $2
	dc.b $F0, $3, $0, $0, $0
	dc.b $F8, $1, $0, $4, $F8
DATAK9CIX9UD3QI_4: dc.b $1
	dc.b $F0, $3, $0, $0, $F8
DATAK9CIX9UD3QI_5: dc.b $2
	dc.b $F0, $3, $0, $0, $10
	dc.b $F8, $9, $0, $6, $F8
DATAK9CIX9UD3QI_6: dc.b $2
	dc.b $F8, $4, $30, $4, $F8
	dc.b $0, $C, $10, $0, $F0
DATAK9CIX9UD3QI_7: dc.b $5
	dc.b $F0, $8, $0, $0, $F0
	dc.b $F8, $8, $0, $3, $F8
	dc.b $0, $5, $0, $6, $0
	dc.b $FB, $5, $0, $A, $F6
	dc.b $1, $5, $0, $12, $F0
DATAK9CIX9UD3QI_8: dc.b $4
	dc.b $F6, $8, $0, $0, $EA
	dc.b $FE, $8, $0, $3, $F2
	dc.b $6, $5, $0, $6, $FA
	dc.b $1, $5, $0, $12, $F0
DATAK9CIX9UD3QI_9: dc.b $6
	dc.b $E6, $8, $0, $0, $FB
	dc.b $EE, $8, $0, $3, $3
	dc.b $F6, $5, $0, $6, $B
	dc.b $F5, $4, $0, $E, $FF
	dc.b $FD, $4, $0, $10, $F7
	dc.b $1, $5, $0, $12, $F0
DATAK9CIX9UD3QI_A: dc.b $5
	dc.b $8, $8, $10, $0, $F0
	dc.b $0, $8, $10, $3, $F8
	dc.b $F0, $5, $10, $6, $0
	dc.b $F5, $5, $10, $A, $F6
	dc.b $EF, $5, $10, $12, $F0
	even