; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Jun 02 2020 11:17:35 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA9IHUMLRYUUG:
	dc.w DATA9IHUMLRYUUG_0-DATA9IHUMLRYUUG, DATA9IHUMLRYUUG_1-DATA9IHUMLRYUUG
	dc.w DATA9IHUMLRYUUG_2-DATA9IHUMLRYUUG, DATA9IHUMLRYUUG_3-DATA9IHUMLRYUUG
	dc.w DATA9IHUMLRYUUG_4-DATA9IHUMLRYUUG, DATA9IHUMLRYUUG_5-DATA9IHUMLRYUUG
	dc.w DATA9IHUMLRYUUG_6-DATA9IHUMLRYUUG, DATA9IHUMLRYUUG_7-DATA9IHUMLRYUUG
	dc.w DATA9IHUMLRYUUG_8-DATA9IHUMLRYUUG, DATA9IHUMLRYUUG_9-DATA9IHUMLRYUUG
	dc.w DATA9IHUMLRYUUG_A-DATA9IHUMLRYUUG
DATA9IHUMLRYUUG_0: dc.b $2
	dc.b $0, $4, $0, $4, $F8
	dc.b $F8, $C, $0, $C, $F0
DATA9IHUMLRYUUG_1: dc.b $1
	dc.b $0, $C, $0, $C, $F0
DATA9IHUMLRYUUG_2: dc.b $2
	dc.b $F0, $6, $0, $6, $F8
	dc.b $E8, $C, $0, $C, $F0
DATA9IHUMLRYUUG_3: dc.b $2
	dc.b $F8, $1, $0, $4, $F8
	dc.b $F0, $3, $0, $C, $0
DATA9IHUMLRYUUG_4: dc.b $1
	dc.b $F0, $3, $0, $C, $F8
DATA9IHUMLRYUUG_5: dc.b $2
	dc.b $F8, $9, $0, $6, $F8
	dc.b $F0, $3, $0, $C, $10
DATA9IHUMLRYUUG_6: dc.b $2
	dc.b $F8, $4, $30, $4, $F8
	dc.b $0, $C, $10, $0, $F0
DATA9IHUMLRYUUG_7: dc.b $5
	dc.b $FB, $5, $0, $A, $F6
	dc.b $F0, $8, $0, $16, $F1
	dc.b $F8, $8, $0, $19, $F9
	dc.b $0, $5, $0, $1C, $1
	dc.b $1, $5, $0, $12, $F0
DATA9IHUMLRYUUG_8: dc.b $4
	dc.b $F6, $8, $0, $16, $EA
	dc.b $FE, $8, $0, $19, $F2
	dc.b $6, $5, $0, $1C, $FA
	dc.b $1, $5, $0, $12, $F0
DATA9IHUMLRYUUG_9: dc.b $5
	dc.b $F5, $4, $0, $E, $FF
	dc.b $FD, $4, $0, $10, $F7
	dc.b $E6, $8, $0, $16, $FB
	dc.b $EE, $8, $0, $19, $3
	dc.b $F6, $5, $0, $1C, $B
DATA9IHUMLRYUUG_A: dc.b $4
	dc.b $8, $8, $10, $16, $F0
	dc.b $0, $8, $10, $19, $F8
	dc.b $F0, $5, $10, $1C, $0
	dc.b $F5, $5, $10, $12, $F6
	even