; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon May 25 2020 14:08:48 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA13VE31STMU8:
	dc.w DATA13VE31STMU8_0-DATA13VE31STMU8, DATA13VE31STMU8_1-DATA13VE31STMU8
	dc.w DATA13VE31STMU8_2-DATA13VE31STMU8
DATA13VE31STMU8_0: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
DATA13VE31STMU8_1: dc.b $1
	dc.b $FC, $0, $0, $E, $FC
DATA13VE31STMU8_2: dc.b $1
	dc.b $FC, $0, $0, $F, $FC
	even