; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon May 25 2020 14:04:58 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA744IRQLM6IK:
	dc.w DATA744IRQLM6IK_0-DATA744IRQLM6IK, DATA744IRQLM6IK_1-DATA744IRQLM6IK
	dc.w DATA744IRQLM6IK_2-DATA744IRQLM6IK, DATA744IRQLM6IK_3-DATA744IRQLM6IK
	dc.w DATA744IRQLM6IK_4-DATA744IRQLM6IK
DATA744IRQLM6IK_0: dc.b $4
	dc.b $E8, $1, $0, $4, $FC
	dc.b $F8, $3, $0, $6, $F8
	dc.b $F8, $3, $8, $6, $0
	dc.b $D8, $5, $0, $10, $F8
DATA744IRQLM6IK_1: dc.b $3
	dc.b $E8, $1, $0, $4, $FC
	dc.b $F8, $3, $0, $6, $F8
	dc.b $F8, $3, $8, $6, $0
DATA744IRQLM6IK_2: dc.b $1
	dc.b $F8, $5, $0, $10, $F8
DATA744IRQLM6IK_3: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATA744IRQLM6IK_4: dc.b $4
	dc.b $E8, $1, $0, $4, $FC
	dc.b $F8, $3, $0, $6, $F8
	dc.b $F8, $3, $8, $6, $0
	dc.b $D8, $5, $0, $0, $F8
	even