; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Apr 09 2018 20:48:02 GMT-0400 (Eastern Daylight Time)
; ================================================================================

GoalRing:
	dc.w GoalRing_0-GoalRing, GoalRing_1-GoalRing
	dc.w GoalRing_2-GoalRing, GoalRing_3-GoalRing
	dc.w GoalRing_4-GoalRing
GoalRing_0: dc.b $F
	dc.b $DC, $F, $20, $0, $F0
	dc.b $E4, $7, $20, $10, $E0
	dc.b $E4, $7, $20, $18, $10
	dc.b $FC, $D, $20, $20, $F0
	dc.b $4, $6, $20, $28, $E0
	dc.b $4, $6, $20, $2E, $10
	dc.b $C, $2, $20, $34, $F0
	dc.b $C, $2, $20, $37, $8
	dc.b $14, $5, $20, $3A, $F8
	dc.b $F4, $2, $0, $3E, $EC
	dc.b $EC, $4, $0, $41, $F4
	dc.b $C, $4, $0, $43, $F4
	dc.b $F4, $2, $8, $3E, $C
	dc.b $EC, $4, $8, $41, $FC
	dc.b $C, $4, $8, $43, $FC
GoalRing_1: dc.b $8
	dc.b $E8, $F, $20, $0, $E7
	dc.b $8, $D, $20, $10, $E7
	dc.b $E0, $C, $20, $18, $EF
	dc.b $18, $C, $20, $1C, $EF
	dc.b $E8, $7, $20, $20, $7
	dc.b $8, $5, $20, $28, $7
	dc.b $ED, $B, $0, $2C, $F0
	dc.b $D, $4, $0, $38, $F8
GoalRing_2: dc.b $2
	dc.b $E0, $B, $20, $0, $F4
	dc.b $0, $B, $20, $C, $F4
GoalRing_3: dc.b $8
	dc.b $E8, $F, $28, $0, $F8
	dc.b $8, $D, $28, $10, $F8
	dc.b $E0, $C, $28, $18, $F0
	dc.b $18, $C, $28, $1C, $F0
	dc.b $E8, $7, $28, $20, $E8
	dc.b $8, $5, $28, $28, $E8
	dc.b $ED, $B, $8, $2C, $F7
	dc.b $D, $4, $8, $38, $F7
GoalRing_4: dc.b $2
	dc.b $E6, $B, $0, $0, $FC
	dc.b $6, $4, $0, $C, $4
	even