; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed May 27 2020 20:37:06 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAIV8VAWDZKKH:
	dc.w DATAIV8VAWDZKKH_0-DATAIV8VAWDZKKH
DATAIV8VAWDZKKH_0: dc.b $4
	dc.b $E0, $5, $0, $0, $F8
	dc.b $F0, $2, $0, $4, $FC
	dc.b $8, $2, $0, $7, $F8
	dc.b $8, $2, $8, $7, $0
	even