; Sprite mappings - generated by Flex - Sonic 1 format

SME_z1Gdy:
	dc.w DQZ_Frame0-SME_z1Gdy

DQZ_Frame0: dc.b  $5
	dc.b  $E0, $5, $60, $0, $F8
	dc.b  $F0, $3, $0, $4, $F8
	dc.b  $10, $1, $0, $8, $F8
	dc.b  $F0, $3, $8, $4, $0
	dc.b  $10, $1, $8, $8, $0
