; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Mar 13 2018 13:07:48 GMT-0500 (Eastern Standard Time)
; ================================================================================

GoalRing:
	dc.w GoalRing_0-GoalRing, GoalRing_1-GoalRing
	dc.w GoalRing_2-GoalRing, GoalRing_3-GoalRing
	dc.w GoalRing_4-GoalRing, GoalRing_5-GoalRing
	dc.w GoalRing_6-GoalRing, GoalRing_7-GoalRing
	dc.w GoalRing_8-GoalRing
GoalRing_0: dc.b $F
	dc.b $DC, $F, $20, $0, $F0
	dc.b $E4, $7, $20, $10, $E0
	dc.b $E4, $7, $20, $18, $10
	dc.b $FC, $D, $20, $20, $F0
	dc.b $4, $6, $20, $28, $E0
	dc.b $4, $6, $20, $2E, $10
	dc.b $C, $2, $20, $34, $F0
	dc.b $C, $2, $20, $37, $8
	dc.b $14, $5, $20, $3A, $F8
	dc.b $F4, $6, $0, $3E, $E8
	dc.b $EC, $4, $0, $44, $F0
	dc.b $C, $4, $0, $46, $F0
	dc.b $F4, $6, $8, $3E, $8
	dc.b $EC, $4, $8, $44, $0
	dc.b $C, $4, $8, $46, $0
GoalRing_1: dc.b $8
	dc.b $E8, $F, $20, $0, $E8
	dc.b $8, $D, $20, $10, $E8
	dc.b $E0, $C, $20, $18, $F0
	dc.b $18, $C, $20, $1C, $F0
	dc.b $E8, $7, $20, $20, $8
	dc.b $8, $5, $20, $28, $8
	dc.b $ED, $B, $0, $2C, $F1
	dc.b $D, $4, $0, $38, $F9
GoalRing_2: dc.b $2
	dc.b $E0, $B, $20, $0, $F6
	dc.b $0, $B, $20, $C, $F6
GoalRing_3: dc.b $4
	dc.b $DC, $7, $0, $0, $FF
	dc.b $E4, $7, $0, $8, $F
	dc.b $4, $7, $10, $0, $FF
	dc.b $FC, $7, $10, $8, $F
GoalRing_4: dc.b $8
	dc.b $E0, $E, $0, $0, $EF
	dc.b $F8, $C, $0, $C, $F7
	dc.b $E0, $2, $0, $10, $F
	dc.b $E8, $2, $0, $13, $17
	dc.b $8, $E, $10, $0, $EF
	dc.b $0, $C, $10, $C, $F7
	dc.b $8, $2, $10, $10, $F
	dc.b $0, $2, $10, $13, $17
GoalRing_5: dc.b $6
	dc.b $E0, $F, $0, $0, $E7
	dc.b $0, $7, $10, $10, $7
	dc.b $0, $2, $10, $18, $17
	dc.b $0, $F, $10, $0, $E7
	dc.b $E0, $7, $0, $10, $7
	dc.b $E8, $2, $0, $18, $17
GoalRing_6: dc.b $6
	dc.b $E0, $F, $8, $0, $F7
	dc.b $0, $7, $18, $10, $E7
	dc.b $0, $2, $18, $18, $DF
	dc.b $0, $F, $18, $0, $F7
	dc.b $E0, $7, $8, $10, $E7
	dc.b $E8, $2, $8, $18, $DF
GoalRing_7: dc.b $8
	dc.b $E0, $E, $8, $0, $EF
	dc.b $F8, $C, $8, $C, $E7
	dc.b $E0, $2, $8, $10, $E7
	dc.b $E8, $2, $8, $13, $DF
	dc.b $8, $E, $18, $0, $EF
	dc.b $0, $C, $18, $C, $E7
	dc.b $8, $2, $18, $10, $E7
	dc.b $0, $2, $18, $13, $DF
GoalRing_8: dc.b $4
	dc.b $DC, $7, $8, $0, $EF
	dc.b $E4, $7, $8, $8, $DF
	dc.b $4, $7, $18, $0, $EF
	dc.b $FC, $7, $18, $8, $DF
	even