; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jun 15 2020 21:40:28 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA2ESUK69M67C:
	dc.w $0, DATA2ESUK69M67C_1-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_2-DATA2ESUK69M67C, DATA2ESUK69M67C_3-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_4-DATA2ESUK69M67C, DATA2ESUK69M67C_5-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_6-DATA2ESUK69M67C, DATA2ESUK69M67C_7-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_8-DATA2ESUK69M67C, DATA2ESUK69M67C_9-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_A-DATA2ESUK69M67C, DATA2ESUK69M67C_B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_C-DATA2ESUK69M67C, DATA2ESUK69M67C_D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_E-DATA2ESUK69M67C, DATA2ESUK69M67C_F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_10-DATA2ESUK69M67C, DATA2ESUK69M67C_11-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_12-DATA2ESUK69M67C, DATA2ESUK69M67C_13-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_14-DATA2ESUK69M67C, DATA2ESUK69M67C_15-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_16-DATA2ESUK69M67C, DATA2ESUK69M67C_17-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_18-DATA2ESUK69M67C, DATA2ESUK69M67C_19-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_1A-DATA2ESUK69M67C, DATA2ESUK69M67C_1B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_1C-DATA2ESUK69M67C, DATA2ESUK69M67C_1D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_1E-DATA2ESUK69M67C, DATA2ESUK69M67C_1F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_20-DATA2ESUK69M67C, DATA2ESUK69M67C_21-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_22-DATA2ESUK69M67C, DATA2ESUK69M67C_23-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_24-DATA2ESUK69M67C, DATA2ESUK69M67C_25-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_26-DATA2ESUK69M67C, DATA2ESUK69M67C_27-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_28-DATA2ESUK69M67C, DATA2ESUK69M67C_29-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_2A-DATA2ESUK69M67C, DATA2ESUK69M67C_2B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_2C-DATA2ESUK69M67C, DATA2ESUK69M67C_2D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_2E-DATA2ESUK69M67C, DATA2ESUK69M67C_2F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_30-DATA2ESUK69M67C, DATA2ESUK69M67C_31-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_32-DATA2ESUK69M67C, DATA2ESUK69M67C_33-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_34-DATA2ESUK69M67C, DATA2ESUK69M67C_35-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_36-DATA2ESUK69M67C, DATA2ESUK69M67C_37-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_38-DATA2ESUK69M67C, DATA2ESUK69M67C_39-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_3A-DATA2ESUK69M67C, DATA2ESUK69M67C_3B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_3C-DATA2ESUK69M67C, DATA2ESUK69M67C_3D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_3E-DATA2ESUK69M67C, DATA2ESUK69M67C_3F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_40-DATA2ESUK69M67C, DATA2ESUK69M67C_41-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_42-DATA2ESUK69M67C, DATA2ESUK69M67C_43-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_44-DATA2ESUK69M67C, DATA2ESUK69M67C_45-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_46-DATA2ESUK69M67C, DATA2ESUK69M67C_47-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_48-DATA2ESUK69M67C, DATA2ESUK69M67C_49-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_4A-DATA2ESUK69M67C, DATA2ESUK69M67C_4B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_4C-DATA2ESUK69M67C, DATA2ESUK69M67C_4D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_4E-DATA2ESUK69M67C, DATA2ESUK69M67C_4F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_50-DATA2ESUK69M67C, DATA2ESUK69M67C_51-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_52-DATA2ESUK69M67C, DATA2ESUK69M67C_53-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_54-DATA2ESUK69M67C, DATA2ESUK69M67C_55-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_56-DATA2ESUK69M67C, DATA2ESUK69M67C_57-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_58-DATA2ESUK69M67C, DATA2ESUK69M67C_59-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_5A-DATA2ESUK69M67C, DATA2ESUK69M67C_5B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_5C-DATA2ESUK69M67C, DATA2ESUK69M67C_5D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_5E-DATA2ESUK69M67C, DATA2ESUK69M67C_5F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_60-DATA2ESUK69M67C, DATA2ESUK69M67C_61-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_62-DATA2ESUK69M67C, DATA2ESUK69M67C_63-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_64-DATA2ESUK69M67C, DATA2ESUK69M67C_65-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_66-DATA2ESUK69M67C, DATA2ESUK69M67C_67-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_68-DATA2ESUK69M67C, DATA2ESUK69M67C_69-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_6A-DATA2ESUK69M67C, DATA2ESUK69M67C_6B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_6C-DATA2ESUK69M67C, DATA2ESUK69M67C_6D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_6E-DATA2ESUK69M67C, DATA2ESUK69M67C_6F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_70-DATA2ESUK69M67C, DATA2ESUK69M67C_71-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_72-DATA2ESUK69M67C, DATA2ESUK69M67C_73-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_74-DATA2ESUK69M67C, DATA2ESUK69M67C_75-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_76-DATA2ESUK69M67C, DATA2ESUK69M67C_77-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_78-DATA2ESUK69M67C, DATA2ESUK69M67C_79-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_7A-DATA2ESUK69M67C, DATA2ESUK69M67C_7B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_7C-DATA2ESUK69M67C, DATA2ESUK69M67C_7D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_7E-DATA2ESUK69M67C, DATA2ESUK69M67C_7F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_80-DATA2ESUK69M67C, DATA2ESUK69M67C_81-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_82-DATA2ESUK69M67C, DATA2ESUK69M67C_83-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_84-DATA2ESUK69M67C, DATA2ESUK69M67C_85-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_86-DATA2ESUK69M67C, DATA2ESUK69M67C_87-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_88-DATA2ESUK69M67C, DATA2ESUK69M67C_89-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_8A-DATA2ESUK69M67C, DATA2ESUK69M67C_8B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_8C-DATA2ESUK69M67C, DATA2ESUK69M67C_8D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_8E-DATA2ESUK69M67C, DATA2ESUK69M67C_8F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_90-DATA2ESUK69M67C, DATA2ESUK69M67C_91-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_92-DATA2ESUK69M67C, DATA2ESUK69M67C_93-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_94-DATA2ESUK69M67C, DATA2ESUK69M67C_95-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_96-DATA2ESUK69M67C, DATA2ESUK69M67C_97-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_98-DATA2ESUK69M67C, DATA2ESUK69M67C_99-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_9A-DATA2ESUK69M67C, DATA2ESUK69M67C_9B-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_9C-DATA2ESUK69M67C, DATA2ESUK69M67C_9D-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_9E-DATA2ESUK69M67C, DATA2ESUK69M67C_9F-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_A0-DATA2ESUK69M67C, DATA2ESUK69M67C_A1-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_A2-DATA2ESUK69M67C, DATA2ESUK69M67C_A3-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_A4-DATA2ESUK69M67C, DATA2ESUK69M67C_A5-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_A6-DATA2ESUK69M67C, DATA2ESUK69M67C_A7-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_A8-DATA2ESUK69M67C, DATA2ESUK69M67C_A9-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_AA-DATA2ESUK69M67C, DATA2ESUK69M67C_AB-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_AC-DATA2ESUK69M67C, DATA2ESUK69M67C_AD-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_AE-DATA2ESUK69M67C, DATA2ESUK69M67C_AF-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_B0-DATA2ESUK69M67C, DATA2ESUK69M67C_B1-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_B2-DATA2ESUK69M67C, DATA2ESUK69M67C_B3-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_B4-DATA2ESUK69M67C, DATA2ESUK69M67C_B5-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_B6-DATA2ESUK69M67C, DATA2ESUK69M67C_B7-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_B8-DATA2ESUK69M67C, DATA2ESUK69M67C_B9-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_BA-DATA2ESUK69M67C, DATA2ESUK69M67C_BB-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_BC-DATA2ESUK69M67C, DATA2ESUK69M67C_BD-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_BE-DATA2ESUK69M67C, DATA2ESUK69M67C_BF-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_C0-DATA2ESUK69M67C, DATA2ESUK69M67C_C1-DATA2ESUK69M67C
	dc.w DATA2ESUK69M67C_C2-DATA2ESUK69M67C, DATA2ESUK69M67C_C3-DATA2ESUK69M67C
DATA2ESUK69M67C_1: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATA2ESUK69M67C_2: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F8
DATA2ESUK69M67C_3: dc.b $4
	dc.b $E7, $E, $0, $0, $F0
	dc.b $FF, $8, $0, $C, $F0
	dc.b $7, $5, $0, $F, $F8
	dc.b $F, $0, $0, $13, $8
DATA2ESUK69M67C_4: dc.b $4
	dc.b $E8, $7, $0, $0, $F9
	dc.b $F0, $2, $0, $8, $F1
	dc.b $F0, $1, $0, $B, $9
	dc.b $8, $9, $0, $D, $F9
DATA2ESUK69M67C_5: dc.b $4
	dc.b $E8, $7, $0, $0, $F9
	dc.b $F0, $2, $0, $8, $F1
	dc.b $F0, $1, $0, $B, $9
	dc.b $8, $9, $0, $D, $F9
DATA2ESUK69M67C_6: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATA2ESUK69M67C_7: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $8
	dc.b $C, $8, $0, $D, $F8
DATA2ESUK69M67C_8: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $8
	dc.b $C, $8, $0, $D, $F8
DATA2ESUK69M67C_9: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $8
	dc.b $C, $8, $0, $D, $F9
DATA2ESUK69M67C_A: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $F4, $0, $0, $9, $8
	dc.b $4, $5, $0, $A, $F8
	dc.b $C, $0, $0, $E, $8
DATA2ESUK69M67C_B: dc.b $4
	dc.b $EC, $A, $0, $0, $F1
	dc.b $F4, $0, $0, $9, $9
	dc.b $4, $5, $0, $A, $F9
	dc.b $C, $0, $0, $E, $9
DATA2ESUK69M67C_C: dc.b $3
	dc.b $ED, $B, $0, $0, $EF
	dc.b $F5, $3, $0, $C, $7
	dc.b $D, $4, $0, $10, $F7
DATA2ESUK69M67C_D: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $FD, $2, $0, $C, $C
	dc.b $5, $9, $0, $F, $F4
DATA2ESUK69M67C_E: dc.b $4
	dc.b $E8, $B, $0, $0, $EF
	dc.b $F0, $0, $0, $C, $7
	dc.b $0, $2, $0, $D, $7
	dc.b $8, $5, $0, $10, $F7
DATA2ESUK69M67C_F: dc.b $3
	dc.b $EC, $B, $0, $0, $EE
	dc.b $FC, $2, $0, $C, $6
	dc.b $C, $4, $0, $F, $F6
DATA2ESUK69M67C_10: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F0
DATA2ESUK69M67C_11: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $F4, $3, $0, $E, $C
	dc.b $C, $4, $0, $12, $FC
DATA2ESUK69M67C_12: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $FC, $2, $0, $E, $C
	dc.b $C, $4, $0, $11, $FC
DATA2ESUK69M67C_13: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $FC, $2, $0, $E, $C
	dc.b $C, $4, $0, $11, $FC
DATA2ESUK69M67C_14: dc.b $3
	dc.b $EC, $E, $0, $0, $F2
	dc.b $F4, $3, $0, $C, $12
	dc.b $4, $9, $0, $10, $FA
DATA2ESUK69M67C_15: dc.b $3
	dc.b $EC, $F, $0, $0, $F0
	dc.b $FC, $1, $0, $10, $10
	dc.b $C, $8, $0, $12, $F8
DATA2ESUK69M67C_16: dc.b $3
	dc.b $EC, $E, $0, $0, $F0
	dc.b $F4, $3, $0, $C, $10
	dc.b $4, $9, $0, $10, $F8
DATA2ESUK69M67C_17: dc.b $3
	dc.b $EF, $B, $0, $0, $F7
	dc.b $F7, $3, $0, $C, $F
	dc.b $F, $8, $0, $10, $F7
DATA2ESUK69M67C_18: dc.b $2
	dc.b $F6, $B, $0, $0, $FF
	dc.b $FE, $2, $0, $C, $F7
DATA2ESUK69M67C_19: dc.b $2
	dc.b $F4, $E, $0, $0, $E4
	dc.b $F4, $A, $0, $C, $4
DATA2ESUK69M67C_1A: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATA2ESUK69M67C_1B: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $FC, $2, $0, $9, $8
	dc.b $4, $5, $0, $C, $F8
DATA2ESUK69M67C_1C: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATA2ESUK69M67C_1D: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATA2ESUK69M67C_1E: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATA2ESUK69M67C_1F: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA2ESUK69M67C_20: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATA2ESUK69M67C_21: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA2ESUK69M67C_22: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F0
DATA2ESUK69M67C_23: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F0
DATA2ESUK69M67C_24: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F0
DATA2ESUK69M67C_25: dc.b $3
	dc.b $EC, $A, $0, $0, $F8
	dc.b $FC, $2, $0, $9, $F0
	dc.b $4, $5, $0, $C, $F8
DATA2ESUK69M67C_26: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATA2ESUK69M67C_27: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATA2ESUK69M67C_28: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATA2ESUK69M67C_29: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATA2ESUK69M67C_2A: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATA2ESUK69M67C_2B: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATA2ESUK69M67C_2C: dc.b $1
	dc.b $F0, $F, $8, $0, $F0
DATA2ESUK69M67C_2D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA2ESUK69M67C_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA2ESUK69M67C_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA2ESUK69M67C_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA2ESUK69M67C_31: dc.b $4
	dc.b $E4, $F, $0, $0, $F0
	dc.b $4, $6, $0, $10, $F8
	dc.b $C, $1, $0, $16, $8
	dc.b $14, $0, $0, $18, $F0
DATA2ESUK69M67C_32: dc.b $4
	dc.b $E7, $E, $0, $0, $F1
	dc.b $FF, $6, $0, $C, $F9
	dc.b $F, $0, $0, $12, $F1
	dc.b $F, $0, $0, $13, $9
DATA2ESUK69M67C_33: dc.b $2
	dc.b $7, $D, $0, $0, $EB
	dc.b $EF, $A, $0, $8, $F3
DATA2ESUK69M67C_34: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATA2ESUK69M67C_35: dc.b $2
	dc.b $7, $D, $0, $0, $EB
	dc.b $EF, $A, $0, $8, $F3
DATA2ESUK69M67C_36: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATA2ESUK69M67C_37: dc.b $5
	dc.b $E8, $E, $0, $0, $EC
	dc.b $E8, $2, $0, $C, $C
	dc.b $0, $8, $0, $F, $F4
	dc.b $8, $5, $0, $12, $EC
	dc.b $8, $5, $0, $16, $4
DATA2ESUK69M67C_38: dc.b $5
	dc.b $E8, $E, $0, $0, $EC
	dc.b $E8, $2, $0, $C, $C
	dc.b $0, $8, $0, $F, $F4
	dc.b $8, $5, $0, $12, $EC
	dc.b $8, $5, $0, $16, $4
DATA2ESUK69M67C_39: dc.b $6
	dc.b $EC, $D, $0, $0, $EC
	dc.b $EC, $1, $0, $8, $C
	dc.b $FC, $9, $0, $A, $F4
	dc.b $4, $1, $0, $10, $EC
	dc.b $C, $0, $0, $12, $F4
	dc.b $C, $4, $0, $13, $4
DATA2ESUK69M67C_3A: dc.b $5
	dc.b $E8, $B, $0, $0, $EE
	dc.b $E8, $1, $0, $C, $E
	dc.b $F0, $2, $0, $E, $6
	dc.b $8, $8, $0, $11, $EE
	dc.b $10, $4, $0, $14, $F6
DATA2ESUK69M67C_3B: dc.b $4
	dc.b $E8, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $0, $9, $0, $E, $F4
	dc.b $10, $4, $0, $14, $F4
DATA2ESUK69M67C_3C: dc.b $4
	dc.b $E8, $B, $0, $0, $F4
	dc.b $F0, $1, $0, $C, $EC
	dc.b $0, $1, $0, $E, $C
	dc.b $8, $5, $0, $10, $F4
DATA2ESUK69M67C_3D: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F0, $2, $0, $10, $C
DATA2ESUK69M67C_3E: dc.b $3
	dc.b $F0, $E, $0, $0, $EB
	dc.b $F0, $2, $0, $C, $B
	dc.b $8, $8, $0, $F, $F3
DATA2ESUK69M67C_3F: dc.b $4
	dc.b $E8, $B, $0, $0, $F0
	dc.b $F0, $3, $0, $C, $8
	dc.b $8, $9, $0, $10, $F0
	dc.b $10, $0, $0, $16, $8
DATA2ESUK69M67C_40: dc.b $3
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $8, $0, $C, $F8
	dc.b $8, $9, $0, $F, $F0
DATA2ESUK69M67C_41: dc.b $3
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $9, $0, $10, $F0
	dc.b $10, $0, $0, $16, $8
DATA2ESUK69M67C_42: dc.b $3
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $9, $0, $10, $F0
	dc.b $10, $0, $0, $16, $8
DATA2ESUK69M67C_43: dc.b $4
	dc.b $EC, $F, $0, $0, $EC
	dc.b $FC, $2, $0, $10, $C
	dc.b $C, $4, $0, $13, $EC
	dc.b $C, $0, $0, $15, $4
DATA2ESUK69M67C_44: dc.b $3
	dc.b $ED, $F, $0, $0, $EC
	dc.b $5, $1, $0, $10, $C
	dc.b $D, $C, $0, $12, $EC
DATA2ESUK69M67C_45: dc.b $2
	dc.b $ED, $E, $0, $0, $EF
	dc.b $5, $9, $0, $C, $EF
DATA2ESUK69M67C_46: dc.b $2
	dc.b $EC, $F, $0, $0, $EF
	dc.b $C, $C, $0, $10, $EF
DATA2ESUK69M67C_47: dc.b $4
	dc.b $EC, $F, $0, $0, $EC
	dc.b $FC, $1, $0, $10, $C
	dc.b $C, $4, $0, $12, $EC
	dc.b $C, $0, $0, $14, $4
DATA2ESUK69M67C_48: dc.b $4
	dc.b $ED, $F, $0, $0, $EC
	dc.b $5, $1, $0, $10, $C
	dc.b $D, $4, $0, $12, $EC
	dc.b $D, $0, $0, $14, $4
DATA2ESUK69M67C_49: dc.b $4
	dc.b $ED, $E, $0, $0, $EF
	dc.b $5, $5, $0, $C, $F7
	dc.b $D, $0, $0, $10, $EF
	dc.b $D, $0, $0, $11, $7
DATA2ESUK69M67C_4A: dc.b $2
	dc.b $EC, $F, $0, $0, $EE
	dc.b $C, $C, $0, $10, $EE
DATA2ESUK69M67C_4B: dc.b $5
	dc.b $ED, $E, $0, $0, $ED
	dc.b $ED, $2, $0, $C, $D
	dc.b $F5, $1, $0, $F, $E5
	dc.b $5, $8, $0, $11, $ED
	dc.b $D, $5, $0, $14, $F5
DATA2ESUK69M67C_4C: dc.b $7
	dc.b $EE, $7, $0, $0, $F0
	dc.b $F6, $1, $0, $8, $E8
	dc.b $F6, $3, $0, $A, $0
	dc.b $F6, $2, $0, $E, $10
	dc.b $FE, $1, $0, $11, $8
	dc.b $E, $1, $0, $13, $F8
	dc.b $16, $0, $0, $15, $0
DATA2ESUK69M67C_4D: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $8, $0, $10, $FA
DATA2ESUK69M67C_4E: dc.b $5
	dc.b $ED, $E, $0, $0, $E8
	dc.b $F5, $3, $0, $C, $8
	dc.b $FD, $1, $0, $10, $10
	dc.b $5, $8, $0, $12, $F0
	dc.b $D, $4, $0, $15, $F8
DATA2ESUK69M67C_4F: dc.b $4
	dc.b $EC, $F, $0, $0, $EA
	dc.b $F4, $2, $0, $10, $A
	dc.b $C, $4, $0, $13, $F2
	dc.b $14, $4, $0, $15, $FA
DATA2ESUK69M67C_50: dc.b $5
	dc.b $ED, $B, $0, $0, $F1
	dc.b $F5, $1, $0, $C, $E9
	dc.b $F5, $6, $0, $E, $9
	dc.b $D, $4, $0, $14, $F9
	dc.b $15, $0, $0, $16, $F9
DATA2ESUK69M67C_51: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $4, $0, $10, $2
DATA2ESUK69M67C_52: dc.b $4
	dc.b $EF, $E, $0, $0, $E7
	dc.b $F7, $3, $0, $C, $7
	dc.b $FF, $1, $0, $10, $F
	dc.b $7, $5, $0, $12, $F7
DATA2ESUK69M67C_53: dc.b $4
	dc.b $EC, $A, $0, $0, $FD
	dc.b $F4, $7, $0, $9, $ED
	dc.b $4, $8, $0, $11, $FD
	dc.b $C, $4, $0, $14, $5
DATA2ESUK69M67C_54: dc.b $3
	dc.b $EC, $7, $0, $0, $5
	dc.b $F4, $B, $0, $8, $ED
	dc.b $C, $4, $0, $14, $5
DATA2ESUK69M67C_55: dc.b $2
	dc.b $F5, $E, $0, $0, $ED
	dc.b $F5, $2, $0, $C, $D
DATA2ESUK69M67C_56: dc.b $2
	dc.b $F1, $F, $0, $0, $ED
	dc.b $F1, $3, $0, $10, $D
DATA2ESUK69M67C_57: dc.b $3
	dc.b $EC, $B, $0, $0, $FD
	dc.b $F4, $7, $0, $C, $ED
	dc.b $C, $8, $0, $14, $FD
DATA2ESUK69M67C_58: dc.b $4
	dc.b $EC, $A, $0, $0, $FD
	dc.b $F4, $7, $0, $9, $ED
	dc.b $4, $8, $0, $11, $FD
	dc.b $C, $4, $0, $14, $5
DATA2ESUK69M67C_59: dc.b $3
	dc.b $F1, $E, $0, $0, $ED
	dc.b $F1, $2, $0, $C, $D
	dc.b $9, $8, $0, $F, $ED
DATA2ESUK69M67C_5A: dc.b $2
	dc.b $F2, $F, $0, $0, $EC
	dc.b $F2, $3, $0, $10, $C
DATA2ESUK69M67C_5B: dc.b $4
	dc.b $E4, $B, $0, $0, $E4
	dc.b $F4, $9, $0, $C, $FC
	dc.b $4, $C, $0, $12, $E4
	dc.b $C, $4, $0, $16, $EC
DATA2ESUK69M67C_5C: dc.b $6
	dc.b $E4, $8, $0, $0, $EC
	dc.b $EC, $7, $0, $3, $F4
	dc.b $F4, $3, $0, $B, $EC
	dc.b $F4, $5, $0, $F, $4
	dc.b $FC, $1, $0, $13, $E4
	dc.b $C, $0, $0, $15, $F4
DATA2ESUK69M67C_5D: dc.b $3
	dc.b $E8, $6, $0, $0, $0
	dc.b $F0, $B, $0, $6, $E8
	dc.b $0, $0, $0, $12, $0
DATA2ESUK69M67C_5E: dc.b $6
	dc.b $E4, $7, $0, $0, $F8
	dc.b $EC, $3, $0, $8, $F0
	dc.b $EC, $2, $0, $C, $8
	dc.b $F4, $3, $0, $F, $E8
	dc.b $4, $4, $0, $13, $F8
	dc.b $C, $4, $0, $15, $F0
DATA2ESUK69M67C_5F: dc.b $5
	dc.b $E8, $B, $0, $0, $EC
	dc.b $F0, $3, $0, $C, $E4
	dc.b $F0, $5, $0, $10, $4
	dc.b $0, $0, $0, $14, $4
	dc.b $8, $4, $0, $15, $EC
DATA2ESUK69M67C_60: dc.b $6
	dc.b $E4, $B, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $E4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
	dc.b $4, $8, $0, $12, $EC
	dc.b $C, $4, $0, $15, $EC
DATA2ESUK69M67C_61: dc.b $3
	dc.b $E8, $5, $0, $0, $0
	dc.b $F0, $B, $0, $4, $E8
	dc.b $F8, $1, $0, $10, $0
DATA2ESUK69M67C_62: dc.b $6
	dc.b $E4, $7, $0, $0, $F8
	dc.b $EC, $3, $0, $8, $F0
	dc.b $EC, $1, $0, $C, $8
	dc.b $F4, $2, $0, $E, $E8
	dc.b $4, $4, $0, $11, $F8
	dc.b $C, $4, $0, $13, $F0
DATA2ESUK69M67C_63: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F8
DATA2ESUK69M67C_64: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $4, $0, $10, $F8
DATA2ESUK69M67C_65: dc.b $3
	dc.b $F0, $7, $0, $0, $F8
	dc.b $F8, $1, $0, $8, $F0
	dc.b $F8, $2, $0, $A, $8
DATA2ESUK69M67C_66: dc.b $2
	dc.b $F0, $B, $0, $0, $F8
	dc.b $F8, $2, $0, $C, $F0
DATA2ESUK69M67C_67: dc.b $3
	dc.b $F0, $7, $0, $0, $F8
	dc.b $F8, $2, $0, $8, $F0
	dc.b $F8, $2, $0, $B, $8
DATA2ESUK69M67C_68: dc.b $3
	dc.b $EC, $7, $0, $0, $0
	dc.b $F4, $7, $0, $8, $F0
	dc.b $C, $4, $0, $10, $0
DATA2ESUK69M67C_69: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F0
DATA2ESUK69M67C_6A: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $4, $0, $C, $FC
DATA2ESUK69M67C_6B: dc.b $2
	dc.b $F0, $B, $0, $0, $F0
	dc.b $F8, $1, $0, $C, $8
DATA2ESUK69M67C_6C: dc.b $2
	dc.b $F0, $E, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
DATA2ESUK69M67C_6D: dc.b $3
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $8, $0, $C, $F8
	dc.b $C, $4, $0, $F, $F8
DATA2ESUK69M67C_6E: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATA2ESUK69M67C_6F: dc.b $3
	dc.b $EC, $F, $0, $0, $EF
	dc.b $C, $C, $0, $10, $EF
	dc.b $4, $0, $0, $14, $F
DATA2ESUK69M67C_70: dc.b $3
	dc.b $F5, $D, $0, $0, $E9
	dc.b $ED, $8, $0, $8, $F1
	dc.b $5, $6, $0, $B, $F9
DATA2ESUK69M67C_71: dc.b $3
	dc.b $E9, $E, $0, $0, $F3
	dc.b $F9, $1, $0, $C, $EB
	dc.b $1, $A, $0, $E, $F3
DATA2ESUK69M67C_72: dc.b $4
	dc.b $EA, $E, $0, $0, $F1
	dc.b $F2, $1, $0, $C, $E9
	dc.b $2, $6, $0, $E, $F9
	dc.b $12, $0, $0, $14, $9
DATA2ESUK69M67C_73: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATA2ESUK69M67C_74: dc.b $2
	dc.b $F4, $E, $8, $0, $F4
	dc.b $4, $0, $8, $C, $EC
DATA2ESUK69M67C_75: dc.b $2
	dc.b $F4, $E, $8, $0, $F8
	dc.b $FC, $5, $8, $C, $E8
DATA2ESUK69M67C_76: dc.b $2
	dc.b $F4, $E, $8, $0, $EC
	dc.b $4, $0, $8, $C, $C
DATA2ESUK69M67C_77: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATA2ESUK69M67C_78: dc.b $2
	dc.b $F4, $E, $0, $0, $F4
	dc.b $4, $0, $0, $C, $EC
DATA2ESUK69M67C_79: dc.b $2
	dc.b $F4, $E, $0, $0, $E8
	dc.b $FC, $5, $0, $C, $8
DATA2ESUK69M67C_7A: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $4, $0, $0, $C, $C
DATA2ESUK69M67C_7B: dc.b $3
	dc.b $F, $C, $0, $0, $EF
	dc.b $EF, $B, $0, $4, $F7
	dc.b $F7, $3, $0, $10, $F
DATA2ESUK69M67C_7C: dc.b $3
	dc.b $D, $C, $0, $0, $ED
	dc.b $F5, $E, $0, $4, $F5
	dc.b $ED, $4, $0, $10, $FD
DATA2ESUK69M67C_7D: dc.b $4
	dc.b $EE, $B, $0, $0, $F7
	dc.b $F6, $2, $0, $C, $F
	dc.b $FE, $6, $0, $F, $E7
	dc.b $E, $8, $0, $15, $F7
DATA2ESUK69M67C_7E: dc.b $3
	dc.b $ED, $B, $0, $0, $FC
	dc.b $F5, $6, $0, $C, $EC
	dc.b $D, $9, $0, $12, $FC
DATA2ESUK69M67C_7F: dc.b $3
	dc.b $ED, $B, $0, $0, $FC
	dc.b $F5, $6, $0, $C, $EC
	dc.b $D, $C, $0, $12, $F4
DATA2ESUK69M67C_80: dc.b $4
	dc.b $EE, $F, $0, $0, $F4
	dc.b $F6, $1, $0, $10, $EC
	dc.b $E, $C, $0, $12, $F4
	dc.b $15, $0, $0, $16, $FC
DATA2ESUK69M67C_81: dc.b $4
	dc.b $EC, $B, $0, $0, $FB
	dc.b $F4, $6, $0, $C, $EB
	dc.b $F4, $0, $0, $12, $13
	dc.b $C, $D, $0, $13, $F2
DATA2ESUK69M67C_82: dc.b $3
	dc.b $6, $D, $0, $0, $EE
	dc.b $EE, $E, $0, $8, $F6
	dc.b $6, $1, $0, $14, $E
DATA2ESUK69M67C_83: dc.b $2
	dc.b $F5, $F, $0, $0, $F4
	dc.b $ED, $4, $0, $10, $FC
DATA2ESUK69M67C_84: dc.b $3
	dc.b $5, $D, $0, $0, $F0
	dc.b $ED, $A, $0, $8, $F8
	dc.b $F5, $2, $0, $11, $10
DATA2ESUK69M67C_85: dc.b $4
	dc.b $F0, $D, $0, $0, $F9
	dc.b $F8, $3, $0, $8, $F1
	dc.b $0, $1, $0, $C, $E9
	dc.b $0, $A, $0, $E, $F9
DATA2ESUK69M67C_86: dc.b $3
	dc.b $EE, $E, $0, $0, $F8
	dc.b $F6, $7, $0, $C, $E8
	dc.b $6, $9, $0, $14, $F8
DATA2ESUK69M67C_87: dc.b $4
	dc.b $EC, $B, $0, $0, $F9
	dc.b $F4, $7, $0, $C, $E9
	dc.b $F4, $1, $0, $14, $11
	dc.b $C, $9, $0, $16, $F9
DATA2ESUK69M67C_88: dc.b $4
	dc.b $EE, $E, $0, $0, $F6
	dc.b $F6, $7, $0, $C, $E6
	dc.b $6, $9, $0, $14, $F6
	dc.b $E, $0, $0, $1A, $E
DATA2ESUK69M67C_89: dc.b $4
	dc.b $EB, $B, $0, $0, $FA
	dc.b $F3, $6, $0, $C, $EA
	dc.b $F3, $0, $0, $12, $12
	dc.b $B, $9, $0, $13, $FA
DATA2ESUK69M67C_8A: dc.b $4
	dc.b $EC, $B, $0, $0, $F9
	dc.b $F4, $2, $0, $C, $11
	dc.b $4, $4, $0, $F, $E9
	dc.b $C, $C, $0, $11, $F1
DATA2ESUK69M67C_8B: dc.b $4
	dc.b $F1, $E, $0, $0, $EC
	dc.b $9, $5, $0, $C, $FC
	dc.b $19, $0, $0, $10, $FC
	dc.b $1, $0, $0, $11, $C
DATA2ESUK69M67C_8C: dc.b $3
	dc.b $EF, $A, $0, $0, $ED
	dc.b $F7, $3, $0, $9, $5
	dc.b $7, $6, $0, $D, $F5
DATA2ESUK69M67C_8D: dc.b $4
	dc.b $C, $D, $0, $0, $E2
	dc.b $EC, $B, $0, $8, $EA
	dc.b $1C, $0, $0, $14, $F2
	dc.b $F4, $7, $0, $15, $2
DATA2ESUK69M67C_8E: dc.b $5
	dc.b $EF, $F, $0, $0, $E9
	dc.b $FF, $1, $0, $10, $9
	dc.b $7, $0, $0, $12, $E1
	dc.b $F, $C, $0, $13, $E9
	dc.b $10, $0, $0, $17, $0
DATA2ESUK69M67C_8F: dc.b $4
	dc.b $EE, $F, $0, $0, $E9
	dc.b $FE, $1, $0, $10, $9
	dc.b $6, $0, $0, $12, $E1
	dc.b $E, $C, $0, $13, $E9
DATA2ESUK69M67C_90: dc.b $4
	dc.b $4, $D, $0, $0, $E3
	dc.b $EC, $A, $0, $8, $EB
	dc.b $F4, $3, $0, $11, $3
	dc.b $4, $0, $0, $15, $B
DATA2ESUK69M67C_91: dc.b $4
	dc.b $EE, $F, $0, $0, $E9
	dc.b $FE, $1, $0, $10, $9
	dc.b $6, $0, $0, $12, $E1
	dc.b $E, $C, $0, $13, $E9
DATA2ESUK69M67C_92: dc.b $4
	dc.b $EC, $B, $0, $0, $EA
	dc.b $F4, $7, $0, $C, $2
	dc.b $C, $2, $0, $14, $FA
	dc.b $14, $4, $0, $17, $EA
DATA2ESUK69M67C_93: dc.b $2
	dc.b $F3, $E, $0, $0, $EC
	dc.b $B, $9, $0, $C, $F4
DATA2ESUK69M67C_94: dc.b $4
	dc.b $F0, $A, $0, $0, $ED
	dc.b $F8, $3, $0, $9, $5
	dc.b $8, $6, $0, $D, $F5
	dc.b $8, $0, $0, $13, $D
DATA2ESUK69M67C_95: dc.b $4
	dc.b $EE, $F, $0, $0, $EA
	dc.b $E, $9, $0, $10, $EA
	dc.b $E, $0, $0, $16, $2
	dc.b $6, $0, $0, $17, $A
DATA2ESUK69M67C_96: dc.b $4
	dc.b $EE, $F, $0, $0, $E9
	dc.b $FE, $2, $0, $10, $9
	dc.b $6, $1, $0, $13, $E1
	dc.b $E, $D, $0, $15, $E9
DATA2ESUK69M67C_97: dc.b $5
	dc.b $0, $D, $0, $0, $E3
	dc.b $F0, $D, $0, $8, $EB
	dc.b $10, $C, $0, $10, $EB
	dc.b $18, $4, $0, $14, $F3
	dc.b $0, $5, $0, $16, $3
DATA2ESUK69M67C_98: dc.b $5
	dc.b $0, $E, $0, $0, $E3
	dc.b $F0, $9, $0, $C, $EB
	dc.b $18, $1, $0, $12, $F3
	dc.b $F8, $3, $0, $14, $3
	dc.b $0, $1, $0, $18, $B
DATA2ESUK69M67C_99: dc.b $5
	dc.b $5, $D, $0, $0, $E3
	dc.b $ED, $A, $0, $8, $EB
	dc.b $15, $0, $0, $11, $EB
	dc.b $F5, $3, $0, $12, $3
	dc.b $5, $0, $0, $16, $B
DATA2ESUK69M67C_9A: dc.b $5
	dc.b $F0, $E, $0, $0, $E9
	dc.b $10, $C, $0, $C, $E9
	dc.b $8, $C, $0, $10, $F1
	dc.b $18, $0, $0, $14, $F9
	dc.b $0, $4, $0, $15, $9
DATA2ESUK69M67C_9B: dc.b $3
	dc.b $EF, $F, $0, $0, $F7
	dc.b $F7, $1, $0, $10, $EF
	dc.b $F, $0, $0, $12, $F
DATA2ESUK69M67C_9C: dc.b $3
	dc.b $F0, $B, $0, $0, $F5
	dc.b $F8, $1, $0, $C, $ED
	dc.b $F8, $3, $0, $E, $D
DATA2ESUK69M67C_9D: dc.b $4
	dc.b $F6, $E, $0, $0, $EE
	dc.b $EE, $8, $0, $C, $F6
	dc.b $E, $9, $0, $F, $FE
	dc.b $F6, $2, $0, $15, $E
DATA2ESUK69M67C_9E: dc.b $3
	dc.b $F1, $E, $0, $0, $ED
	dc.b $9, $9, $0, $C, $F5
	dc.b $F1, $6, $0, $12, $D
DATA2ESUK69M67C_9F: dc.b $3
	dc.b $F1, $E, $0, $0, $ED
	dc.b $9, $9, $0, $C, $F5
	dc.b $F1, $3, $0, $12, $D
DATA2ESUK69M67C_A0: dc.b $4
	dc.b $F1, $F, $0, $0, $EE
	dc.b $11, $4, $0, $10, $F6
	dc.b $F1, $3, $0, $12, $E
	dc.b $1, $0, $0, $16, $16
DATA2ESUK69M67C_A1: dc.b $4
	dc.b $EF, $E, $0, $0, $F2
	dc.b $EF, $3, $0, $C, $12
	dc.b $F7, $1, $0, $10, $EA
	dc.b $7, $A, $0, $12, $F2
DATA2ESUK69M67C_A2: dc.b $3
	dc.b $F0, $F, $0, $0, $EE
	dc.b $10, $4, $0, $10, $6
	dc.b $F0, $3, $0, $12, $E
DATA2ESUK69M67C_A3: dc.b $2
	dc.b $F1, $F, $0, $0, $F5
	dc.b $F9, $1, $0, $10, $ED
DATA2ESUK69M67C_A4: dc.b $3
	dc.b $ED, $B, $0, $0, $EF
	dc.b $D, $D, $0, $C, $F7
	dc.b $F5, $6, $0, $14, $7
DATA2ESUK69M67C_A5: dc.b $4
	dc.b $EB, $7, $0, $0, $F1
	dc.b $F3, $A, $0, $8, $1
	dc.b $FB, $1, $0, $11, $E9
	dc.b $B, $9, $0, $13, $F1
DATA2ESUK69M67C_A6: dc.b $4
	dc.b $ED, $B, $0, $0, $EE
	dc.b $D, $D, $0, $C, $F6
	dc.b $F5, $6, $0, $14, $6
	dc.b $ED, $0, $0, $1A, $E
DATA2ESUK69M67C_A7: dc.b $4
	dc.b $F4, $E, $0, $0, $EC
	dc.b $EC, $4, $0, $C, $F4
	dc.b $C, $D, $0, $E, $F4
	dc.b $F4, $6, $0, $16, $C
DATA2ESUK69M67C_A8: dc.b $4
	dc.b $EC, $7, $0, $0, $F0
	dc.b $C, $C, $0, $8, $F8
	dc.b $F4, $A, $0, $C, $0
	dc.b $14, $4, $0, $15, $0
DATA2ESUK69M67C_A9: dc.b $3
	dc.b $F0, $F, $0, $0, $F1
	dc.b $10, $0, $0, $10, $9
	dc.b $F8, $2, $0, $11, $11
DATA2ESUK69M67C_AA: dc.b $3
	dc.b $F1, $F, $0, $0, $F4
	dc.b $F9, $1, $0, $10, $EC
	dc.b $11, $4, $0, $12, $4
DATA2ESUK69M67C_AB: dc.b $3
	dc.b $E8, $6, $0, $0, $0
	dc.b $F0, $B, $0, $6, $E8
	dc.b $0, $0, $0, $12, $0
DATA2ESUK69M67C_AC: dc.b $4
	dc.b $ED, $B, $0, $0, $ED
	dc.b $E5, $0, $0, $C, $FD
	dc.b $ED, $5, $0, $D, $5
	dc.b $F5, $0, $0, $11, $15
DATA2ESUK69M67C_AD: dc.b $3
	dc.b $F4, $A, $0, $0, $E9
	dc.b $EC, $C, $0, $9, $F1
	dc.b $F4, $9, $0, $D, $1
DATA2ESUK69M67C_AE: dc.b $4
	dc.b $F7, $E, $0, $0, $E6
	dc.b $E7, $D, $0, $C, $EE
	dc.b $F7, $7, $0, $14, $6
	dc.b $FF, $0, $0, $1C, $16
DATA2ESUK69M67C_AF: dc.b $4
	dc.b $F0, $F, $0, $0, $E7
	dc.b $E8, $4, $0, $10, $F7
	dc.b $10, $0, $0, $12, $FF
	dc.b $F0, $3, $0, $13, $7
DATA2ESUK69M67C_B0: dc.b $4
	dc.b $F0, $F, $0, $0, $E7
	dc.b $E8, $4, $0, $10, $F7
	dc.b $10, $0, $0, $12, $FF
	dc.b $F0, $3, $0, $13, $7
DATA2ESUK69M67C_B1: dc.b $4
	dc.b $E7, $7, $0, $0, $FD
	dc.b $EF, $7, $0, $8, $ED
	dc.b $F7, $2, $0, $10, $E5
	dc.b $7, $5, $0, $13, $FD
DATA2ESUK69M67C_B2: dc.b $5
	dc.b $F0, $F, $0, $0, $E8
	dc.b $E8, $4, $0, $10, $F8
	dc.b $10, $0, $0, $12, $0
	dc.b $F0, $3, $0, $13, $8
	dc.b $F8, $0, $0, $17, $10
DATA2ESUK69M67C_B3: dc.b $4
	dc.b $F7, $E, $0, $0, $E4
	dc.b $E7, $D, $0, $C, $EC
	dc.b $F7, $8, $0, $14, $4
	dc.b $FF, $1, $0, $17, $C
DATA2ESUK69M67C_B4: dc.b $3
	dc.b $EC, $E, $0, $0, $EB
	dc.b $4, $8, $0, $C, $EB
	dc.b $F4, $1, $0, $F, $B
DATA2ESUK69M67C_B5: dc.b $5
	dc.b $EE, $F, $0, $0, $E9
	dc.b $E6, $4, $0, $10, $F9
	dc.b $E, $0, $0, $12, $1
	dc.b $EE, $0, $0, $13, $9
	dc.b $FE, $1, $0, $14, $9
DATA2ESUK69M67C_B6: dc.b $4
	dc.b $F0, $F, $0, $0, $E7
	dc.b $E8, $8, $0, $10, $F7
	dc.b $10, $4, $0, $13, $FF
	dc.b $F0, $7, $0, $15, $7
DATA2ESUK69M67C_B7: dc.b $5
	dc.b $EE, $F, $0, $0, $E9
	dc.b $E6, $4, $0, $10, $F9
	dc.b $E, $4, $0, $12, $F9
	dc.b $EE, $3, $0, $14, $9
	dc.b $F6, $1, $0, $18, $11
DATA2ESUK69M67C_B8: dc.b $5
	dc.b $F3, $F, $0, $0, $E9
	dc.b $E3, $5, $0, $10, $F9
	dc.b $EB, $3, $0, $14, $9
	dc.b $B, $0, $0, $18, $9
	dc.b $FB, $4, $0, $19, $11
DATA2ESUK69M67C_B9: dc.b $4
	dc.b $EF, $F, $0, $0, $E7
	dc.b $E7, $0, $0, $10, $FF
	dc.b $EF, $3, $0, $11, $7
	dc.b $F7, $2, $0, $15, $F
DATA2ESUK69M67C_BA: dc.b $4
	dc.b $F4, $A, $0, $0, $E9
	dc.b $EC, $C, $0, $9, $F1
	dc.b $E4, $0, $0, $D, $1
	dc.b $F4, $9, $0, $E, $1
DATA2ESUK69M67C_BB: dc.b $4
	dc.b $F5, $E, $0, $0, $E6
	dc.b $ED, $C, $0, $C, $EE
	dc.b $E5, $4, $0, $10, $F6
	dc.b $F5, $6, $0, $12, $6
DATA2ESUK69M67C_BC: dc.b $4
	dc.b $E8, $F, $0, $0, $E8
	dc.b $8, $D, $0, $10, $F0
	dc.b $E8, $7, $0, $18, $8
	dc.b $8, $0, $0, $20, $10
DATA2ESUK69M67C_BD: dc.b $5
	dc.b $E8, $F, $0, $0, $E8
	dc.b $8, $D, $0, $10, $E8
	dc.b $E8, $3, $0, $18, $8
	dc.b $8, $4, $0, $1C, $8
	dc.b $F0, $2, $0, $1E, $10
DATA2ESUK69M67C_BE: dc.b $5
	dc.b $E8, $F, $0, $0, $F0
	dc.b $F0, $3, $0, $10, $E8
	dc.b $F8, $3, $0, $14, $10
	dc.b $8, $D, $0, $18, $F0
	dc.b $10, $0, $0, $20, $E8
DATA2ESUK69M67C_BF: dc.b $4
	dc.b $E8, $F, $0, $0, $F8
	dc.b $F0, $7, $0, $10, $E8
	dc.b $8, $D, $0, $18, $F8
	dc.b $10, $0, $0, $20, $F0
DATA2ESUK69M67C_C0: dc.b $5
	dc.b $EC, $E, $0, $0, $E4
	dc.b $4, $E, $0, $C, $EC
	dc.b $E4, $B, $0, $18, $4
	dc.b $4, $5, $0, $24, $C
	dc.b $14, $0, $0, $28, $C
DATA2ESUK69M67C_C1: dc.b $5
	dc.b $E4, $F, $0, $0, $E4
	dc.b $4, $A, $0, $10, $EC
	dc.b $E4, $7, $0, $19, $4
	dc.b $4, $9, $0, $21, $4
	dc.b $EC, $2, $0, $27, $14
DATA2ESUK69M67C_C2: dc.b $6
	dc.b $F4, $E, $0, $0, $E0
	dc.b $E4, $D, $0, $C, $E8
	dc.b $C, $9, $0, $14, $E8
	dc.b $F4, $B, $0, $1A, $0
	dc.b $E4, $5, $0, $26, $8
	dc.b $FC, $1, $0, $2A, $18
DATA2ESUK69M67C_C3: dc.b $5
	dc.b $E4, $B, $0, $0, $FC
	dc.b $EC, $B, $0, $C, $E4
	dc.b $4, $E, $0, $18, $FC
	dc.b $C, $8, $0, $24, $E4
	dc.b $14, $4, $0, $27, $EC
	even