; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu May 21 2020 15:45:54 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAY5VYWOSMC0N:
	dc.w $0, DATAY5VYWOSMC0N_1-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_2-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_3-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_4-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_5-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_6-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_7-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_8-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_9-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_10-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_11-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_12-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_13-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_14-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_15-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_16-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_17-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_18-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_19-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_1A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_1B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_1C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_1D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_1E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_1F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_20-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_21-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_22-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_23-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_24-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_25-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_26-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_27-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_28-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_29-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_2A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_2B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_2C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_2D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_2E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_2F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_30-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_31-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_32-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_33-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_34-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_35-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_36-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_37-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_38-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_39-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_3A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_3B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_3C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_3D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_3E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_3F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_40-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_41-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_42-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_43-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_44-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_45-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_46-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_47-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_48-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_49-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_4A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_4B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_4C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_4D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_4E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_4F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_50-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_51-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_52-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_53-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_54-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_55-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_56-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_57-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_58-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_59-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_5A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_5B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_5C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_5D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_5E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_5F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_60-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_61-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_62-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_63-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_64-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_65-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_66-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_67-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_68-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_69-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_6A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_6B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_6C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_6D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_6E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_6F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_70-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_71-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_72-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_73-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_74-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_75-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_76-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_77-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_78-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_79-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_7A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_7B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_7C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_7D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_7E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_7F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_80-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_81-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_82-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_83-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_84-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_85-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_86-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_87-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_88-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_89-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_8A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_8B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_8C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_8D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_8E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_8F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_90-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_91-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_92-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_93-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_94-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_95-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_96-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_97-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_98-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_99-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_9A-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_9B-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_9C-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_9D-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_9E-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_9F-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_A0-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_A1-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_A2-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_A3-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_A4-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_A5-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_A6-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_A7-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_A8-DATAY5VYWOSMC0N, DATAY5VYWOSMC0N_A9-DATAY5VYWOSMC0N
	dc.w DATAY5VYWOSMC0N_AA-DATAY5VYWOSMC0N
DATAY5VYWOSMC0N_1: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATAY5VYWOSMC0N_2: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F8
DATAY5VYWOSMC0N_3: dc.b $4
	dc.b $E7, $E, $0, $0, $F0
	dc.b $FF, $8, $0, $C, $F0
	dc.b $7, $5, $0, $F, $F8
	dc.b $F, $0, $0, $13, $8
DATAY5VYWOSMC0N_4: dc.b $4
	dc.b $E8, $7, $0, $0, $F9
	dc.b $F0, $2, $0, $8, $F1
	dc.b $F0, $1, $0, $B, $9
	dc.b $8, $9, $0, $D, $F9
DATAY5VYWOSMC0N_5: dc.b $4
	dc.b $E8, $7, $0, $0, $F9
	dc.b $F0, $2, $0, $8, $F1
	dc.b $F0, $1, $0, $B, $9
	dc.b $8, $9, $0, $D, $F9
DATAY5VYWOSMC0N_6: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATAY5VYWOSMC0N_7: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $8
	dc.b $C, $8, $0, $D, $F8
DATAY5VYWOSMC0N_8: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $8
	dc.b $C, $8, $0, $D, $F8
DATAY5VYWOSMC0N_9: dc.b $3
	dc.b $EC, $B, $0, $0, $F1
	dc.b $F4, $0, $0, $C, $9
	dc.b $C, $8, $0, $D, $F9
DATAY5VYWOSMC0N_A: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $F4, $0, $0, $9, $8
	dc.b $4, $5, $0, $A, $F8
	dc.b $C, $0, $0, $E, $8
DATAY5VYWOSMC0N_B: dc.b $4
	dc.b $EC, $A, $0, $0, $F1
	dc.b $F4, $0, $0, $9, $9
	dc.b $4, $5, $0, $A, $F9
	dc.b $C, $0, $0, $E, $9
DATAY5VYWOSMC0N_C: dc.b $3
	dc.b $ED, $B, $0, $0, $EF
	dc.b $F5, $3, $0, $C, $7
	dc.b $D, $4, $0, $10, $F7
DATAY5VYWOSMC0N_D: dc.b $3
	dc.b $ED, $E, $0, $0, $EC
	dc.b $FD, $2, $0, $C, $C
	dc.b $5, $9, $0, $F, $F4
DATAY5VYWOSMC0N_E: dc.b $4
	dc.b $E8, $B, $0, $0, $EF
	dc.b $F0, $0, $0, $C, $7
	dc.b $0, $2, $0, $D, $7
	dc.b $8, $5, $0, $10, $F7
DATAY5VYWOSMC0N_F: dc.b $3
	dc.b $EC, $B, $0, $0, $EE
	dc.b $FC, $2, $0, $C, $6
	dc.b $C, $4, $0, $F, $F6
DATAY5VYWOSMC0N_10: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F0
DATAY5VYWOSMC0N_11: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $F4, $3, $0, $E, $C
	dc.b $C, $4, $0, $12, $FC
DATAY5VYWOSMC0N_12: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $FC, $2, $0, $E, $C
	dc.b $C, $4, $0, $11, $FC
DATAY5VYWOSMC0N_13: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $FC, $2, $0, $E, $C
	dc.b $C, $4, $0, $11, $FC
DATAY5VYWOSMC0N_14: dc.b $3
	dc.b $EC, $E, $0, $0, $F2
	dc.b $F4, $3, $0, $C, $12
	dc.b $4, $9, $0, $10, $FA
DATAY5VYWOSMC0N_15: dc.b $3
	dc.b $EC, $F, $0, $0, $F0
	dc.b $FC, $1, $0, $10, $10
	dc.b $C, $8, $0, $12, $F8
DATAY5VYWOSMC0N_16: dc.b $3
	dc.b $EC, $E, $0, $0, $F0
	dc.b $F4, $3, $0, $C, $10
	dc.b $4, $9, $0, $10, $F8
DATAY5VYWOSMC0N_17: dc.b $3
	dc.b $EF, $B, $0, $0, $F7
	dc.b $F7, $3, $0, $C, $F
	dc.b $F, $8, $0, $10, $F7
DATAY5VYWOSMC0N_18: dc.b $2
	dc.b $F6, $B, $0, $0, $FF
	dc.b $FE, $2, $0, $C, $F7
DATAY5VYWOSMC0N_19: dc.b $2
	dc.b $F4, $E, $0, $0, $E4
	dc.b $F4, $A, $0, $C, $4
DATAY5VYWOSMC0N_1A: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATAY5VYWOSMC0N_1B: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $FC, $2, $0, $9, $8
	dc.b $4, $5, $0, $C, $F8
DATAY5VYWOSMC0N_1C: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATAY5VYWOSMC0N_1D: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATAY5VYWOSMC0N_1E: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F8
DATAY5VYWOSMC0N_1F: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAY5VYWOSMC0N_20: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATAY5VYWOSMC0N_21: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAY5VYWOSMC0N_22: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F0
DATAY5VYWOSMC0N_23: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F0
DATAY5VYWOSMC0N_24: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $9, $0, $C, $F0
DATAY5VYWOSMC0N_25: dc.b $3
	dc.b $EC, $A, $0, $0, $F8
	dc.b $FC, $2, $0, $9, $F0
	dc.b $4, $5, $0, $C, $F8
DATAY5VYWOSMC0N_26: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATAY5VYWOSMC0N_27: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATAY5VYWOSMC0N_28: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATAY5VYWOSMC0N_29: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATAY5VYWOSMC0N_2A: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATAY5VYWOSMC0N_2B: dc.b $3
	dc.b $F7, $A, $0, $0, $FA
	dc.b $FF, $2, $0, $9, $F2
	dc.b $F, $4, $0, $C, $FA
DATAY5VYWOSMC0N_2C: dc.b $1
	dc.b $F0, $F, $8, $0, $F0
DATAY5VYWOSMC0N_2D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY5VYWOSMC0N_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY5VYWOSMC0N_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY5VYWOSMC0N_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAY5VYWOSMC0N_31: dc.b $4
	dc.b $E4, $F, $0, $0, $F0
	dc.b $4, $6, $0, $10, $F8
	dc.b $C, $1, $0, $16, $8
	dc.b $14, $0, $0, $18, $F0
DATAY5VYWOSMC0N_32: dc.b $4
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
	dc.b $10, $0, $0, $12, $F0
	dc.b $10, $0, $0, $13, $8
DATAY5VYWOSMC0N_33: dc.b $2
	dc.b $7, $D, $0, $0, $EB
	dc.b $EF, $A, $0, $8, $F3
DATAY5VYWOSMC0N_34: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATAY5VYWOSMC0N_35: dc.b $2
	dc.b $7, $D, $0, $0, $EB
	dc.b $EF, $A, $0, $8, $F3
DATAY5VYWOSMC0N_36: dc.b $2
	dc.b $EF, $B, $0, $0, $F3
	dc.b $F, $4, $0, $C, $F3
DATAY5VYWOSMC0N_37: dc.b $5
	dc.b $E8, $E, $0, $0, $EC
	dc.b $E8, $2, $0, $C, $C
	dc.b $0, $8, $0, $F, $F4
	dc.b $8, $5, $0, $12, $EC
	dc.b $8, $5, $0, $16, $4
DATAY5VYWOSMC0N_38: dc.b $5
	dc.b $E8, $E, $0, $0, $EC
	dc.b $E8, $2, $0, $C, $C
	dc.b $0, $8, $0, $F, $F4
	dc.b $8, $5, $0, $12, $EC
	dc.b $8, $5, $0, $16, $4
DATAY5VYWOSMC0N_39: dc.b $6
	dc.b $EC, $D, $0, $0, $EC
	dc.b $EC, $1, $0, $8, $C
	dc.b $FC, $9, $0, $A, $F4
	dc.b $4, $1, $0, $10, $EC
	dc.b $C, $0, $0, $12, $F4
	dc.b $C, $4, $0, $13, $4
DATAY5VYWOSMC0N_3A: dc.b $5
	dc.b $E8, $B, $0, $0, $EE
	dc.b $E8, $1, $0, $C, $E
	dc.b $F0, $2, $0, $E, $6
	dc.b $8, $8, $0, $11, $EE
	dc.b $10, $4, $0, $14, $F6
DATAY5VYWOSMC0N_3B: dc.b $4
	dc.b $E8, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $0, $9, $0, $E, $F4
	dc.b $10, $4, $0, $14, $F4
DATAY5VYWOSMC0N_3C: dc.b $4
	dc.b $E8, $B, $0, $0, $F4
	dc.b $F0, $1, $0, $C, $EC
	dc.b $0, $1, $0, $E, $C
	dc.b $8, $5, $0, $10, $F4
DATAY5VYWOSMC0N_3D: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F0, $2, $0, $10, $C
DATAY5VYWOSMC0N_3E: dc.b $3
	dc.b $F0, $E, $0, $0, $EB
	dc.b $F0, $2, $0, $C, $B
	dc.b $8, $8, $0, $F, $F3
DATAY5VYWOSMC0N_3F: dc.b $4
	dc.b $E8, $B, $0, $0, $F0
	dc.b $F0, $3, $0, $C, $8
	dc.b $8, $9, $0, $10, $F0
	dc.b $10, $0, $0, $16, $8
DATAY5VYWOSMC0N_40: dc.b $3
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $8, $0, $C, $F8
	dc.b $8, $9, $0, $F, $F0
DATAY5VYWOSMC0N_41: dc.b $3
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $9, $0, $10, $F0
	dc.b $10, $0, $0, $16, $8
DATAY5VYWOSMC0N_42: dc.b $3
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $9, $0, $10, $F0
	dc.b $10, $0, $0, $16, $8
DATAY5VYWOSMC0N_43: dc.b $4
	dc.b $EC, $F, $0, $0, $EC
	dc.b $FC, $2, $0, $10, $C
	dc.b $C, $4, $0, $13, $EC
	dc.b $C, $0, $0, $15, $4
DATAY5VYWOSMC0N_44: dc.b $3
	dc.b $ED, $F, $0, $0, $EC
	dc.b $5, $1, $0, $10, $C
	dc.b $D, $C, $0, $12, $EC
DATAY5VYWOSMC0N_45: dc.b $2
	dc.b $ED, $E, $0, $0, $EF
	dc.b $5, $9, $0, $C, $EF
DATAY5VYWOSMC0N_46: dc.b $2
	dc.b $EC, $F, $0, $0, $EF
	dc.b $C, $C, $0, $10, $EF
DATAY5VYWOSMC0N_47: dc.b $4
	dc.b $EC, $F, $0, $0, $EC
	dc.b $FC, $1, $0, $10, $C
	dc.b $C, $4, $0, $12, $EC
	dc.b $C, $0, $0, $14, $4
DATAY5VYWOSMC0N_48: dc.b $4
	dc.b $ED, $F, $0, $0, $EC
	dc.b $5, $1, $0, $10, $C
	dc.b $D, $4, $0, $12, $EC
	dc.b $D, $0, $0, $14, $4
DATAY5VYWOSMC0N_49: dc.b $4
	dc.b $ED, $E, $0, $0, $EF
	dc.b $5, $5, $0, $C, $F7
	dc.b $D, $0, $0, $10, $EF
	dc.b $D, $0, $0, $11, $7
DATAY5VYWOSMC0N_4A: dc.b $2
	dc.b $EC, $F, $0, $0, $EE
	dc.b $C, $C, $0, $10, $EE
DATAY5VYWOSMC0N_4B: dc.b $5
	dc.b $ED, $E, $0, $0, $ED
	dc.b $ED, $2, $0, $C, $D
	dc.b $F5, $1, $0, $F, $E5
	dc.b $5, $8, $0, $11, $ED
	dc.b $D, $5, $0, $14, $F5
DATAY5VYWOSMC0N_4C: dc.b $7
	dc.b $EE, $7, $0, $0, $F0
	dc.b $F6, $1, $0, $8, $E8
	dc.b $F6, $3, $0, $A, $0
	dc.b $F6, $2, $0, $E, $10
	dc.b $FE, $1, $0, $11, $8
	dc.b $E, $1, $0, $13, $F8
	dc.b $16, $0, $0, $15, $0
DATAY5VYWOSMC0N_4D: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $8, $0, $10, $FA
DATAY5VYWOSMC0N_4E: dc.b $5
	dc.b $ED, $E, $0, $0, $E8
	dc.b $F5, $3, $0, $C, $8
	dc.b $FD, $1, $0, $10, $10
	dc.b $5, $8, $0, $12, $F0
	dc.b $D, $4, $0, $15, $F8
DATAY5VYWOSMC0N_4F: dc.b $4
	dc.b $EC, $F, $0, $0, $EA
	dc.b $F4, $2, $0, $10, $A
	dc.b $C, $4, $0, $13, $F2
	dc.b $14, $4, $0, $15, $FA
DATAY5VYWOSMC0N_50: dc.b $5
	dc.b $ED, $B, $0, $0, $F1
	dc.b $F5, $1, $0, $C, $E9
	dc.b $F5, $6, $0, $E, $9
	dc.b $D, $4, $0, $14, $F9
	dc.b $15, $0, $0, $16, $F9
DATAY5VYWOSMC0N_51: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $C, $0, $C, $F2
	dc.b $E, $4, $0, $10, $2
DATAY5VYWOSMC0N_52: dc.b $4
	dc.b $EF, $E, $0, $0, $E7
	dc.b $F7, $3, $0, $C, $7
	dc.b $FF, $1, $0, $10, $F
	dc.b $7, $5, $0, $12, $F7
DATAY5VYWOSMC0N_53: dc.b $4
	dc.b $EC, $A, $0, $0, $FD
	dc.b $F4, $7, $0, $9, $ED
	dc.b $4, $8, $0, $11, $FD
	dc.b $C, $4, $0, $14, $5
DATAY5VYWOSMC0N_54: dc.b $3
	dc.b $EC, $7, $0, $0, $5
	dc.b $F4, $B, $0, $8, $ED
	dc.b $C, $4, $0, $14, $5
DATAY5VYWOSMC0N_55: dc.b $2
	dc.b $F5, $E, $0, $0, $ED
	dc.b $F5, $2, $0, $C, $D
DATAY5VYWOSMC0N_56: dc.b $2
	dc.b $F1, $F, $0, $0, $ED
	dc.b $F1, $3, $0, $10, $D
DATAY5VYWOSMC0N_57: dc.b $3
	dc.b $EC, $B, $0, $0, $FD
	dc.b $F4, $7, $0, $C, $ED
	dc.b $C, $8, $0, $14, $FD
DATAY5VYWOSMC0N_58: dc.b $4
	dc.b $EC, $A, $0, $0, $FD
	dc.b $F4, $7, $0, $9, $ED
	dc.b $4, $8, $0, $11, $FD
	dc.b $C, $4, $0, $14, $5
DATAY5VYWOSMC0N_59: dc.b $3
	dc.b $F1, $E, $0, $0, $ED
	dc.b $F1, $2, $0, $C, $D
	dc.b $9, $8, $0, $F, $ED
DATAY5VYWOSMC0N_5A: dc.b $2
	dc.b $F2, $F, $0, $0, $EC
	dc.b $F2, $3, $0, $10, $C
DATAY5VYWOSMC0N_5B: dc.b $4
	dc.b $E4, $B, $0, $0, $E4
	dc.b $F4, $9, $0, $C, $FC
	dc.b $4, $C, $0, $12, $E4
	dc.b $C, $4, $0, $16, $EC
DATAY5VYWOSMC0N_5C: dc.b $6
	dc.b $E4, $8, $0, $0, $EC
	dc.b $EC, $7, $0, $3, $F4
	dc.b $F4, $3, $0, $B, $EC
	dc.b $F4, $5, $0, $F, $4
	dc.b $FC, $1, $0, $13, $E4
	dc.b $C, $0, $0, $15, $F4
DATAY5VYWOSMC0N_5D: dc.b $3
	dc.b $E8, $6, $0, $0, $0
	dc.b $F0, $B, $0, $6, $E8
	dc.b $0, $0, $0, $12, $0
DATAY5VYWOSMC0N_5E: dc.b $6
	dc.b $E4, $7, $0, $0, $F8
	dc.b $EC, $3, $0, $8, $F0
	dc.b $EC, $2, $0, $C, $8
	dc.b $F4, $3, $0, $F, $E8
	dc.b $4, $4, $0, $13, $F8
	dc.b $C, $4, $0, $15, $F0
DATAY5VYWOSMC0N_5F: dc.b $5
	dc.b $E8, $B, $0, $0, $EC
	dc.b $F0, $3, $0, $C, $E4
	dc.b $F0, $5, $0, $10, $4
	dc.b $0, $0, $0, $14, $4
	dc.b $8, $4, $0, $15, $EC
DATAY5VYWOSMC0N_60: dc.b $6
	dc.b $E4, $B, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $E4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
	dc.b $4, $8, $0, $12, $EC
	dc.b $C, $4, $0, $15, $EC
DATAY5VYWOSMC0N_61: dc.b $3
	dc.b $E8, $5, $0, $0, $0
	dc.b $F0, $B, $0, $4, $E8
	dc.b $F8, $1, $0, $10, $0
DATAY5VYWOSMC0N_62: dc.b $6
	dc.b $E4, $7, $0, $0, $F8
	dc.b $EC, $3, $0, $8, $F0
	dc.b $EC, $1, $0, $C, $8
	dc.b $F4, $2, $0, $E, $E8
	dc.b $4, $4, $0, $11, $F8
	dc.b $C, $4, $0, $13, $F0
DATAY5VYWOSMC0N_63: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F8
DATAY5VYWOSMC0N_64: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $4, $0, $10, $F8
DATAY5VYWOSMC0N_65: dc.b $3
	dc.b $F0, $7, $0, $0, $F8
	dc.b $F8, $1, $0, $8, $F0
	dc.b $F8, $2, $0, $A, $8
DATAY5VYWOSMC0N_66: dc.b $2
	dc.b $F0, $B, $0, $0, $F8
	dc.b $F8, $2, $0, $C, $F0
DATAY5VYWOSMC0N_67: dc.b $3
	dc.b $F0, $7, $0, $0, $F8
	dc.b $F8, $2, $0, $8, $F0
	dc.b $F8, $2, $0, $B, $8
DATAY5VYWOSMC0N_68: dc.b $3
	dc.b $EC, $7, $0, $0, $0
	dc.b $F4, $7, $0, $8, $F0
	dc.b $C, $4, $0, $10, $0
DATAY5VYWOSMC0N_69: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F0
DATAY5VYWOSMC0N_6A: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $4, $0, $C, $FC
DATAY5VYWOSMC0N_6B: dc.b $2
	dc.b $F0, $B, $0, $0, $F0
	dc.b $F8, $1, $0, $C, $8
DATAY5VYWOSMC0N_6C: dc.b $2
	dc.b $F0, $E, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
DATAY5VYWOSMC0N_6D: dc.b $3
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $8, $0, $C, $F8
	dc.b $C, $4, $0, $F, $F8
DATAY5VYWOSMC0N_6E: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $C, $0, $10, $F0
DATAY5VYWOSMC0N_6F: dc.b $3
	dc.b $EC, $F, $0, $0, $EF
	dc.b $C, $C, $0, $10, $EF
	dc.b $4, $0, $0, $14, $F
DATAY5VYWOSMC0N_70: dc.b $2
	dc.b $E8, $F, $0, $0, $F4
	dc.b $8, $D, $0, $10, $EC
DATAY5VYWOSMC0N_71: dc.b $4
	dc.b $E8, $F, $0, $0, $F1
	dc.b $F8, $1, $0, $10, $11
	dc.b $8, $D, $0, $12, $E1
	dc.b $8, $5, $0, $1A, $1
DATAY5VYWOSMC0N_72: dc.b $6
	dc.b $EA, $B, $0, $0, $F1
	dc.b $F2, $3, $0, $C, $9
	dc.b $FA, $1, $0, $10, $11
	dc.b $2, $6, $0, $12, $E1
	dc.b $A, $9, $0, $18, $F1
	dc.b $12, $4, $0, $1E, $9
DATAY5VYWOSMC0N_73: dc.b $5
	dc.b $EE, $F, $0, $0, $F1
	dc.b $F6, $1, $0, $10, $11
	dc.b $FE, $6, $0, $12, $E1
	dc.b $E, $C, $0, $18, $F1
	dc.b $E, $0, $0, $1C, $11
DATAY5VYWOSMC0N_74: dc.b $4
	dc.b $EE, $F, $0, $0, $F5
	dc.b $F6, $A, $0, $10, $DD
	dc.b $E, $C, $0, $19, $E5
	dc.b $E, $4, $0, $1D, $5
DATAY5VYWOSMC0N_75: dc.b $3
	dc.b $ED, $F, $0, $0, $F7
	dc.b $F5, $3, $0, $10, $EF
	dc.b $D, $C, $0, $14, $F7
DATAY5VYWOSMC0N_76: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $F0, $2, $0, $C, $C
	dc.b $8, $D, $0, $F, $EC
DATAY5VYWOSMC0N_77: dc.b $6
	dc.b $E8, $B, $0, $0, $F4
	dc.b $F0, $2, $0, $C, $C
	dc.b $0, $2, $0, $F, $EC
	dc.b $8, $1, $0, $12, $E4
	dc.b $8, $9, $0, $14, $F4
	dc.b $10, $0, $0, $1A, $C
DATAY5VYWOSMC0N_78: dc.b $5
	dc.b $E9, $B, $0, $0, $F4
	dc.b $F1, $3, $0, $C, $C
	dc.b $1, $6, $0, $10, $E4
	dc.b $9, $9, $0, $16, $F4
	dc.b $11, $0, $0, $1C, $C
DATAY5VYWOSMC0N_79: dc.b $3
	dc.b $EE, $F, $0, $0, $F2
	dc.b $F6, $7, $0, $10, $E2
	dc.b $E, $C, $0, $18, $F2
DATAY5VYWOSMC0N_7A: dc.b $4
	dc.b $EE, $F, $0, $0, $F5
	dc.b $F6, $A, $0, $10, $DD
	dc.b $E, $C, $0, $19, $E5
	dc.b $E, $4, $0, $1D, $5
DATAY5VYWOSMC0N_7B: dc.b $3
	dc.b $ED, $F, $0, $0, $F1
	dc.b $FD, $2, $0, $10, $E9
	dc.b $D, $C, $0, $13, $F1
DATAY5VYWOSMC0N_7C: dc.b $6
	dc.b $E4, $7, $0, $0, $F4
	dc.b $EC, $2, $0, $8, $EC
	dc.b $EC, $3, $0, $B, $4
	dc.b $4, $2, $0, $F, $FC
	dc.b $4, $1, $0, $12, $C
	dc.b $C, $1, $0, $14, $4
DATAY5VYWOSMC0N_7D: dc.b $7
	dc.b $E4, $E, $0, $0, $E8
	dc.b $E4, $3, $0, $C, $8
	dc.b $FC, $8, $0, $10, $F0
	dc.b $FC, $1, $0, $13, $10
	dc.b $4, $9, $0, $15, $F8
	dc.b $C, $1, $0, $1B, $F0
	dc.b $14, $0, $0, $1D, $F8
DATAY5VYWOSMC0N_7E: dc.b $6
	dc.b $E4, $F, $0, $0, $E8
	dc.b $E4, $3, $0, $10, $8
	dc.b $F4, $1, $0, $14, $10
	dc.b $4, $C, $0, $16, $E8
	dc.b $4, $0, $0, $1A, $8
	dc.b $C, $9, $0, $1B, $E8
DATAY5VYWOSMC0N_7F: dc.b $6
	dc.b $E4, $F, $0, $0, $E8
	dc.b $E4, $3, $0, $10, $8
	dc.b $F4, $1, $0, $14, $10
	dc.b $4, $D, $0, $16, $E8
	dc.b $4, $0, $0, $1E, $8
	dc.b $14, $0, $0, $1F, $F0
DATAY5VYWOSMC0N_80: dc.b $7
	dc.b $E8, $B, $0, $0, $F4
	dc.b $F0, $3, $0, $C, $EC
	dc.b $F0, $3, $0, $10, $C
	dc.b $F8, $1, $0, $14, $14
	dc.b $8, $1, $0, $16, $E4
	dc.b $8, $9, $0, $18, $F4
	dc.b $10, $0, $0, $1E, $EC
DATAY5VYWOSMC0N_81: dc.b $5
	dc.b $E8, $F, $0, $0, $EC
	dc.b $F0, $6, $0, $10, $C
	dc.b $8, $D, $0, $16, $EC
	dc.b $8, $0, $0, $1E, $C
	dc.b $10, $0, $0, $1F, $E4
DATAY5VYWOSMC0N_82: dc.b $5
	dc.b $E8, $A, $0, $0, $EC
	dc.b $F0, $7, $0, $9, $4
	dc.b $0, $4, $0, $11, $F4
	dc.b $8, $1, $0, $13, $FC
	dc.b $10, $0, $0, $15, $4
DATAY5VYWOSMC0N_83: dc.b $7
	dc.b $E4, $7, $0, $0, $F0
	dc.b $EC, $1, $0, $8, $E8
	dc.b $EC, $7, $0, $A, $0
	dc.b $FC, $1, $0, $12, $10
	dc.b $4, $2, $0, $14, $F8
	dc.b $C, $1, $0, $17, $F0
	dc.b $C, $4, $0, $19, $0
DATAY5VYWOSMC0N_84: dc.b $6
	dc.b $E4, $E, $0, $0, $E8
	dc.b $EC, $3, $0, $C, $8
	dc.b $F4, $1, $0, $10, $10
	dc.b $FC, $A, $0, $12, $F0
	dc.b $C, $0, $0, $1B, $E8
	dc.b $14, $4, $0, $1C, $F0
DATAY5VYWOSMC0N_85: dc.b $7
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $1, $0, $C, $E8
	dc.b $EC, $3, $0, $E, $8
	dc.b $FC, $0, $0, $12, $10
	dc.b $4, $D, $0, $13, $E8
	dc.b $C, $0, $0, $1B, $8
	dc.b $14, $0, $0, $1C, $F8
DATAY5VYWOSMC0N_86: dc.b $4
	dc.b $E8, $F, $0, $0, $EC
	dc.b $F8, $5, $0, $10, $C
	dc.b $8, $D, $0, $14, $E4
	dc.b $8, $4, $0, $1C, $4
DATAY5VYWOSMC0N_87: dc.b $6
	dc.b $E8, $A, $0, $0, $E8
	dc.b $F0, $7, $0, $9, $0
	dc.b $F8, $1, $0, $11, $10
	dc.b $0, $6, $0, $13, $F0
	dc.b $8, $1, $0, $19, $E8
	dc.b $10, $0, $0, $1B, $0
DATAY5VYWOSMC0N_88: dc.b $3
	dc.b $EC, $F, $0, $0, $EC
	dc.b $EC, $3, $0, $10, $C
	dc.b $C, $8, $0, $14, $FC
DATAY5VYWOSMC0N_89: dc.b $2
	dc.b $EA, $F, $0, $0, $E7
	dc.b $F2, $7, $0, $10, $7
DATAY5VYWOSMC0N_8A: dc.b $5
	dc.b $E5, $7, $0, $0, $F7
	dc.b $ED, $7, $0, $8, $E7
	dc.b $ED, $7, $0, $10, $7
	dc.b $5, $4, $0, $18, $F7
	dc.b $D, $5, $0, $1A, $7
DATAY5VYWOSMC0N_8B: dc.b $8
	dc.b $E4, $7, $0, $0, $FA
	dc.b $E4, $3, $0, $8, $12
	dc.b $EC, $3, $0, $C, $F2
	dc.b $EC, $3, $0, $10, $A
	dc.b $F4, $2, $0, $14, $EA
	dc.b $4, $4, $0, $17, $FA
	dc.b $4, $2, $0, $19, $12
	dc.b $C, $5, $0, $1C, $2
DATAY5VYWOSMC0N_8C: dc.b $7
	dc.b $E4, $7, $0, $0, $F5
	dc.b $E4, $3, $0, $8, $D
	dc.b $EC, $3, $0, $C, $ED
	dc.b $EC, $3, $0, $10, $5
	dc.b $4, $4, $0, $14, $F5
	dc.b $4, $2, $0, $16, $D
	dc.b $C, $5, $0, $19, $FD
DATAY5VYWOSMC0N_8D: dc.b $4
	dc.b $E8, $F, $0, $0, $ED
	dc.b $E8, $3, $0, $10, $D
	dc.b $8, $D, $0, $14, $F5
	dc.b $18, $8, $0, $1C, $F5
DATAY5VYWOSMC0N_8E: dc.b $4
	dc.b $E6, $3, $0, $0, $EC
	dc.b $E6, $B, $0, $4, $FC
	dc.b $EE, $3, $0, $10, $F4
	dc.b $6, $8, $0, $14, $FC
DATAY5VYWOSMC0N_8F: dc.b $3
	dc.b $E9, $B, $0, $0, $EF
	dc.b $F1, $2, $0, $C, $E7
	dc.b $F1, $7, $0, $F, $7
DATAY5VYWOSMC0N_90: dc.b $7
	dc.b $E9, $B, $0, $0, $EF
	dc.b $E9, $3, $0, $C, $F
	dc.b $F1, $2, $0, $10, $E7
	dc.b $F1, $3, $0, $13, $7
	dc.b $9, $0, $0, $17, $FF
	dc.b $9, $1, $0, $18, $F
	dc.b $11, $0, $0, $1A, $7
DATAY5VYWOSMC0N_91: dc.b $4
	dc.b $EA, $F, $0, $0, $F0
	dc.b $EA, $3, $0, $10, $10
	dc.b $F2, $2, $0, $14, $E8
	dc.b $A, $9, $0, $17, $0
DATAY5VYWOSMC0N_92: dc.b $3
	dc.b $EB, $F, $0, $0, $ED
	dc.b $EB, $3, $0, $10, $D
	dc.b $B, $D, $0, $14, $F5
DATAY5VYWOSMC0N_93: dc.b $6
	dc.b $E8, $B, $0, $0, $ED
	dc.b $E8, $3, $0, $C, $D
	dc.b $F0, $3, $0, $10, $5
	dc.b $8, $6, $0, $14, $F5
	dc.b $8, $1, $0, $1A, $D
	dc.b $10, $1, $0, $1C, $5
DATAY5VYWOSMC0N_94: dc.b $4
	dc.b $EC, $6, $0, $0, $4
	dc.b $F4, $B, $0, $6, $EC
	dc.b $F4, $1, $0, $12, $14
	dc.b $FC, $1, $0, $14, $E4
DATAY5VYWOSMC0N_95: dc.b $6
	dc.b $E6, $7, $0, $0, $FE
	dc.b $EE, $B, $0, $8, $E6
	dc.b $EE, $3, $0, $14, $E
	dc.b $FE, $1, $0, $18, $16
	dc.b $6, $0, $0, $1A, $FE
	dc.b $E, $8, $0, $1B, $E6
DATAY5VYWOSMC0N_96: dc.b $8
	dc.b $E3, $7, $0, $0, $F9
	dc.b $EB, $7, $0, $8, $E9
	dc.b $EB, $3, $0, $10, $9
	dc.b $F3, $3, $0, $14, $11
	dc.b $FB, $1, $0, $18, $19
	dc.b $3, $4, $0, $1A, $F9
	dc.b $B, $8, $0, $1C, $E9
	dc.b $B, $0, $0, $1F, $9
DATAY5VYWOSMC0N_97: dc.b $9
	dc.b $E4, $7, $0, $0, $F8
	dc.b $EC, $3, $0, $8, $F0
	dc.b $EC, $3, $0, $C, $8
	dc.b $F4, $2, $0, $10, $E8
	dc.b $F4, $3, $0, $13, $10
	dc.b $4, $5, $0, $17, $F8
	dc.b $C, $0, $0, $1B, $F0
	dc.b $C, $1, $0, $1C, $8
	dc.b $14, $0, $0, $1E, $10
DATAY5VYWOSMC0N_98: dc.b $8
	dc.b $E8, $7, $0, $0, $F4
	dc.b $F0, $7, $0, $8, $E4
	dc.b $F0, $3, $0, $10, $4
	dc.b $F8, $3, $0, $14, $C
	dc.b $8, $5, $0, $18, $F4
	dc.b $8, $0, $0, $1C, $14
	dc.b $10, $4, $0, $1D, $E4
	dc.b $10, $0, $0, $1F, $4
DATAY5VYWOSMC0N_99: dc.b $7
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $3, $0, $C, $8
	dc.b $F4, $3, $0, $10, $E8
	dc.b $F4, $3, $0, $14, $10
	dc.b $4, $9, $0, $18, $F0
	dc.b $C, $0, $0, $1E, $8
	dc.b $14, $0, $0, $1F, $10
DATAY5VYWOSMC0N_9A: dc.b $5
	dc.b $EC, $E, $0, $0, $F0
	dc.b $F4, $1, $0, $C, $10
	dc.b $FC, $2, $0, $E, $E8
	dc.b $4, $8, $0, $11, $F0
	dc.b $C, $4, $0, $14, $F0
DATAY5VYWOSMC0N_9B: dc.b $7
	dc.b $E8, $7, $0, $0, $FC
	dc.b $F0, $7, $0, $8, $EC
	dc.b $F0, $3, $0, $10, $C
	dc.b $F8, $2, $0, $14, $14
	dc.b $0, $1, $0, $17, $E4
	dc.b $8, $0, $0, $19, $FC
	dc.b $10, $4, $0, $1A, $EC
DATAY5VYWOSMC0N_9C: dc.b $8
	dc.b $E8, $3, $0, $0, $FC
	dc.b $F0, $7, $0, $4, $EC
	dc.b $F0, $7, $0, $C, $4
	dc.b $0, $1, $0, $14, $E4
	dc.b $0, $1, $0, $16, $14
	dc.b $8, $0, $0, $18, $FC
	dc.b $10, $4, $0, $19, $EC
	dc.b $10, $0, $0, $1B, $C
DATAY5VYWOSMC0N_9D: dc.b $8
	dc.b $E8, $3, $0, $0, $FC
	dc.b $F0, $7, $0, $4, $EC
	dc.b $F0, $7, $0, $C, $4
	dc.b $F8, $2, $0, $14, $E4
	dc.b $0, $0, $0, $17, $14
	dc.b $8, $0, $0, $18, $FC
	dc.b $10, $4, $0, $19, $EC
	dc.b $10, $4, $0, $1B, $4
DATAY5VYWOSMC0N_9E: dc.b $8
	dc.b $E8, $7, $0, $0, $F8
	dc.b $F0, $3, $0, $8, $F0
	dc.b $F0, $3, $0, $C, $8
	dc.b $F8, $3, $0, $10, $10
	dc.b $0, $2, $0, $14, $E8
	dc.b $8, $4, $0, $17, $F8
	dc.b $10, $4, $0, $19, $F0
	dc.b $10, $0, $0, $1B, $8
DATAY5VYWOSMC0N_9F: dc.b $6
	dc.b $E4, $7, $0, $0, $F8
	dc.b $EC, $3, $0, $8, $8
	dc.b $F4, $7, $0, $C, $E8
	dc.b $FC, $3, $0, $14, $10
	dc.b $4, $5, $0, $18, $F8
	dc.b $C, $1, $0, $1C, $8
DATAY5VYWOSMC0N_A0: dc.b $3
	dc.b $F5, $D, $0, $0, $E9
	dc.b $ED, $8, $0, $8, $F1
	dc.b $5, $6, $0, $B, $F9
DATAY5VYWOSMC0N_A1: dc.b $3
	dc.b $E9, $E, $0, $0, $F3
	dc.b $F9, $1, $0, $C, $EB
	dc.b $1, $A, $0, $E, $F3
DATAY5VYWOSMC0N_A2: dc.b $4
	dc.b $EA, $E, $0, $0, $F1
	dc.b $F2, $1, $0, $C, $E9
	dc.b $2, $6, $0, $E, $F9
	dc.b $12, $0, $0, $14, $9
DATAY5VYWOSMC0N_A3: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATAY5VYWOSMC0N_A4: dc.b $2
	dc.b $F4, $E, $8, $0, $F4
	dc.b $4, $0, $8, $C, $EC
DATAY5VYWOSMC0N_A5: dc.b $2
	dc.b $F4, $E, $8, $0, $F8
	dc.b $FC, $5, $8, $C, $E8
DATAY5VYWOSMC0N_A6: dc.b $2
	dc.b $F4, $E, $8, $0, $EC
	dc.b $4, $0, $8, $C, $C
DATAY5VYWOSMC0N_A7: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATAY5VYWOSMC0N_A8: dc.b $2
	dc.b $F4, $E, $0, $0, $F4
	dc.b $4, $0, $0, $C, $EC
DATAY5VYWOSMC0N_A9: dc.b $2
	dc.b $F4, $E, $0, $0, $E8
	dc.b $FC, $5, $0, $C, $8
DATAY5VYWOSMC0N_AA: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $4, $0, $0, $C, $C
	even