; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jun 29 2020 21:21:40 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAP3WZOLNFW6K:
	dc.w $0, DATAP3WZOLNFW6K_1-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_2-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_3-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_4-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_5-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_6-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_7-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_8-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_9-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_A-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_B-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_C-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_D-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_E-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_F-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_10-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_11-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_12-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_13-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_14-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_15-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_16-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_17-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_18-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_19-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_1A-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_1B-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_1C-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_1D-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_1E-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_1F-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_20-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_21-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_22-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_23-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_24-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_25-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_26-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_27-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_28-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_29-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_2A-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_2B-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_2C-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_2D-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_2E-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_2F-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_30-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_31-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_32-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_33-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_34-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_35-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_36-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_37-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_38-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_39-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_3A-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_3B-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_3C-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_3D-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_3E-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_3F-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_40-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_41-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_42-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_43-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_44-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_45-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_46-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_47-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_48-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_49-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_4A-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_4B-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_4C-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_4D-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_4E-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_4F-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_50-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_51-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_52-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_53-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_54-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_55-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_56-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_57-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_58-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_59-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_5A-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_5B-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_5C-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_5D-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_5E-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_5F-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_60-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_61-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_62-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_63-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_64-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_65-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_66-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_67-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_68-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_69-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_6A-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_6B-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_6C-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_6D-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_6E-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_6F-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_70-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_71-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_72-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_73-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_74-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_75-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_76-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_77-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_78-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_79-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_7A-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_7B-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_7C-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_7D-DATAP3WZOLNFW6K
	dc.w DATAP3WZOLNFW6K_7E-DATAP3WZOLNFW6K, DATAP3WZOLNFW6K_7F-DATAP3WZOLNFW6K
DATAP3WZOLNFW6K_1: dc.b $5
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $0, $0, $C, $8
	dc.b $F4, $2, $0, $D, $E8
	dc.b $4, $9, $0, $10, $F0
	dc.b $C, $0, $0, $16, $8
DATAP3WZOLNFW6K_2: dc.b $5
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $0, $0, $C, $8
	dc.b $F4, $2, $0, $D, $E8
	dc.b $4, $9, $0, $10, $F0
	dc.b $C, $0, $0, $16, $8
DATAP3WZOLNFW6K_3: dc.b $4
	dc.b $E4, $B, $0, $0, $F0
	dc.b $F4, $2, $0, $C, $E8
	dc.b $4, $9, $0, $F, $F0
	dc.b $C, $0, $0, $15, $8
DATAP3WZOLNFW6K_4: dc.b $4
	dc.b $E4, $B, $0, $0, $F0
	dc.b $F4, $2, $0, $C, $E8
	dc.b $4, $9, $0, $F, $F0
	dc.b $C, $0, $0, $15, $8
DATAP3WZOLNFW6K_5: dc.b $4
	dc.b $E4, $B, $0, $0, $F0
	dc.b $F4, $2, $0, $C, $E8
	dc.b $4, $9, $0, $F, $F0
	dc.b $C, $0, $0, $15, $8
DATAP3WZOLNFW6K_6: dc.b $4
	dc.b $E4, $B, $0, $0, $F0
	dc.b $F4, $2, $0, $C, $E8
	dc.b $4, $9, $0, $F, $F0
	dc.b $C, $0, $0, $15, $8
DATAP3WZOLNFW6K_7: dc.b $4
	dc.b $E4, $B, $0, $0, $F0
	dc.b $F4, $2, $0, $C, $E8
	dc.b $4, $9, $0, $F, $F0
	dc.b $C, $0, $0, $15, $8
DATAP3WZOLNFW6K_8: dc.b $5
	dc.b $E5, $B, $0, $0, $EF
	dc.b $F5, $2, $0, $C, $E7
	dc.b $FD, $2, $0, $F, $7
	dc.b $5, $8, $0, $12, $EF
	dc.b $D, $4, $0, $15, $F7
DATAP3WZOLNFW6K_9: dc.b $4
	dc.b $E5, $B, $0, $0, $F0
	dc.b $ED, $3, $0, $C, $E8
	dc.b $FD, $2, $0, $10, $8
	dc.b $5, $9, $0, $13, $F0
DATAP3WZOLNFW6K_A: dc.b $4
	dc.b $E4, $B, $0, $0, $F0
	dc.b $F4, $2, $0, $C, $E8
	dc.b $4, $9, $0, $F, $F0
	dc.b $C, $0, $0, $15, $8
DATAP3WZOLNFW6K_B: dc.b $4
	dc.b $E4, $B, $0, $0, $F0
	dc.b $F4, $2, $0, $C, $E8
	dc.b $4, $9, $0, $F, $F0
	dc.b $C, $0, $0, $15, $8
DATAP3WZOLNFW6K_C: dc.b $5
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $0, $0, $C, $E8
	dc.b $EC, $0, $0, $D, $8
	dc.b $FC, $1, $0, $E, $E8
	dc.b $4, $9, $0, $10, $F0
DATAP3WZOLNFW6K_D: dc.b $3
	dc.b $E4, $B, $0, $0, $EC
	dc.b $F4, $1, $0, $C, $4
	dc.b $4, $9, $0, $E, $EC
DATAP3WZOLNFW6K_E: dc.b $3
	dc.b $E4, $B, $0, $0, $EC
	dc.b $F4, $1, $0, $C, $4
	dc.b $4, $9, $0, $E, $EC
DATAP3WZOLNFW6K_F: dc.b $4
	dc.b $E4, $7, $0, $0, $EC
	dc.b $EC, $3, $0, $8, $FC
	dc.b $F4, $1, $0, $C, $4
	dc.b $4, $5, $0, $E, $EC
DATAP3WZOLNFW6K_10: dc.b $5
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $0, $0, $C, $E8
	dc.b $F4, $2, $0, $D, $8
	dc.b $4, $9, $0, $10, $F0
	dc.b $C, $0, $0, $16, $E8
DATAP3WZOLNFW6K_11: dc.b $5
	dc.b $E4, $7, $0, $0, $F4
	dc.b $EC, $3, $0, $8, $EC
	dc.b $EC, $3, $0, $C, $4
	dc.b $4, $5, $0, $10, $F4
	dc.b $C, $0, $0, $14, $EC
DATAP3WZOLNFW6K_12: dc.b $5
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $0, $0, $C, $E8
	dc.b $EC, $0, $0, $D, $8
	dc.b $FC, $1, $0, $E, $E8
	dc.b $4, $9, $0, $10, $F0
DATAP3WZOLNFW6K_13: dc.b $5
	dc.b $E4, $7, $0, $0, $F4
	dc.b $EC, $3, $0, $8, $EC
	dc.b $EC, $3, $0, $C, $4
	dc.b $4, $5, $0, $10, $F4
	dc.b $C, $0, $0, $14, $4
DATAP3WZOLNFW6K_14: dc.b $5
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $0, $0, $C, $8
	dc.b $F4, $2, $0, $D, $E8
	dc.b $4, $9, $0, $10, $F0
	dc.b $C, $0, $0, $16, $8
DATAP3WZOLNFW6K_15: dc.b $3
	dc.b $E4, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $4, $9, $0, $E, $F4
DATAP3WZOLNFW6K_16: dc.b $3
	dc.b $E4, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $4, $9, $0, $E, $F4
DATAP3WZOLNFW6K_17: dc.b $3
	dc.b $E4, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $EC
	dc.b $4, $9, $0, $E, $F4
DATAP3WZOLNFW6K_18: dc.b $5
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $0, $0, $C, $E8
	dc.b $EC, $0, $0, $D, $8
	dc.b $FC, $1, $0, $E, $E8
	dc.b $4, $9, $0, $10, $F0
DATAP3WZOLNFW6K_19: dc.b $3
	dc.b $E1, $B, $0, $0, $F1
	dc.b $F1, $2, $0, $C, $E9
	dc.b $1, $E, $0, $F, $F1
DATAP3WZOLNFW6K_1A: dc.b $4
	dc.b $E1, $B, $0, $0, $F2
	dc.b $E9, $3, $0, $C, $EA
	dc.b $1, $A, $0, $10, $F2
	dc.b $9, $1, $0, $19, $EA
DATAP3WZOLNFW6K_1B: dc.b $4
	dc.b $E1, $B, $0, $0, $F2
	dc.b $F1, $2, $0, $C, $EA
	dc.b $1, $6, $0, $F, $F2
	dc.b $9, $1, $0, $15, $2
DATAP3WZOLNFW6K_1C: dc.b $4
	dc.b $E1, $B, $0, $0, $F2
	dc.b $F1, $3, $0, $C, $EA
	dc.b $1, $A, $0, $10, $F2
	dc.b $11, $0, $0, $19, $EA
DATAP3WZOLNFW6K_1D: dc.b $3
	dc.b $E1, $B, $0, $0, $F1
	dc.b $F1, $2, $0, $C, $E9
	dc.b $1, $E, $0, $F, $F1
DATAP3WZOLNFW6K_1E: dc.b $4
	dc.b $E1, $B, $0, $0, $F2
	dc.b $F1, $3, $0, $C, $EA
	dc.b $1, $A, $0, $10, $F2
	dc.b $11, $0, $0, $19, $EA
DATAP3WZOLNFW6K_1F: dc.b $4
	dc.b $E1, $B, $0, $0, $F3
	dc.b $E9, $3, $0, $C, $EB
	dc.b $1, $6, $0, $10, $F3
	dc.b $9, $1, $0, $16, $3
DATAP3WZOLNFW6K_20: dc.b $4
	dc.b $E1, $B, $0, $0, $F2
	dc.b $E9, $3, $0, $C, $EA
	dc.b $1, $A, $0, $10, $F2
	dc.b $9, $1, $0, $19, $EA
DATAP3WZOLNFW6K_21: dc.b $6
	dc.b $E8, $A, $0, $0, $E7
	dc.b $F0, $3, $0, $9, $FF
	dc.b $F8, $6, $0, $D, $7
	dc.b $0, $5, $0, $13, $EF
	dc.b $10, $0, $0, $17, $EF
	dc.b $10, $4, $0, $18, $FF
DATAP3WZOLNFW6K_22: dc.b $6
	dc.b $E9, $A, $0, $0, $E7
	dc.b $F1, $3, $0, $9, $FF
	dc.b $F9, $2, $0, $D, $7
	dc.b $1, $5, $0, $10, $EF
	dc.b $1, $1, $0, $14, $F
	dc.b $11, $4, $0, $16, $F7
DATAP3WZOLNFW6K_23: dc.b $5
	dc.b $EB, $A, $0, $0, $E9
	dc.b $F3, $3, $0, $9, $1
	dc.b $3, $4, $0, $D, $F1
	dc.b $3, $5, $0, $F, $9
	dc.b $B, $0, $0, $13, $F1
DATAP3WZOLNFW6K_24: dc.b $6
	dc.b $E9, $A, $0, $0, $E8
	dc.b $F1, $3, $0, $9, $0
	dc.b $F9, $3, $0, $D, $8
	dc.b $1, $5, $0, $11, $F0
	dc.b $1, $1, $0, $15, $10
	dc.b $11, $0, $0, $17, $0
DATAP3WZOLNFW6K_25: dc.b $5
	dc.b $E9, $A, $0, $0, $E8
	dc.b $F1, $3, $0, $9, $0
	dc.b $F9, $6, $0, $D, $8
	dc.b $1, $5, $0, $13, $F0
	dc.b $11, $4, $0, $17, $0
DATAP3WZOLNFW6K_26: dc.b $6
	dc.b $EA, $A, $0, $0, $E8
	dc.b $F2, $3, $0, $9, $0
	dc.b $FA, $2, $0, $D, $8
	dc.b $2, $5, $0, $10, $F0
	dc.b $2, $1, $0, $14, $10
	dc.b $12, $4, $0, $16, $F8
DATAP3WZOLNFW6K_27: dc.b $6
	dc.b $E7, $B, $0, $0, $E7
	dc.b $EF, $3, $0, $C, $FF
	dc.b $FF, $6, $0, $10, $7
	dc.b $7, $4, $0, $16, $EF
	dc.b $F, $0, $0, $18, $EF
	dc.b $F, $0, $0, $19, $FF
DATAP3WZOLNFW6K_28: dc.b $7
	dc.b $E9, $A, $0, $0, $E7
	dc.b $F1, $3, $0, $9, $FF
	dc.b $F9, $3, $0, $D, $7
	dc.b $1, $5, $0, $11, $EF
	dc.b $1, $1, $0, $15, $F
	dc.b $11, $0, $0, $17, $EF
	dc.b $11, $0, $0, $18, $FF
DATAP3WZOLNFW6K_29: dc.b $6
	dc.b $ED, $7, $0, $0, $E8
	dc.b $ED, $B, $0, $8, $0
	dc.b $F5, $2, $0, $14, $E0
	dc.b $F5, $3, $0, $17, $F8
	dc.b $D, $0, $0, $1B, $F0
	dc.b $D, $0, $0, $1C, $0
DATAP3WZOLNFW6K_2A: dc.b $3
	dc.b $F4, $E, $0, $0, $E0
	dc.b $F4, $B, $0, $C, $0
	dc.b $C, $4, $0, $18, $F0
DATAP3WZOLNFW6K_2B: dc.b $3
	dc.b $F4, $E, $0, $0, $E0
	dc.b $F4, $A, $0, $C, $0
	dc.b $C, $8, $0, $15, $F0
DATAP3WZOLNFW6K_2C: dc.b $3
	dc.b $F4, $E, $0, $0, $E0
	dc.b $F4, $B, $0, $C, $0
	dc.b $C, $4, $0, $18, $F0
DATAP3WZOLNFW6K_2D: dc.b $4
	dc.b $ED, $B, $0, $0, $0
	dc.b $F5, $D, $0, $C, $E0
	dc.b $5, $8, $0, $14, $E8
	dc.b $D, $8, $0, $17, $F0
DATAP3WZOLNFW6K_2E: dc.b $3
	dc.b $F4, $E, $0, $0, $E0
	dc.b $F4, $B, $0, $C, $0
	dc.b $C, $4, $0, $18, $F0
DATAP3WZOLNFW6K_2F: dc.b $4
	dc.b $F3, $E, $0, $0, $E0
	dc.b $F3, $6, $0, $C, $8
	dc.b $FB, $2, $0, $12, $0
	dc.b $B, $8, $0, $15, $E8
DATAP3WZOLNFW6K_30: dc.b $3
	dc.b $F4, $E, $0, $0, $E0
	dc.b $F4, $A, $0, $C, $0
	dc.b $C, $8, $0, $15, $F0
DATAP3WZOLNFW6K_31: dc.b $6
	dc.b $E8, $B, $0, $0, $F8
	dc.b $F0, $1, $0, $C, $10
	dc.b $F8, $3, $0, $E, $F0
	dc.b $0, $2, $0, $12, $E8
	dc.b $8, $C, $0, $15, $F8
	dc.b $10, $0, $0, $19, $F8
DATAP3WZOLNFW6K_32: dc.b $7
	dc.b $E9, $7, $0, $0, $0
	dc.b $F1, $3, $0, $8, $F8
	dc.b $F1, $3, $0, $C, $10
	dc.b $F9, $3, $0, $10, $F0
	dc.b $1, $2, $0, $14, $E8
	dc.b $9, $4, $0, $17, $0
	dc.b $11, $0, $0, $19, $F8
DATAP3WZOLNFW6K_33: dc.b $4
	dc.b $E7, $7, $0, $0, $2
	dc.b $F7, $7, $0, $8, $F2
	dc.b $FF, $2, $0, $10, $EA
	dc.b $7, $4, $0, $13, $2
DATAP3WZOLNFW6K_34: dc.b $7
	dc.b $E8, $7, $0, $0, $1
	dc.b $F0, $3, $0, $8, $F9
	dc.b $F0, $1, $0, $C, $11
	dc.b $F8, $3, $0, $E, $F1
	dc.b $0, $2, $0, $12, $E9
	dc.b $8, $4, $0, $15, $1
	dc.b $10, $0, $0, $17, $F9
DATAP3WZOLNFW6K_35: dc.b $6
	dc.b $E7, $B, $0, $0, $F8
	dc.b $EF, $1, $0, $C, $10
	dc.b $F7, $3, $0, $E, $F0
	dc.b $FF, $2, $0, $12, $E8
	dc.b $7, $8, $0, $15, $F8
	dc.b $F, $0, $0, $18, $F8
DATAP3WZOLNFW6K_36: dc.b $7
	dc.b $E8, $7, $0, $0, $1
	dc.b $F0, $3, $0, $8, $F9
	dc.b $F8, $3, $0, $C, $F1
	dc.b $F8, $1, $0, $10, $11
	dc.b $0, $2, $0, $12, $E9
	dc.b $8, $4, $0, $15, $1
	dc.b $10, $0, $0, $17, $F9
DATAP3WZOLNFW6K_37: dc.b $4
	dc.b $E8, $B, $0, $0, $FE
	dc.b $F8, $7, $0, $C, $EE
	dc.b $0, $2, $0, $14, $E6
	dc.b $8, $8, $0, $17, $FE
DATAP3WZOLNFW6K_38: dc.b $7
	dc.b $E9, $7, $0, $0, $0
	dc.b $F1, $3, $0, $8, $F8
	dc.b $F1, $1, $0, $C, $10
	dc.b $F9, $3, $0, $E, $F0
	dc.b $1, $2, $0, $12, $E8
	dc.b $9, $8, $0, $15, $0
	dc.b $11, $0, $0, $18, $F8
DATAP3WZOLNFW6K_39: dc.b $5
	dc.b $E5, $B, $0, $0, $F8
	dc.b $ED, $3, $0, $C, $F0
	dc.b $F5, $1, $0, $10, $E8
	dc.b $5, $9, $0, $12, $F8
	dc.b $D, $0, $0, $18, $F0
DATAP3WZOLNFW6K_3A: dc.b $5
	dc.b $E6, $B, $0, $0, $F4
	dc.b $EE, $3, $0, $C, $EC
	dc.b $EE, $2, $0, $10, $C
	dc.b $6, $9, $0, $13, $F4
	dc.b $E, $0, $0, $19, $C
DATAP3WZOLNFW6K_3B: dc.b $6
	dc.b $E6, $B, $0, $0, $F4
	dc.b $EE, $3, $0, $C, $EC
	dc.b $EE, $2, $0, $10, $C
	dc.b $6, $9, $0, $13, $F4
	dc.b $E, $0, $0, $19, $EC
	dc.b $E, $0, $0, $1A, $C
DATAP3WZOLNFW6K_3C: dc.b $6
	dc.b $E5, $B, $0, $0, $F1
	dc.b $ED, $3, $0, $C, $9
	dc.b $F5, $1, $0, $10, $11
	dc.b $FD, $2, $0, $12, $E9
	dc.b $5, $9, $0, $15, $F1
	dc.b $D, $0, $0, $1B, $9
DATAP3WZOLNFW6K_3D: dc.b $7
	dc.b $E5, $B, $0, $0, $F3
	dc.b $ED, $0, $0, $C, $EB
	dc.b $ED, $2, $0, $D, $B
	dc.b $F5, $1, $0, $10, $13
	dc.b $FD, $2, $0, $12, $EB
	dc.b $5, $9, $0, $15, $F3
	dc.b $D, $0, $0, $1B, $B
DATAP3WZOLNFW6K_3E: dc.b $7
	dc.b $E5, $B, $0, $0, $F3
	dc.b $ED, $0, $0, $C, $EB
	dc.b $ED, $2, $0, $D, $B
	dc.b $F5, $1, $0, $10, $13
	dc.b $FD, $2, $0, $12, $EB
	dc.b $5, $9, $0, $15, $F3
	dc.b $D, $0, $0, $1B, $B
DATAP3WZOLNFW6K_3F: dc.b $4
	dc.b $E5, $B, $0, $0, $EF
	dc.b $F5, $2, $0, $C, $E7
	dc.b $FD, $2, $0, $F, $7
	dc.b $5, $9, $0, $12, $EF
DATAP3WZOLNFW6K_40: dc.b $5
	dc.b $E5, $B, $0, $0, $F0
	dc.b $ED, $3, $0, $C, $E8
	dc.b $FD, $0, $0, $10, $8
	dc.b $5, $9, $0, $11, $F0
	dc.b $D, $0, $0, $17, $8
DATAP3WZOLNFW6K_41: dc.b $6
	dc.b $E5, $B, $0, $0, $F1
	dc.b $ED, $3, $0, $C, $E9
	dc.b $F5, $1, $0, $10, $9
	dc.b $5, $9, $0, $12, $F1
	dc.b $D, $0, $0, $18, $E9
	dc.b $D, $0, $0, $19, $9
DATAP3WZOLNFW6K_42: dc.b $4
	dc.b $DD, $F, $0, $0, $F0
	dc.b $ED, $2, $0, $10, $E8
	dc.b $FD, $D, $0, $13, $F0
	dc.b $D, $8, $0, $1B, $F8
DATAP3WZOLNFW6K_43: dc.b $3
	dc.b $DD, $F, $0, $0, $F0
	dc.b $ED, $2, $0, $10, $E8
	dc.b $FD, $E, $0, $13, $F0
DATAP3WZOLNFW6K_44: dc.b $4
	dc.b $E5, $B, $0, $0, $EC
	dc.b $ED, $3, $0, $C, $4
	dc.b $5, $8, $0, $10, $EC
	dc.b $D, $8, $0, $13, $F4
DATAP3WZOLNFW6K_45: dc.b $3
	dc.b $EC, $B, $0, $0, $ED
	dc.b $F4, $3, $0, $C, $5
	dc.b $C, $8, $0, $10, $ED
DATAP3WZOLNFW6K_46: dc.b $5
	dc.b $E5, $B, $0, $0, $EC
	dc.b $ED, $0, $0, $C, $4
	dc.b $FD, $1, $0, $D, $4
	dc.b $5, $8, $0, $F, $EC
	dc.b $D, $4, $0, $12, $F4
DATAP3WZOLNFW6K_47: dc.b $5
	dc.b $DE, $B, $0, $0, $F1
	dc.b $EE, $2, $0, $C, $E9
	dc.b $FE, $9, $0, $F, $F9
	dc.b $6, $0, $0, $15, $F1
	dc.b $E, $0, $0, $16, $F9
DATAP3WZOLNFW6K_48: dc.b $7
	dc.b $DC, $B, $0, $0, $F1
	dc.b $E4, $0, $0, $C, $9
	dc.b $EC, $2, $0, $D, $E9
	dc.b $FC, $5, $0, $10, $F9
	dc.b $4, $0, $0, $14, $F1
	dc.b $4, $0, $0, $15, $9
	dc.b $C, $0, $0, $16, $F9
DATAP3WZOLNFW6K_49: dc.b $5
	dc.b $DA, $B, $0, $0, $F7
	dc.b $E2, $2, $0, $C, $EF
	dc.b $EA, $1, $0, $F, $E7
	dc.b $FA, $6, $0, $11, $F7
	dc.b $2, $1, $0, $17, $7
DATAP3WZOLNFW6K_4A: dc.b $5
	dc.b $DA, $B, $0, $0, $F7
	dc.b $E2, $2, $0, $C, $EF
	dc.b $EA, $1, $0, $F, $E7
	dc.b $FA, $6, $0, $11, $F7
	dc.b $2, $1, $0, $17, $7
DATAP3WZOLNFW6K_4B: dc.b $8
	dc.b $EC, $D, $0, $0, $E4
	dc.b $C, $C, $0, $8, $E4
	dc.b $E4, $C, $0, $C, $EC
	dc.b $FC, $9, $0, $10, $EC
	dc.b $DC, $4, $0, $16, $F4
	dc.b $EC, $2, $0, $18, $4
	dc.b $C, $0, $0, $1B, $4
	dc.b $F4, $1, $0, $1C, $C
DATAP3WZOLNFW6K_4C: dc.b $9
	dc.b $F4, $C, $0, $0, $DC
	dc.b $C, $C, $0, $4, $E4
	dc.b $E4, $9, $0, $8, $EC
	dc.b $FC, $9, $0, $E, $EC
	dc.b $DC, $0, $0, $14, $F4
	dc.b $F4, $8, $0, $15, $FC
	dc.b $EC, $0, $0, $18, $4
	dc.b $FC, $4, $0, $19, $4
	dc.b $C, $0, $0, $1B, $4
DATAP3WZOLNFW6K_4D: dc.b $6
	dc.b $E9, $B, $0, $0, $F0
	dc.b $F1, $3, $0, $C, $E8
	dc.b $F1, $1, $0, $10, $8
	dc.b $9, $C, $0, $12, $F0
	dc.b $11, $4, $0, $16, $E8
	dc.b $11, $4, $0, $18, $0
DATAP3WZOLNFW6K_4E: dc.b $3
	dc.b $EC, $F, $0, $0, $E8
	dc.b $EC, $2, $0, $10, $8
	dc.b $C, $C, $0, $13, $E8
DATAP3WZOLNFW6K_4F: dc.b $3
	dc.b $EC, $F, $0, $0, $E8
	dc.b $EC, $2, $0, $10, $8
	dc.b $C, $C, $0, $13, $E8
DATAP3WZOLNFW6K_50: dc.b $8
	dc.b $E4, $B, $0, $0, $F0
	dc.b $EC, $3, $0, $C, $E8
	dc.b $EC, $2, $0, $10, $8
	dc.b $4, $9, $0, $13, $F0
	dc.b $C, $1, $0, $19, $E8
	dc.b $C, $1, $0, $1B, $8
	dc.b $14, $0, $0, $1D, $F0
	dc.b $14, $0, $0, $1E, $0
DATAP3WZOLNFW6K_51: dc.b $3
	dc.b $EC, $B, $0, $0, $F8
	dc.b $F4, $3, $0, $C, $F0
	dc.b $C, $8, $0, $10, $F8
DATAP3WZOLNFW6K_52: dc.b $4
	dc.b $E8, $B, $0, $0, $F4
	dc.b $F0, $2, $0, $C, $C
	dc.b $F8, $2, $0, $F, $EC
	dc.b $8, $9, $0, $12, $F4
DATAP3WZOLNFW6K_53: dc.b $4
	dc.b $E4, $B, $0, $0, $F8
	dc.b $EC, $3, $0, $C, $F0
	dc.b $4, $A, $0, $10, $F8
	dc.b $C, $1, $0, $19, $F0
DATAP3WZOLNFW6K_54: dc.b $3
	dc.b $ED, $F, $0, $0, $E9
	dc.b $E5, $8, $0, $10, $F1
	dc.b $D, $C, $0, $13, $F1
DATAP3WZOLNFW6K_55: dc.b $5
	dc.b $F4, $D, $0, $0, $E5
	dc.b $EC, $C, $0, $8, $ED
	dc.b $4, $D, $0, $C, $ED
	dc.b $E4, $8, $0, $14, $F5
	dc.b $F4, $1, $0, $17, $5
DATAP3WZOLNFW6K_56: dc.b $3
	dc.b $F9, $F, $0, $0, $E9
	dc.b $E1, $A, $0, $10, $F1
	dc.b $F9, $3, $0, $19, $9
DATAP3WZOLNFW6K_57: dc.b $2
	dc.b $F6, $F, $0, $0, $EC
	dc.b $E6, $9, $0, $10, $F4
DATAP3WZOLNFW6K_58: dc.b $4
	dc.b $EC, $B, $0, $0, $F8
	dc.b $F4, $3, $0, $C, $F0
	dc.b $FC, $2, $0, $10, $E8
	dc.b $C, $0, $0, $13, $F8
DATAP3WZOLNFW6K_59: dc.b $3
	dc.b $EC, $B, $0, $0, $F7
	dc.b $FC, $6, $0, $C, $E7
	dc.b $C, $0, $0, $12, $F7
DATAP3WZOLNFW6K_5A: dc.b $3
	dc.b $E8, $E, $0, $0, $F0
	dc.b $8, $9, $0, $C, $F0
	dc.b $0, $8, $0, $12, $F8
DATAP3WZOLNFW6K_5B: dc.b $4
	dc.b $E7, $B, $0, $0, $F7
	dc.b $EF, $0, $0, $C, $EF
	dc.b $7, $9, $0, $D, $EF
	dc.b $17, $0, $0, $13, $F7
DATAP3WZOLNFW6K_5C: dc.b $3
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $9, $0, $C, $FC
	dc.b $FC, $0, $0, $12, $C
DATAP3WZOLNFW6K_5D: dc.b $3
	dc.b $EC, $E, $0, $0, $ED
	dc.b $4, $9, $0, $C, $FD
	dc.b $FC, $0, $0, $12, $D
DATAP3WZOLNFW6K_5E: dc.b $3
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $8, $0, $C, $E8
	dc.b $F8, $6, $0, $F, $8
DATAP3WZOLNFW6K_5F: dc.b $4
	dc.b $F1, $E, $0, $0, $E7
	dc.b $9, $0, $0, $C, $EF
	dc.b $F9, $6, $0, $D, $7
	dc.b $0, $0, $0, $13, $14
DATAP3WZOLNFW6K_60: dc.b $4
	dc.b $E0, $B, $0, $0, $F1
	dc.b $E8, $3, $0, $C, $E9
	dc.b $F0, $1, $0, $10, $9
	dc.b $0, $A, $0, $12, $F1
DATAP3WZOLNFW6K_61: dc.b $5
	dc.b $E0, $B, $0, $0, $F1
	dc.b $E8, $3, $0, $C, $E9
	dc.b $F0, $1, $0, $10, $9
	dc.b $0, $A, $0, $12, $F1
	dc.b $8, $1, $0, $1B, $E9
DATAP3WZOLNFW6K_62: dc.b $8
	dc.b $E0, $B, $0, $0, $F1
	dc.b $E8, $3, $0, $C, $E9
	dc.b $F0, $1, $0, $10, $9
	dc.b $0, $9, $0, $12, $F1
	dc.b $8, $1, $0, $18, $E9
	dc.b $8, $1, $0, $1A, $9
	dc.b $10, $0, $0, $1C, $F1
	dc.b $10, $0, $0, $1D, $1
DATAP3WZOLNFW6K_63: dc.b $5
	dc.b $E0, $B, $0, $0, $F1
	dc.b $E8, $3, $0, $C, $E9
	dc.b $F0, $1, $0, $10, $9
	dc.b $0, $A, $0, $12, $F1
	dc.b $8, $1, $0, $1B, $E9
DATAP3WZOLNFW6K_64: dc.b $4
	dc.b $E0, $B, $0, $0, $F1
	dc.b $E8, $3, $0, $C, $E9
	dc.b $F0, $1, $0, $10, $9
	dc.b $0, $A, $0, $12, $F1
DATAP3WZOLNFW6K_65: dc.b $5
	dc.b $E0, $B, $0, $0, $F1
	dc.b $E8, $3, $0, $C, $E9
	dc.b $F0, $1, $0, $10, $9
	dc.b $0, $A, $0, $12, $F1
	dc.b $8, $1, $0, $1B, $E9
DATAP3WZOLNFW6K_66: dc.b $8
	dc.b $E0, $B, $0, $0, $F1
	dc.b $E8, $3, $0, $C, $E9
	dc.b $F0, $1, $0, $10, $9
	dc.b $0, $9, $0, $12, $F1
	dc.b $8, $1, $0, $18, $E9
	dc.b $8, $1, $0, $1A, $9
	dc.b $10, $0, $0, $1C, $F1
	dc.b $10, $0, $0, $1D, $1
DATAP3WZOLNFW6K_67: dc.b $5
	dc.b $E0, $B, $0, $0, $F1
	dc.b $E8, $3, $0, $C, $E9
	dc.b $F0, $1, $0, $10, $9
	dc.b $0, $A, $0, $12, $F1
	dc.b $8, $1, $0, $1B, $E9
DATAP3WZOLNFW6K_68: dc.b $4
	dc.b $E6, $E, $0, $0, $E6
	dc.b $FE, $E, $0, $C, $EE
	dc.b $E6, $2, $0, $18, $6
	dc.b $FE, $2, $0, $1B, $E
DATAP3WZOLNFW6K_69: dc.b $4
	dc.b $E5, $A, $0, $0, $E6
	dc.b $FD, $E, $0, $9, $EE
	dc.b $ED, $5, $0, $15, $FE
	dc.b $FD, $2, $0, $19, $E
DATAP3WZOLNFW6K_6A: dc.b $4
	dc.b $E5, $A, $0, $0, $E9
	dc.b $FD, $E, $0, $9, $F1
	dc.b $ED, $5, $0, $15, $1
	dc.b $F5, $2, $0, $19, $11
DATAP3WZOLNFW6K_6B: dc.b $4
	dc.b $E5, $A, $0, $0, $E9
	dc.b $FD, $E, $0, $9, $F1
	dc.b $ED, $5, $0, $15, $1
	dc.b $F5, $2, $0, $19, $11
DATAP3WZOLNFW6K_6C: dc.b $5
	dc.b $E8, $F, $0, $0, $ED
	dc.b $F0, $1, $0, $10, $E5
	dc.b $0, $1, $0, $12, $D
	dc.b $8, $C, $0, $14, $ED
	dc.b $10, $4, $0, $18, $FD
DATAP3WZOLNFW6K_6D: dc.b $4
	dc.b $E4, $B, $0, $0, $E6
	dc.b $4, $D, $0, $C, $EE
	dc.b $EC, $6, $0, $14, $FE
	dc.b $FC, $2, $0, $1A, $E
DATAP3WZOLNFW6K_6E: dc.b $5
	dc.b $E9, $E, $0, $0, $E8
	dc.b $E1, $0, $0, $C, $F0
	dc.b $1, $D, $0, $D, $F0
	dc.b $E9, $2, $0, $15, $8
	dc.b $1, $1, $0, $18, $10
DATAP3WZOLNFW6K_6F: dc.b $5
	dc.b $E8, $E, $0, $0, $E8
	dc.b $0, $D, $0, $C, $F0
	dc.b $10, $4, $0, $14, $0
	dc.b $E8, $2, $0, $16, $8
	dc.b $0, $1, $0, $19, $10
DATAP3WZOLNFW6K_70: dc.b $4
	dc.b $EC, $7, $0, $0, $F6
	dc.b $F4, $A, $0, $8, $DE
	dc.b $F4, $7, $0, $11, $6
	dc.b $C, $8, $0, $19, $EE
DATAP3WZOLNFW6K_71: dc.b $4
	dc.b $F5, $E, $0, $0, $E3
	dc.b $E5, $5, $0, $C, $F3
	dc.b $D, $8, $0, $10, $F3
	dc.b $F5, $A, $0, $13, $3
DATAP3WZOLNFW6K_72: dc.b $3
	dc.b $EC, $F, $0, $0, $F6
	dc.b $F4, $A, $0, $10, $DE
	dc.b $C, $8, $0, $19, $EE
DATAP3WZOLNFW6K_73: dc.b $4
	dc.b $E5, $7, $0, $0, $F3
	dc.b $F5, $6, $0, $8, $E3
	dc.b $F5, $9, $0, $E, $3
	dc.b $5, $D, $0, $14, $F3
DATAP3WZOLNFW6K_74: dc.b $4
	dc.b $F4, $E, $0, $0, $DE
	dc.b $C, $8, $0, $C, $EE
	dc.b $EC, $4, $0, $F, $F6
	dc.b $F4, $A, $0, $11, $FE
DATAP3WZOLNFW6K_75: dc.b $3
	dc.b $EC, $F, $0, $0, $F6
	dc.b $F4, $A, $0, $10, $DE
	dc.b $C, $8, $0, $19, $EE
DATAP3WZOLNFW6K_76: dc.b $4
	dc.b $E5, $7, $0, $0, $F3
	dc.b $F5, $6, $0, $8, $E3
	dc.b $F5, $9, $0, $E, $3
	dc.b $5, $D, $0, $14, $F3
DATAP3WZOLNFW6K_77: dc.b $4
	dc.b $F4, $E, $0, $0, $DF
	dc.b $C, $8, $0, $C, $EF
	dc.b $EC, $4, $0, $F, $F7
	dc.b $F4, $A, $0, $11, $FF
DATAP3WZOLNFW6K_78: dc.b $4
	dc.b $EE, $F, $0, $0, $E6
	dc.b $E, $8, $0, $10, $E6
	dc.b $E6, $8, $0, $13, $F6
	dc.b $EE, $7, $0, $16, $6
DATAP3WZOLNFW6K_79: dc.b $4
	dc.b $E9, $B, $0, $0, $FE
	dc.b $F1, $B, $0, $C, $E6
	dc.b $9, $4, $0, $18, $FE
	dc.b $11, $8, $0, $1A, $E6
DATAP3WZOLNFW6K_7A: dc.b $4
	dc.b $E9, $B, $0, $0, $FE
	dc.b $F1, $B, $0, $C, $E6
	dc.b $9, $4, $0, $18, $FE
	dc.b $11, $4, $0, $1A, $EE
DATAP3WZOLNFW6K_7B: dc.b $5
	dc.b $E2, $7, $0, $0, $1
	dc.b $F2, $B, $0, $8, $E9
	dc.b $2, $5, $0, $14, $1
	dc.b $A, $0, $0, $18, $E1
	dc.b $12, $0, $0, $19, $F1
DATAP3WZOLNFW6K_7C: dc.b $5
	dc.b $E8, $7, $0, $0, $2
	dc.b $F0, $B, $0, $8, $EA
	dc.b $8, $0, $0, $14, $E2
	dc.b $8, $4, $0, $15, $2
	dc.b $10, $8, $0, $17, $EA
DATAP3WZOLNFW6K_7D: dc.b $4
	dc.b $F1, $F, $0, $0, $E6
	dc.b $11, $8, $0, $10, $E6
	dc.b $E9, $8, $0, $13, $FE
	dc.b $F1, $7, $0, $16, $6
DATAP3WZOLNFW6K_7E: dc.b $4
	dc.b $F1, $F, $0, $0, $E6
	dc.b $11, $8, $0, $10, $E6
	dc.b $E9, $8, $0, $13, $FE
	dc.b $F1, $7, $0, $16, $6
DATAP3WZOLNFW6K_7F: dc.b $5
	dc.b $F0, $F, $0, $0, $E8
	dc.b $10, $8, $0, $10, $E8
	dc.b $E8, $8, $0, $13, $F8
	dc.b $F0, $5, $0, $16, $8
	dc.b $0, $1, $0, $1A, $8
	even