; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Jun 23 2020 17:21:29 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAJLQUCGWKHSJ:
	dc.w $0, DATAJLQUCGWKHSJ_1-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_2-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_3-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_4-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_5-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_6-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_7-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_8-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_9-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_10-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_11-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_12-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_13-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_14-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_15-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_16-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_17-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_18-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_19-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_1A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_1B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_1C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_1D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_1E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_1F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_20-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_21-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_22-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_23-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_24-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_25-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_26-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_27-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_28-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_29-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_2A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_2B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_2C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_2D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_2E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_2F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_30-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_31-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_32-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_33-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_34-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_35-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_36-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_37-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_38-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_39-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_3A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_3B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_3C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_3D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_3E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_3F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_40-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_41-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_42-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_43-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_44-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_45-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_46-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_47-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_48-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_49-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_4A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_4B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_4C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_4D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_4E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_4F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_50-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_51-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_52-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_53-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_54-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_55-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_56-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_57-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_58-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_59-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_5A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_5B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_5C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_5D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_5E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_5F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_60-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_61-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_62-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_63-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_64-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_65-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_66-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_67-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_68-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_69-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_6A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_6B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_6C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_6D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_6E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_6F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_70-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_71-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_72-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_73-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_74-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_75-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_76-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_77-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_78-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_79-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_7A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_7B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_7C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_7D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_7E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_7F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_80-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_81-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_82-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_83-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_84-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_85-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_86-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_87-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_88-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_89-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_8A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_8B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_8C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_8D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_8E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_8F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_90-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_91-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_92-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_93-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_94-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_95-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_96-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_97-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_98-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_99-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_9A-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_9B-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_9C-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_9D-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_9E-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_9F-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_A0-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_A1-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_A2-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_A3-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_A4-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_A5-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_A6-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_A7-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_A8-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_A9-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_AA-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_AB-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_AC-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_AD-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_AE-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_AF-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_B0-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_B1-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_B2-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_B3-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_B4-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_B5-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_B6-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_B7-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_B8-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_B9-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_BA-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_BB-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_BC-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_BD-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_BE-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_BF-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_C0-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_C1-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_C2-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_C3-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_C4-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_C5-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_C6-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_C7-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_C8-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_C9-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_CA-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_CB-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_CC-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_CD-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_CE-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_CF-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_D0-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_D1-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_D2-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_D3-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_D4-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_D5-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_D6-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_D7-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_D8-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_D9-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_DA-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_DB-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_DC-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_DD-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_DE-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_DF-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_E0-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_E1-DATAJLQUCGWKHSJ
	dc.w DATAJLQUCGWKHSJ_E2-DATAJLQUCGWKHSJ, DATAJLQUCGWKHSJ_E3-DATAJLQUCGWKHSJ
DATAJLQUCGWKHSJ_1: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $6, $0, $8, $4
	dc.b $FC, $A, $0, $E, $EC
DATAJLQUCGWKHSJ_2: dc.b $3
	dc.b $FD, $E, $0, $0, $EC
	dc.b $5, $1, $0, $C, $C
	dc.b $ED, $D, $0, $E, $EC
DATAJLQUCGWKHSJ_3: dc.b $3
	dc.b $FE, $A, $0, $0, $F4
	dc.b $F6, $C, $0, $9, $EC
	dc.b $EE, $8, $0, $D, $F4
DATAJLQUCGWKHSJ_4: dc.b $2
	dc.b $FC, $E, $0, $0, $EE
	dc.b $EC, $9, $0, $C, $F4
DATAJLQUCGWKHSJ_5: dc.b $3
	dc.b $FC, $E, $0, $0, $EE
	dc.b $FC, $1, $0, $C, $E
	dc.b $EC, $9, $0, $E, $F4
DATAJLQUCGWKHSJ_6: dc.b $3
	dc.b $FD, $E, $0, $0, $ED
	dc.b $5, $1, $0, $C, $D
	dc.b $ED, $9, $0, $E, $F4
DATAJLQUCGWKHSJ_7: dc.b $3
	dc.b $FE, $A, $0, $0, $F4
	dc.b $F6, $C, $0, $9, $EC
	dc.b $EE, $8, $0, $D, $F4
DATAJLQUCGWKHSJ_8: dc.b $2
	dc.b $FC, $A, $0, $0, $F4
	dc.b $EC, $D, $0, $9, $EC
DATAJLQUCGWKHSJ_9: dc.b $4
	dc.b $FD, $B, $0, $0, $FB
	dc.b $ED, $D, $0, $C, $EB
	dc.b $F5, $0, $0, $14, $B
	dc.b $FD, $5, $0, $15, $EB
DATAJLQUCGWKHSJ_A: dc.b $4
	dc.b $2, $E, $0, $0, $FC
	dc.b $F2, $D, $0, $C, $EC
	dc.b $FA, $4, $0, $14, $C
	dc.b $2, $4, $0, $16, $EC
DATAJLQUCGWKHSJ_B: dc.b $4
	dc.b $FB, $A, $0, $0, $FD
	dc.b $EB, $4, $0, $9, $F5
	dc.b $F3, $C, $0, $B, $ED
	dc.b $FB, $5, $0, $F, $ED
DATAJLQUCGWKHSJ_C: dc.b $4
	dc.b $FD, $E, $0, $0, $FC
	dc.b $ED, $D, $0, $C, $EC
	dc.b $FD, $4, $0, $14, $EC
	dc.b $5, $0, $0, $16, $F4
DATAJLQUCGWKHSJ_D: dc.b $4
	dc.b $FE, $B, $0, $0, $FC
	dc.b $EE, $D, $0, $C, $EC
	dc.b $EE, $1, $0, $14, $C
	dc.b $FE, $6, $0, $16, $EC
DATAJLQUCGWKHSJ_E: dc.b $4
	dc.b $FC, $F, $0, $0, $FB
	dc.b $EC, $9, $0, $10, $EB
	dc.b $F4, $8, $0, $16, $3
	dc.b $FC, $5, $0, $19, $EB
DATAJLQUCGWKHSJ_F: dc.b $4
	dc.b $FF, $A, $0, $0, $FA
	dc.b $EF, $D, $0, $9, $EA
	dc.b $FF, $4, $0, $11, $EA
	dc.b $7, $0, $0, $13, $F2
DATAJLQUCGWKHSJ_10: dc.b $4
	dc.b $FE, $A, $0, $0, $FC
	dc.b $EE, $8, $0, $9, $EC
	dc.b $F6, $C, $0, $C, $EC
	dc.b $FE, $5, $0, $10, $EC
DATAJLQUCGWKHSJ_11: dc.b $3
	dc.b $ED, $9, $0, $0, $FC
	dc.b $FD, $A, $0, $6, $FC
	dc.b $F5, $7, $0, $F, $EC
DATAJLQUCGWKHSJ_12: dc.b $3
	dc.b $F5, $B, $0, $0, $FC
	dc.b $ED, $4, $0, $C, $4
	dc.b $F5, $7, $0, $E, $EC
DATAJLQUCGWKHSJ_13: dc.b $3
	dc.b $F5, $A, $0, $0, $FC
	dc.b $F5, $6, $0, $9, $EC
	dc.b $D, $0, $0, $F, $F4
DATAJLQUCGWKHSJ_14: dc.b $2
	dc.b $F3, $B, $0, $0, $FC
	dc.b $F3, $7, $0, $C, $EC
DATAJLQUCGWKHSJ_15: dc.b $3
	dc.b $EB, $4, $0, $0, $FC
	dc.b $F3, $B, $0, $2, $FC
	dc.b $F3, $7, $0, $E, $EC
DATAJLQUCGWKHSJ_16: dc.b $4
	dc.b $EC, $4, $0, $0, $4
	dc.b $F4, $B, $0, $2, $FC
	dc.b $F4, $6, $0, $E, $EC
	dc.b $C, $0, $0, $14, $F4
DATAJLQUCGWKHSJ_17: dc.b $3
	dc.b $F5, $A, $0, $0, $FC
	dc.b $F5, $6, $0, $9, $EC
	dc.b $D, $0, $0, $F, $F4
DATAJLQUCGWKHSJ_18: dc.b $2
	dc.b $F5, $A, $0, $0, $FC
	dc.b $F5, $7, $0, $9, $EC
DATAJLQUCGWKHSJ_19: dc.b $4
	dc.b $EF, $E, $0, $0, $FE
	dc.b $EF, $6, $0, $C, $EE
	dc.b $7, $C, $0, $12, $EE
	dc.b $F, $8, $0, $16, $EE
DATAJLQUCGWKHSJ_1A: dc.b $4
	dc.b $E7, $B, $0, $0, $0
	dc.b $E7, $1, $0, $C, $F8
	dc.b $F7, $5, $0, $E, $F0
	dc.b $7, $9, $0, $12, $F0
DATAJLQUCGWKHSJ_1B: dc.b $4
	dc.b $EF, $A, $0, $0, $FD
	dc.b $F7, $5, $0, $9, $ED
	dc.b $7, $C, $0, $D, $ED
	dc.b $F, $4, $0, $11, $F5
DATAJLQUCGWKHSJ_1C: dc.b $4
	dc.b $E7, $B, $0, $0, $0
	dc.b $F7, $5, $0, $C, $F0
	dc.b $7, $C, $0, $10, $F0
	dc.b $F, $8, $0, $14, $F0
DATAJLQUCGWKHSJ_1D: dc.b $4
	dc.b $EE, $E, $0, $0, $FF
	dc.b $EE, $6, $0, $C, $EF
	dc.b $6, $D, $0, $12, $EF
	dc.b $6, $0, $0, $1A, $F
DATAJLQUCGWKHSJ_1E: dc.b $4
	dc.b $E8, $F, $0, $0, $FF
	dc.b $E8, $2, $0, $10, $F7
	dc.b $0, $4, $0, $13, $EF
	dc.b $8, $D, $0, $15, $EF
DATAJLQUCGWKHSJ_1F: dc.b $4
	dc.b $EE, $A, $0, $0, $FE
	dc.b $F6, $5, $0, $9, $EE
	dc.b $6, $C, $0, $D, $EE
	dc.b $E, $8, $0, $11, $EE
DATAJLQUCGWKHSJ_20: dc.b $4
	dc.b $EE, $A, $0, $0, $FE
	dc.b $F6, $5, $0, $9, $EE
	dc.b $6, $C, $0, $D, $EE
	dc.b $E, $8, $0, $11, $EE
DATAJLQUCGWKHSJ_21: dc.b $2
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
DATAJLQUCGWKHSJ_22: dc.b $2
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
DATAJLQUCGWKHSJ_23: dc.b $2
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
DATAJLQUCGWKHSJ_24: dc.b $2
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
DATAJLQUCGWKHSJ_25: dc.b $4
	dc.b $EF, $E, $0, $0, $ED
	dc.b $FF, $0, $0, $C, $D
	dc.b $7, $C, $0, $D, $F5
	dc.b $F, $8, $0, $11, $F5
DATAJLQUCGWKHSJ_26: dc.b $2
	dc.b $EE, $8, $0, $0, $F0
	dc.b $F6, $F, $0, $3, $F0
DATAJLQUCGWKHSJ_27: dc.b $4
	dc.b $EF, $E, $0, $0, $ED
	dc.b $FF, $0, $0, $C, $D
	dc.b $7, $C, $0, $D, $F5
	dc.b $F, $8, $0, $11, $F5
DATAJLQUCGWKHSJ_28: dc.b $2
	dc.b $EE, $8, $0, $0, $F0
	dc.b $F6, $F, $0, $3, $F0
DATAJLQUCGWKHSJ_29: dc.b $2
	dc.b $F0, $2, $0, $0, $EC
	dc.b $F0, $F, $0, $3, $F4
DATAJLQUCGWKHSJ_2A: dc.b $2
	dc.b $F0, $2, $0, $0, $EC
	dc.b $F0, $F, $0, $3, $F4
DATAJLQUCGWKHSJ_2B: dc.b $2
	dc.b $F0, $2, $0, $0, $EC
	dc.b $F0, $F, $0, $3, $F4
DATAJLQUCGWKHSJ_2C: dc.b $2
	dc.b $F0, $2, $0, $0, $EC
	dc.b $F0, $F, $0, $3, $F4
DATAJLQUCGWKHSJ_2D: dc.b $3
	dc.b $EA, $4, $0, $0, $FE
	dc.b $F2, $B, $0, $2, $EE
	dc.b $F2, $6, $0, $E, $6
DATAJLQUCGWKHSJ_2E: dc.b $2
	dc.b $F7, $2, $0, $0, $ED
	dc.b $EF, $F, $0, $3, $F5
DATAJLQUCGWKHSJ_2F: dc.b $3
	dc.b $EA, $4, $0, $0, $FE
	dc.b $F2, $B, $0, $2, $EE
	dc.b $F2, $6, $0, $E, $6
DATAJLQUCGWKHSJ_30: dc.b $2
	dc.b $F7, $2, $0, $0, $ED
	dc.b $EF, $F, $0, $3, $F5
DATAJLQUCGWKHSJ_31: dc.b $3
	dc.b $EC, $8, $0, $0, $F2
	dc.b $F4, $E, $0, $3, $F2
	dc.b $C, $8, $0, $F, $F2
DATAJLQUCGWKHSJ_32: dc.b $4
	dc.b $EA, $9, $0, $0, $F3
	dc.b $FA, $C, $0, $6, $F3
	dc.b $2, $8, $0, $A, $F3
	dc.b $A, $4, $0, $D, $FB
DATAJLQUCGWKHSJ_33: dc.b $4
	dc.b $F0, $4, $0, $0, $F9
	dc.b $F8, $8, $0, $2, $F1
	dc.b $0, $C, $0, $5, $F1
	dc.b $8, $4, $0, $9, $F9
DATAJLQUCGWKHSJ_34: dc.b $4
	dc.b $EF, $8, $0, $0, $F9
	dc.b $F7, $C, $0, $3, $F1
	dc.b $FF, $8, $0, $7, $F1
	dc.b $7, $C, $0, $A, $F1
DATAJLQUCGWKHSJ_35: dc.b $4
	dc.b $EF, $4, $0, $0, $F4
	dc.b $F7, $8, $0, $2, $F4
	dc.b $FF, $C, $0, $5, $F4
	dc.b $7, $8, $0, $9, $F4
DATAJLQUCGWKHSJ_36: dc.b $3
	dc.b $EA, $4, $0, $0, $F9
	dc.b $F2, $D, $0, $2, $F1
	dc.b $2, $9, $0, $A, $F1
DATAJLQUCGWKHSJ_37: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F0
DATAJLQUCGWKHSJ_38: dc.b $2
	dc.b $EE, $B, $0, $0, $F4
	dc.b $E, $0, $0, $C, $FC
DATAJLQUCGWKHSJ_39: dc.b $3
	dc.b $EE, $4, $0, $0, $F0
	dc.b $F6, $D, $0, $2, $F0
	dc.b $6, $8, $0, $A, $F0
DATAJLQUCGWKHSJ_3A: dc.b $4
	dc.b $F0, $8, $0, $0, $F5
	dc.b $F8, $C, $0, $3, $ED
	dc.b $0, $8, $0, $7, $F5
	dc.b $8, $4, $0, $A, $F5
DATAJLQUCGWKHSJ_3B: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $FC
DATAJLQUCGWKHSJ_3C: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAJLQUCGWKHSJ_3D: dc.b $3
	dc.b $E6, $0, $0, $0, $FA
	dc.b $EE, $B, $0, $1, $F2
	dc.b $E, $8, $0, $D, $F2
DATAJLQUCGWKHSJ_3E: dc.b $1
	dc.b $F0, $B, $0, $0, $F3
DATAJLQUCGWKHSJ_3F: dc.b $3
	dc.b $F1, $8, $0, $0, $EF
	dc.b $F9, $D, $0, $3, $EF
	dc.b $9, $4, $0, $B, $F7
DATAJLQUCGWKHSJ_40: dc.b $4
	dc.b $F2, $8, $0, $0, $F8
	dc.b $FA, $C, $0, $3, $F0
	dc.b $2, $8, $0, $7, $F0
	dc.b $A, $4, $0, $A, $F8
DATAJLQUCGWKHSJ_41: dc.b $4
	dc.b $EF, $9, $0, $0, $F8
	dc.b $FF, $C, $0, $6, $F0
	dc.b $7, $8, $0, $A, $F0
	dc.b $F, $4, $0, $D, $F8
DATAJLQUCGWKHSJ_42: dc.b $4
	dc.b $EC, $9, $0, $0, $F8
	dc.b $FC, $8, $0, $6, $F0
	dc.b $4, $C, $0, $9, $F0
	dc.b $C, $8, $0, $D, $F0
DATAJLQUCGWKHSJ_43: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATAJLQUCGWKHSJ_44: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAJLQUCGWKHSJ_45: dc.b $2
	dc.b $F6, $D, $0, $0, $F2
	dc.b $6, $8, $0, $8, $F2
DATAJLQUCGWKHSJ_46: dc.b $1
	dc.b $F3, $B, $0, $0, $F3
DATAJLQUCGWKHSJ_47: dc.b $2
	dc.b $EB, $4, $0, $0, $FB
	dc.b $F3, $B, $0, $2, $F3
DATAJLQUCGWKHSJ_48: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $9, $0, $B, $F8
DATAJLQUCGWKHSJ_49: dc.b $4
	dc.b $E8, $A, $0, $0, $FC
	dc.b $F0, $5, $0, $9, $EC
	dc.b $0, $C, $0, $D, $EC
	dc.b $8, $8, $0, $11, $F4
DATAJLQUCGWKHSJ_4A: dc.b $4
	dc.b $EA, $8, $0, $0, $FA
	dc.b $F2, $D, $0, $3, $F2
	dc.b $2, $8, $0, $B, $F2
	dc.b $A, $5, $0, $E, $F2
DATAJLQUCGWKHSJ_4B: dc.b $3
	dc.b $EB, $9, $0, $0, $F8
	dc.b $FB, $C, $0, $6, $F0
	dc.b $3, $8, $0, $A, $F8
DATAJLQUCGWKHSJ_4C: dc.b $3
	dc.b $F1, $8, $0, $0, $F3
	dc.b $F9, $D, $0, $3, $F3
	dc.b $9, $8, $0, $B, $F3
DATAJLQUCGWKHSJ_4D: dc.b $3
	dc.b $EE, $4, $0, $0, $FB
	dc.b $F6, $D, $0, $2, $F3
	dc.b $6, $4, $0, $A, $FB
DATAJLQUCGWKHSJ_4E: dc.b $1
	dc.b $F2, $F, $0, $0, $EE
DATAJLQUCGWKHSJ_4F: dc.b $4
	dc.b $EA, $0, $0, $0, $2
	dc.b $F2, $D, $0, $1, $F2
	dc.b $FA, $0, $0, $9, $EA
	dc.b $2, $D, $0, $A, $EA
DATAJLQUCGWKHSJ_50: dc.b $4
	dc.b $EC, $4, $0, $0, $FB
	dc.b $F4, $8, $0, $2, $F3
	dc.b $FC, $A, $0, $5, $EB
	dc.b $FC, $5, $0, $E, $3
DATAJLQUCGWKHSJ_51: dc.b $2
	dc.b $ED, $4, $0, $0, $FF
	dc.b $F5, $E, $0, $2, $EF
DATAJLQUCGWKHSJ_52: dc.b $3
	dc.b $EF, $4, $0, $0, $FA
	dc.b $F7, $D, $0, $2, $F2
	dc.b $7, $4, $0, $A, $FA
DATAJLQUCGWKHSJ_53: dc.b $3
	dc.b $ED, $0, $0, $0, $0
	dc.b $F5, $A, $0, $1, $F8
	dc.b $FD, $4, $0, $A, $E8
DATAJLQUCGWKHSJ_54: dc.b $2
	dc.b $F0, $F, $0, $0, $EF
	dc.b $F8, $0, $0, $10, $F
DATAJLQUCGWKHSJ_55: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATAJLQUCGWKHSJ_56: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $D, $0, $3, $EF
	dc.b $4, $9, $0, $B, $F7
DATAJLQUCGWKHSJ_57: dc.b $2
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $C, $0, $C, $F0
DATAJLQUCGWKHSJ_58: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F3
DATAJLQUCGWKHSJ_59: dc.b $4
	dc.b $EC, $8, $0, $0, $F7
	dc.b $F4, $C, $0, $3, $EF
	dc.b $FC, $8, $0, $7, $F7
	dc.b $4, $D, $0, $A, $EF
DATAJLQUCGWKHSJ_5A: dc.b $3
	dc.b $EC, $A, $0, $0, $F6
	dc.b $4, $C, $0, $9, $EE
	dc.b $C, $8, $0, $D, $F6
DATAJLQUCGWKHSJ_5B: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F3
DATAJLQUCGWKHSJ_5C: dc.b $3
	dc.b $F5, $A, $0, $0, $EC
	dc.b $F5, $9, $0, $9, $4
	dc.b $5, $0, $0, $F, $14
DATAJLQUCGWKHSJ_5D: dc.b $1
	dc.b $F4, $E, $0, $0, $FC
DATAJLQUCGWKHSJ_5E: dc.b $2
	dc.b $F4, $E, $0, $0, $E2
	dc.b $F4, $2, $0, $C, $2
DATAJLQUCGWKHSJ_5F: dc.b $3
	dc.b $F5, $5, $0, $0, $E5
	dc.b $F5, $E, $0, $4, $F5
	dc.b $5, $0, $0, $10, $E5
DATAJLQUCGWKHSJ_60: dc.b $1
	dc.b $F4, $E, $0, $0, $F6
DATAJLQUCGWKHSJ_61: dc.b $2
	dc.b $FC, $0, $0, $0, $DA
	dc.b $F4, $E, $0, $1, $E2
DATAJLQUCGWKHSJ_62: dc.b $2
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $6, $0, $9, $4
DATAJLQUCGWKHSJ_63: dc.b $3
	dc.b $E8, $A, $0, $0, $F5
	dc.b $0, $5, $0, $9, $F5
	dc.b $10, $8, $0, $D, $F5
DATAJLQUCGWKHSJ_64: dc.b $1
	dc.b $F1, $B, $0, $0, $F3
DATAJLQUCGWKHSJ_65: dc.b $2
	dc.b $EB, $B, $0, $0, $F4
	dc.b $B, $8, $0, $C, $F4
DATAJLQUCGWKHSJ_66: dc.b $3
	dc.b $E8, $8, $0, $0, $F4
	dc.b $F0, $4, $0, $3, $F4
	dc.b $F8, $B, $0, $5, $F4
DATAJLQUCGWKHSJ_67: dc.b $1
	dc.b $F0, $B, $0, $0, $F2
DATAJLQUCGWKHSJ_68: dc.b $2
	dc.b $E8, $0, $0, $0, $FA
	dc.b $F0, $B, $0, $1, $F2
DATAJLQUCGWKHSJ_69: dc.b $2
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
DATAJLQUCGWKHSJ_6A: dc.b $4
	dc.b $EC, $4, $0, $0, $F0
	dc.b $F4, $C, $0, $2, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $4, $0, $C, $F8
DATAJLQUCGWKHSJ_6B: dc.b $3
	dc.b $EC, $0, $0, $0, $FB
	dc.b $F4, $D, $0, $1, $EB
	dc.b $4, $8, $0, $9, $F3
DATAJLQUCGWKHSJ_6C: dc.b $3
	dc.b $F0, $0, $0, $0, $0
	dc.b $F8, $D, $0, $1, $F0
	dc.b $8, $8, $0, $9, $F0
DATAJLQUCGWKHSJ_6D: dc.b $2
	dc.b $F8, $6, $0, $0, $EC
	dc.b $F0, $B, $0, $6, $FC
DATAJLQUCGWKHSJ_6E: dc.b $3
	dc.b $F0, $0, $0, $0, $FC
	dc.b $F8, $A, $0, $1, $EC
	dc.b $F8, $5, $0, $A, $4
DATAJLQUCGWKHSJ_6F: dc.b $3
	dc.b $F0, $4, $0, $0, $F8
	dc.b $F8, $9, $0, $2, $F0
	dc.b $8, $C, $0, $8, $F0
DATAJLQUCGWKHSJ_70: dc.b $3
	dc.b $F0, $9, $0, $0, $F8
	dc.b $0, $C, $0, $6, $F0
	dc.b $8, $4, $0, $A, $0
DATAJLQUCGWKHSJ_71: dc.b $2
	dc.b $F0, $0, $0, $0, $0
	dc.b $F8, $E, $0, $1, $F0
DATAJLQUCGWKHSJ_72: dc.b $4
	dc.b $F0, $4, $0, $0, $F4
	dc.b $F8, $0, $0, $2, $EC
	dc.b $8, $0, $0, $3, $EC
	dc.b $F8, $E, $0, $4, $F4
DATAJLQUCGWKHSJ_73: dc.b $3
	dc.b $F0, $4, $0, $0, $FC
	dc.b $F8, $E, $0, $2, $EC
	dc.b $F8, $2, $0, $E, $C
DATAJLQUCGWKHSJ_74: dc.b $3
	dc.b $F0, $4, $0, $0, $F8
	dc.b $F8, $D, $0, $2, $F0
	dc.b $8, $8, $0, $A, $F8
DATAJLQUCGWKHSJ_75: dc.b $2
	dc.b $F0, $0, $0, $0, $F4
	dc.b $F8, $A, $0, $1, $F4
DATAJLQUCGWKHSJ_76: dc.b $3
	dc.b $F0, $8, $0, $0, $F0
	dc.b $F8, $D, $0, $3, $F0
	dc.b $8, $8, $0, $B, $F0
DATAJLQUCGWKHSJ_77: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATAJLQUCGWKHSJ_78: dc.b $4
	dc.b $E7, $C, $0, $0, $EE
	dc.b $EF, $8, $0, $4, $EE
	dc.b $F7, $D, $0, $7, $EE
	dc.b $7, $D, $0, $F, $F6
DATAJLQUCGWKHSJ_79: dc.b $4
	dc.b $E6, $4, $0, $0, $E9
	dc.b $EE, $E, $0, $2, $E1
	dc.b $F6, $6, $0, $E, $1
	dc.b $6, $8, $0, $14, $E9
DATAJLQUCGWKHSJ_7A: dc.b $3
	dc.b $F1, $8, $0, $0, $E6
	dc.b $F9, $E, $0, $3, $E6
	dc.b $E9, $7, $0, $F, $6
DATAJLQUCGWKHSJ_7B: dc.b $4
	dc.b $EE, $8, $0, $0, $F5
	dc.b $F6, $4, $0, $3, $FD
	dc.b $6, $1, $0, $5, $E5
	dc.b $FE, $F, $0, $7, $ED
DATAJLQUCGWKHSJ_7C: dc.b $4
	dc.b $12, $C, $18, $0, $F1
	dc.b $A, $8, $18, $4, $F9
	dc.b $FA, $D, $18, $7, $F1
	dc.b $EA, $D, $18, $F, $E9
DATAJLQUCGWKHSJ_7D: dc.b $4
	dc.b $13, $4, $18, $0, $4
	dc.b $FB, $E, $18, $2, $FC
	dc.b $F3, $6, $18, $E, $EC
	dc.b $F3, $8, $18, $14, $FC
DATAJLQUCGWKHSJ_7E: dc.b $3
	dc.b $7, $8, $18, $0, $1
	dc.b $EF, $E, $18, $3, $F9
	dc.b $F7, $7, $18, $F, $E9
DATAJLQUCGWKHSJ_7F: dc.b $4
	dc.b $C, $8, $18, $0, $F3
	dc.b $4, $4, $18, $3, $F3
	dc.b $EC, $1, $18, $5, $13
	dc.b $E4, $F, $18, $7, $F3
DATAJLQUCGWKHSJ_80: dc.b $4
	dc.b $E8, $E, $0, $0, $EF
	dc.b $E8, $0, $0, $C, $F
	dc.b $0, $4, $0, $D, $F7
	dc.b $8, $9, $0, $F, $EF
DATAJLQUCGWKHSJ_81: dc.b $4
	dc.b $E8, $C, $0, $0, $EE
	dc.b $F0, $D, $0, $4, $EE
	dc.b $0, $5, $0, $C, $F6
	dc.b $10, $8, $0, $10, $EE
DATAJLQUCGWKHSJ_82: dc.b $3
	dc.b $E8, $8, $0, $0, $F4
	dc.b $F0, $C, $0, $3, $EC
	dc.b $F8, $B, $0, $7, $F4
DATAJLQUCGWKHSJ_83: dc.b $4
	dc.b $E8, $0, $0, $0, $EA
	dc.b $E8, $D, $0, $1, $F2
	dc.b $F8, $8, $0, $9, $F2
	dc.b $0, $6, $0, $C, $FA
DATAJLQUCGWKHSJ_84: dc.b $3
	dc.b $E8, $E, $0, $0, $ED
	dc.b $0, $9, $0, $C, $F5
	dc.b $10, $4, $0, $12, $F5
DATAJLQUCGWKHSJ_85: dc.b $2
	dc.b $E8, $E, $0, $0, $EF
	dc.b $0, $6, $0, $C, $F7
DATAJLQUCGWKHSJ_86: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATAJLQUCGWKHSJ_87: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAJLQUCGWKHSJ_88: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAJLQUCGWKHSJ_89: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAJLQUCGWKHSJ_8A: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAJLQUCGWKHSJ_8B: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAJLQUCGWKHSJ_8C: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F0, $2, $0, $C, $C
	dc.b $8, $8, $0, $F, $F4
DATAJLQUCGWKHSJ_8D: dc.b $3
	dc.b $EF, $E, $0, $0, $EC
	dc.b $EF, $2, $0, $C, $C
	dc.b $7, $8, $0, $F, $F4
DATAJLQUCGWKHSJ_8E: dc.b $2
	dc.b $E8, $B, $0, $0, $F1
	dc.b $8, $5, $0, $C, $F9
DATAJLQUCGWKHSJ_8F: dc.b $3
	dc.b $F1, $C, $0, $0, $E9
	dc.b $F9, $5, $0, $4, $E9
	dc.b $F9, $A, $0, $8, $F9
DATAJLQUCGWKHSJ_90: dc.b $4
	dc.b $E8, $9, $0, $0, $F0
	dc.b $F8, $C, $0, $6, $F0
	dc.b $0, $8, $0, $A, $F0
	dc.b $8, $9, $0, $D, $F8
DATAJLQUCGWKHSJ_91: dc.b $4
	dc.b $E6, $9, $0, $0, $F0
	dc.b $F6, $C, $0, $6, $F0
	dc.b $FE, $8, $0, $A, $F0
	dc.b $6, $D, $0, $D, $F8
DATAJLQUCGWKHSJ_92: dc.b $4
	dc.b $E8, $8, $0, $0, $F0
	dc.b $F0, $E, $0, $3, $F0
	dc.b $0, $0, $0, $F, $10
	dc.b $8, $4, $0, $10, $0
DATAJLQUCGWKHSJ_93: dc.b $2
	dc.b $E8, $8, $0, $0, $F0
	dc.b $F0, $E, $0, $3, $F0
DATAJLQUCGWKHSJ_94: dc.b $5
	dc.b $E8, $D, $0, $0, $F2
	dc.b $E8, $4, $0, $8, $F7
	dc.b $F0, $9, $0, $A, $F7
	dc.b $0, $5, $0, $10, $F7
	dc.b $10, $8, $0, $14, $F7
DATAJLQUCGWKHSJ_95: dc.b $5
	dc.b $E8, $8, $0, $0, $F6
	dc.b $E8, $4, $0, $3, $F7
	dc.b $F0, $9, $0, $5, $F7
	dc.b $0, $5, $0, $B, $F7
	dc.b $10, $8, $0, $F, $F7
DATAJLQUCGWKHSJ_96: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJLQUCGWKHSJ_97: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJLQUCGWKHSJ_98: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJLQUCGWKHSJ_99: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJLQUCGWKHSJ_9A: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAJLQUCGWKHSJ_9B: dc.b $2
	dc.b $EC, $0, $0, $0, $0
	dc.b $F4, $B, $0, $1, $F8
DATAJLQUCGWKHSJ_9C: dc.b $2
	dc.b $F4, $0, $0, $0, $3
	dc.b $FC, $E, $0, $1, $F3
DATAJLQUCGWKHSJ_9D: dc.b $4
	dc.b $EB, $A, $0, $0, $F5
	dc.b $F3, $1, $0, $9, $ED
	dc.b $3, $C, $0, $B, $F5
	dc.b $B, $8, $0, $F, $FD
DATAJLQUCGWKHSJ_9E: dc.b $4
	dc.b $EB, $A, $0, $0, $F6
	dc.b $F3, $1, $0, $9, $EE
	dc.b $3, $C, $0, $B, $F6
	dc.b $B, $8, $0, $F, $FE
DATAJLQUCGWKHSJ_9F: dc.b $4
	dc.b $EA, $8, $0, $0, $F9
	dc.b $F2, $D, $0, $3, $F1
	dc.b $2, $8, $0, $B, $F9
	dc.b $A, $4, $0, $E, $1
DATAJLQUCGWKHSJ_A0: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $E, $0, $3, $EF
	dc.b $C, $8, $0, $F, $F7
DATAJLQUCGWKHSJ_A1: dc.b $3
	dc.b $EC, $D, $0, $0, $EB
	dc.b $EC, $0, $0, $8, $B
	dc.b $FC, $A, $0, $9, $EB
DATAJLQUCGWKHSJ_A2: dc.b $4
	dc.b $E5, $0, $0, $0, $F4
	dc.b $ED, $E, $0, $1, $EC
	dc.b $ED, $0, $0, $D, $E4
	dc.b $5, $9, $0, $E, $EC
DATAJLQUCGWKHSJ_A3: dc.b $3
	dc.b $E4, $0, $0, $0, $FB
	dc.b $EC, $F, $0, $1, $EB
	dc.b $C, $8, $0, $11, $EB
DATAJLQUCGWKHSJ_A4: dc.b $4
	dc.b $EC, $8, $0, $0, $FA
	dc.b $F4, $E, $0, $3, $EA
	dc.b $F4, $1, $0, $F, $A
	dc.b $C, $8, $0, $11, $F2
DATAJLQUCGWKHSJ_A5: dc.b $3
	dc.b $EC, $F, $0, $0, $F3
	dc.b $4, $0, $0, $10, $EB
	dc.b $C, $8, $0, $11, $F3
DATAJLQUCGWKHSJ_A6: dc.b $4
	dc.b $ED, $8, $0, $0, $FA
	dc.b $F5, $E, $0, $3, $EA
	dc.b $F5, $1, $0, $F, $A
	dc.b $D, $8, $0, $11, $F2
DATAJLQUCGWKHSJ_A7: dc.b $3
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
	dc.b $F4, $0, $0, $13, $10
DATAJLQUCGWKHSJ_A8: dc.b $3
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
	dc.b $F4, $0, $0, $13, $10
DATAJLQUCGWKHSJ_A9: dc.b $3
	dc.b $EC, $4, $0, $0, $F8
	dc.b $F4, $F, $0, $2, $F0
	dc.b $F4, $0, $0, $12, $10
DATAJLQUCGWKHSJ_AA: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $0, $0, $C, $6
	dc.b $FC, $9, $0, $D, $6
DATAJLQUCGWKHSJ_AB: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $0, $0, $C, $6
	dc.b $FC, $9, $0, $D, $6
DATAJLQUCGWKHSJ_AC: dc.b $4
	dc.b $EC, $F, $0, $0, $EC
	dc.b $4, $0, $0, $10, $C
	dc.b $C, $4, $0, $11, $EC
	dc.b $C, $4, $0, $13, $4
DATAJLQUCGWKHSJ_AD: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $4, $0, $B, $F6
	dc.b $C, $8, $0, $D, $F6
DATAJLQUCGWKHSJ_AE: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $4, $0, $B, $F6
	dc.b $C, $8, $0, $D, $F6
DATAJLQUCGWKHSJ_AF: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $C, $0, $3, $E6
	dc.b $FC, $D, $0, $7, $EE
	dc.b $C, $8, $0, $F, $F6
DATAJLQUCGWKHSJ_B0: dc.b $2
	dc.b $EC, $D, $0, $0, $EA
	dc.b $FC, $A, $0, $8, $F2
DATAJLQUCGWKHSJ_B1: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $D, $0, $3, $EF
	dc.b $4, $9, $0, $B, $EF
DATAJLQUCGWKHSJ_B2: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $D, $0, $3, $EF
	dc.b $4, $9, $0, $B, $EF
DATAJLQUCGWKHSJ_B3: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $D, $0, $3, $EF
	dc.b $4, $9, $0, $B, $EF
DATAJLQUCGWKHSJ_B4: dc.b $3
	dc.b $E6, $B, $0, $0, $F5
	dc.b $6, $8, $0, $C, $F5
	dc.b $E, $5, $0, $F, $F5
DATAJLQUCGWKHSJ_B5: dc.b $3
	dc.b $E6, $B, $0, $0, $F5
	dc.b $6, $8, $0, $C, $F5
	dc.b $E, $5, $0, $F, $F5
DATAJLQUCGWKHSJ_B6: dc.b $3
	dc.b $EC, $4, $0, $0, $FD
	dc.b $F4, $A, $0, $2, $F5
	dc.b $C, $C, $0, $B, $ED
DATAJLQUCGWKHSJ_B7: dc.b $3
	dc.b $EC, $4, $0, $0, $FD
	dc.b $F4, $A, $0, $2, $F5
	dc.b $C, $4, $0, $B, $F5
DATAJLQUCGWKHSJ_B8: dc.b $3
	dc.b $EC, $4, $0, $0, $FD
	dc.b $F4, $9, $0, $2, $F5
	dc.b $4, $D, $0, $8, $ED
DATAJLQUCGWKHSJ_B9: dc.b $3
	dc.b $EC, $4, $0, $0, $FD
	dc.b $F4, $A, $0, $2, $F5
	dc.b $C, $4, $0, $B, $F5
DATAJLQUCGWKHSJ_BA: dc.b $4
	dc.b $FC, $A, $0, $0, $F8
	dc.b $EC, $8, $0, $9, $F0
	dc.b $F4, $C, $0, $C, $F0
	dc.b $FC, $0, $0, $10, $F0
DATAJLQUCGWKHSJ_BB: dc.b $3
	dc.b $ED, $8, $0, $0, $EE
	dc.b $F5, $D, $0, $3, $EE
	dc.b $5, $9, $0, $B, $F6
DATAJLQUCGWKHSJ_BC: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $EE
	dc.b $C, $8, $0, $E, $F6
DATAJLQUCGWKHSJ_BD: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $EE
	dc.b $C, $8, $0, $E, $F6
DATAJLQUCGWKHSJ_BE: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $EE
	dc.b $C, $8, $0, $E, $F6
DATAJLQUCGWKHSJ_BF: dc.b $2
	dc.b $EA, $D, $0, $0, $EA
	dc.b $FA, $B, $0, $8, $F2
DATAJLQUCGWKHSJ_C0: dc.b $2
	dc.b $E9, $D, $0, $0, $EB
	dc.b $F9, $B, $0, $8, $F4
DATAJLQUCGWKHSJ_C1: dc.b $3
	dc.b $E4, $B, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F8
	dc.b $EC, $2, $0, $10, $8
DATAJLQUCGWKHSJ_C2: dc.b $2
	dc.b $E5, $F, $0, $0, $F0
	dc.b $5, $5, $0, $10, $F8
DATAJLQUCGWKHSJ_C3: dc.b $4
	dc.b $EC, $8, $0, $0, $ED
	dc.b $F4, $D, $0, $3, $ED
	dc.b $4, $8, $0, $B, $F5
	dc.b $C, $8, $0, $E, $F5
DATAJLQUCGWKHSJ_C4: dc.b $4
	dc.b $EE, $8, $0, $0, $ED
	dc.b $F6, $C, $0, $3, $E5
	dc.b $FE, $C, $0, $7, $ED
	dc.b $6, $9, $0, $B, $F5
DATAJLQUCGWKHSJ_C5: dc.b $2
	dc.b $F1, $E, $0, $0, $EB
	dc.b $9, $9, $0, $C, $F2
DATAJLQUCGWKHSJ_C6: dc.b $2
	dc.b $F1, $F, $0, $0, $EE
	dc.b $11, $C, $0, $10, $EE
DATAJLQUCGWKHSJ_C7: dc.b $2
	dc.b $F4, $F, $0, $0, $EC
	dc.b $EC, $4, $0, $10, $F4
DATAJLQUCGWKHSJ_C8: dc.b $3
	dc.b $F4, $A, $0, $0, $FB
	dc.b $FC, $4, $0, $9, $EB
	dc.b $4, $8, $0, $B, $E3
DATAJLQUCGWKHSJ_C9: dc.b $3
	dc.b $F4, $9, $0, $0, $F4
	dc.b $4, $C, $0, $6, $EC
	dc.b $4, $0, $0, $A, $C
DATAJLQUCGWKHSJ_CA: dc.b $2
	dc.b $F4, $9, $0, $0, $F7
	dc.b $4, $C, $0, $6, $EF
DATAJLQUCGWKHSJ_CB: dc.b $3
	dc.b $F4, $9, $8, $0, $F3
	dc.b $4, $C, $8, $6, $F3
	dc.b $4, $0, $8, $A, $EB
DATAJLQUCGWKHSJ_CC: dc.b $3
	dc.b $F4, $A, $8, $0, $EE
	dc.b $FC, $4, $8, $9, $6
	dc.b $4, $8, $8, $B, $6
DATAJLQUCGWKHSJ_CD: dc.b $2
	dc.b $F4, $E, $0, $0, $F2
	dc.b $4, $0, $0, $C, $EA
DATAJLQUCGWKHSJ_CE: dc.b $2
	dc.b $F4, $9, $0, $0, $F7
	dc.b $4, $C, $0, $6, $EF
DATAJLQUCGWKHSJ_CF: dc.b $2
	dc.b $F4, $E, $8, $0, $EF
	dc.b $4, $0, $8, $C, $F
DATAJLQUCGWKHSJ_D0: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F8, $2, $0, $C, $C
	dc.b $10, $8, $0, $F, $F4
DATAJLQUCGWKHSJ_D1: dc.b $3
	dc.b $F7, $E, $0, $0, $EC
	dc.b $F7, $2, $0, $C, $C
	dc.b $F, $8, $0, $F, $F4
DATAJLQUCGWKHSJ_D2: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAJLQUCGWKHSJ_D3: dc.b $3
	dc.b $E8, $9, $0, $0, $F3
	dc.b $F8, $D, $0, $6, $F3
	dc.b $8, $9, $0, $E, $F3
DATAJLQUCGWKHSJ_D4: dc.b $2
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $9, $0, $10, $F0
DATAJLQUCGWKHSJ_D5: dc.b $3
	dc.b $E8, $A, $0, $0, $F0
	dc.b $0, $C, $0, $9, $F0
	dc.b $8, $9, $0, $D, $F0
DATAJLQUCGWKHSJ_D6: dc.b $3
	dc.b $EC, $A, $0, $0, $ED
	dc.b $4, $D, $0, $9, $F4
	dc.b $FC, $4, $0, $11, $5
DATAJLQUCGWKHSJ_D7: dc.b $2
	dc.b $ED, $F, $0, $0, $F3
	dc.b $FD, $5, $0, $10, $E3
DATAJLQUCGWKHSJ_D8: dc.b $2
	dc.b $ED, $F, $0, $0, $EE
	dc.b $F5, $0, $0, $10, $E6
DATAJLQUCGWKHSJ_D9: dc.b $2
	dc.b $F0, $F, $10, $0, $F3
	dc.b $F0, $5, $10, $10, $E3
DATAJLQUCGWKHSJ_DA: dc.b $2
	dc.b $F0, $F, $10, $0, $EE
	dc.b $0, $0, $10, $10, $E6
DATAJLQUCGWKHSJ_DB: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAJLQUCGWKHSJ_DC: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAJLQUCGWKHSJ_DD: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAJLQUCGWKHSJ_DE: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAJLQUCGWKHSJ_DF: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAJLQUCGWKHSJ_E0: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAJLQUCGWKHSJ_E1: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAJLQUCGWKHSJ_E2: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAJLQUCGWKHSJ_E3: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
	even