; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Feb 24 2019 23:44:45 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAKBWUH8984OJ:
	dc.w $0, DATAKBWUH8984OJ_1-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_2-DATAKBWUH8984OJ, DATAKBWUH8984OJ_3-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_4-DATAKBWUH8984OJ, DATAKBWUH8984OJ_5-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_6-DATAKBWUH8984OJ, DATAKBWUH8984OJ_7-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_8-DATAKBWUH8984OJ, DATAKBWUH8984OJ_9-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_10-DATAKBWUH8984OJ, DATAKBWUH8984OJ_11-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_12-DATAKBWUH8984OJ, DATAKBWUH8984OJ_13-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_14-DATAKBWUH8984OJ, DATAKBWUH8984OJ_15-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_16-DATAKBWUH8984OJ, DATAKBWUH8984OJ_17-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_18-DATAKBWUH8984OJ, DATAKBWUH8984OJ_19-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_1A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_1B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_1C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_1D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_1E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_1F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_20-DATAKBWUH8984OJ, DATAKBWUH8984OJ_21-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_22-DATAKBWUH8984OJ, DATAKBWUH8984OJ_23-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_24-DATAKBWUH8984OJ, DATAKBWUH8984OJ_25-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_26-DATAKBWUH8984OJ, DATAKBWUH8984OJ_27-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_28-DATAKBWUH8984OJ, DATAKBWUH8984OJ_29-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_2A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_2B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_2C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_2D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_2E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_2F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_30-DATAKBWUH8984OJ, DATAKBWUH8984OJ_31-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_32-DATAKBWUH8984OJ, DATAKBWUH8984OJ_33-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_34-DATAKBWUH8984OJ, DATAKBWUH8984OJ_35-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_36-DATAKBWUH8984OJ, DATAKBWUH8984OJ_37-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_38-DATAKBWUH8984OJ, DATAKBWUH8984OJ_39-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_3A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_3B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_3C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_3D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_3E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_3F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_40-DATAKBWUH8984OJ, DATAKBWUH8984OJ_41-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_42-DATAKBWUH8984OJ, DATAKBWUH8984OJ_43-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_44-DATAKBWUH8984OJ, DATAKBWUH8984OJ_45-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_46-DATAKBWUH8984OJ, DATAKBWUH8984OJ_47-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_48-DATAKBWUH8984OJ, DATAKBWUH8984OJ_49-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_4A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_4B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_4C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_4D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_4E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_4F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_50-DATAKBWUH8984OJ, DATAKBWUH8984OJ_51-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_52-DATAKBWUH8984OJ, DATAKBWUH8984OJ_53-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_54-DATAKBWUH8984OJ, DATAKBWUH8984OJ_55-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_56-DATAKBWUH8984OJ, DATAKBWUH8984OJ_57-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_58-DATAKBWUH8984OJ, DATAKBWUH8984OJ_59-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_5A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_5B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_5C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_5D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_5E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_5F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_60-DATAKBWUH8984OJ, DATAKBWUH8984OJ_61-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_62-DATAKBWUH8984OJ, DATAKBWUH8984OJ_63-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_64-DATAKBWUH8984OJ, DATAKBWUH8984OJ_65-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_66-DATAKBWUH8984OJ, DATAKBWUH8984OJ_67-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_68-DATAKBWUH8984OJ, DATAKBWUH8984OJ_69-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_6A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_6B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_6C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_6D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_6E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_6F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_70-DATAKBWUH8984OJ, DATAKBWUH8984OJ_71-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_72-DATAKBWUH8984OJ, DATAKBWUH8984OJ_73-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_74-DATAKBWUH8984OJ, DATAKBWUH8984OJ_75-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_76-DATAKBWUH8984OJ, DATAKBWUH8984OJ_77-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_78-DATAKBWUH8984OJ, DATAKBWUH8984OJ_79-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_7A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_7B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_7C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_7D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_7E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_7F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_80-DATAKBWUH8984OJ, DATAKBWUH8984OJ_81-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_82-DATAKBWUH8984OJ, DATAKBWUH8984OJ_83-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_84-DATAKBWUH8984OJ, DATAKBWUH8984OJ_85-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_86-DATAKBWUH8984OJ, DATAKBWUH8984OJ_87-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_88-DATAKBWUH8984OJ, DATAKBWUH8984OJ_89-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_8A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_8B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_8C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_8D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_8E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_8F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_90-DATAKBWUH8984OJ, DATAKBWUH8984OJ_91-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_92-DATAKBWUH8984OJ, DATAKBWUH8984OJ_93-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_94-DATAKBWUH8984OJ, DATAKBWUH8984OJ_95-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_96-DATAKBWUH8984OJ, DATAKBWUH8984OJ_97-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_98-DATAKBWUH8984OJ, DATAKBWUH8984OJ_99-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_9A-DATAKBWUH8984OJ, DATAKBWUH8984OJ_9B-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_9C-DATAKBWUH8984OJ, DATAKBWUH8984OJ_9D-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_9E-DATAKBWUH8984OJ, DATAKBWUH8984OJ_9F-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_A0-DATAKBWUH8984OJ, DATAKBWUH8984OJ_A1-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_A2-DATAKBWUH8984OJ, DATAKBWUH8984OJ_A3-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_A4-DATAKBWUH8984OJ, DATAKBWUH8984OJ_A5-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_A6-DATAKBWUH8984OJ, DATAKBWUH8984OJ_A7-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_A8-DATAKBWUH8984OJ, DATAKBWUH8984OJ_A9-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_AA-DATAKBWUH8984OJ, DATAKBWUH8984OJ_AB-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_AC-DATAKBWUH8984OJ, DATAKBWUH8984OJ_AD-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_AE-DATAKBWUH8984OJ, DATAKBWUH8984OJ_AF-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_B0-DATAKBWUH8984OJ, DATAKBWUH8984OJ_B1-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_B2-DATAKBWUH8984OJ, DATAKBWUH8984OJ_B3-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_B4-DATAKBWUH8984OJ, DATAKBWUH8984OJ_B5-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_B6-DATAKBWUH8984OJ, DATAKBWUH8984OJ_B7-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_B8-DATAKBWUH8984OJ, DATAKBWUH8984OJ_B9-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_BA-DATAKBWUH8984OJ, DATAKBWUH8984OJ_BB-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_BC-DATAKBWUH8984OJ, DATAKBWUH8984OJ_BD-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_BE-DATAKBWUH8984OJ, DATAKBWUH8984OJ_BF-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_C0-DATAKBWUH8984OJ, DATAKBWUH8984OJ_C1-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_C2-DATAKBWUH8984OJ, DATAKBWUH8984OJ_C3-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_C4-DATAKBWUH8984OJ, DATAKBWUH8984OJ_C5-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_C6-DATAKBWUH8984OJ, DATAKBWUH8984OJ_C7-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_C8-DATAKBWUH8984OJ, DATAKBWUH8984OJ_C9-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_CA-DATAKBWUH8984OJ, DATAKBWUH8984OJ_CB-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_CC-DATAKBWUH8984OJ, DATAKBWUH8984OJ_CD-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_CE-DATAKBWUH8984OJ, DATAKBWUH8984OJ_CF-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_D0-DATAKBWUH8984OJ, DATAKBWUH8984OJ_D1-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_D2-DATAKBWUH8984OJ, DATAKBWUH8984OJ_D3-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_D4-DATAKBWUH8984OJ, DATAKBWUH8984OJ_D5-DATAKBWUH8984OJ
	dc.w DATAKBWUH8984OJ_D6-DATAKBWUH8984OJ
DATAKBWUH8984OJ_1: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $FC, $6, $0, $8, $4
	dc.b $FC, $A, $0, $E, $EC
DATAKBWUH8984OJ_2: dc.b $3
	dc.b $FD, $E, $0, $0, $EC
	dc.b $5, $1, $0, $C, $C
	dc.b $ED, $D, $0, $E, $EC
DATAKBWUH8984OJ_3: dc.b $3
	dc.b $FE, $A, $0, $0, $F4
	dc.b $F6, $C, $0, $9, $EC
	dc.b $EE, $8, $0, $D, $F4
DATAKBWUH8984OJ_4: dc.b $2
	dc.b $FC, $E, $0, $0, $EE
	dc.b $EC, $9, $0, $C, $F4
DATAKBWUH8984OJ_5: dc.b $3
	dc.b $FC, $E, $0, $0, $EE
	dc.b $FC, $1, $0, $C, $E
	dc.b $EC, $9, $0, $E, $F4
DATAKBWUH8984OJ_6: dc.b $3
	dc.b $FD, $E, $0, $0, $ED
	dc.b $5, $1, $0, $C, $D
	dc.b $ED, $9, $0, $E, $F4
DATAKBWUH8984OJ_7: dc.b $3
	dc.b $FE, $A, $0, $0, $F4
	dc.b $F6, $C, $0, $9, $EC
	dc.b $EE, $8, $0, $D, $F4
DATAKBWUH8984OJ_8: dc.b $2
	dc.b $FC, $A, $0, $0, $F4
	dc.b $EC, $D, $0, $9, $EC
DATAKBWUH8984OJ_9: dc.b $4
	dc.b $FD, $B, $0, $0, $FB
	dc.b $ED, $D, $0, $C, $EB
	dc.b $F5, $0, $0, $14, $B
	dc.b $FD, $5, $0, $15, $EB
DATAKBWUH8984OJ_A: dc.b $4
	dc.b $2, $E, $0, $0, $FC
	dc.b $F2, $D, $0, $C, $EC
	dc.b $FA, $4, $0, $14, $C
	dc.b $2, $4, $0, $16, $EC
DATAKBWUH8984OJ_B: dc.b $4
	dc.b $FB, $A, $0, $0, $FD
	dc.b $EB, $4, $0, $9, $F5
	dc.b $F3, $C, $0, $B, $ED
	dc.b $FB, $5, $0, $F, $ED
DATAKBWUH8984OJ_C: dc.b $4
	dc.b $FD, $E, $0, $0, $FC
	dc.b $ED, $D, $0, $C, $EC
	dc.b $FD, $4, $0, $14, $EC
	dc.b $5, $0, $0, $16, $F4
DATAKBWUH8984OJ_D: dc.b $4
	dc.b $FE, $B, $0, $0, $FC
	dc.b $EE, $D, $0, $C, $EC
	dc.b $EE, $1, $0, $14, $C
	dc.b $FE, $6, $0, $16, $EC
DATAKBWUH8984OJ_E: dc.b $4
	dc.b $FC, $F, $0, $0, $FB
	dc.b $EC, $9, $0, $10, $EB
	dc.b $F4, $8, $0, $16, $3
	dc.b $FC, $5, $0, $19, $EB
DATAKBWUH8984OJ_F: dc.b $4
	dc.b $FF, $A, $0, $0, $FA
	dc.b $EF, $D, $0, $9, $EA
	dc.b $FF, $4, $0, $11, $EA
	dc.b $7, $0, $0, $13, $F2
DATAKBWUH8984OJ_10: dc.b $4
	dc.b $FE, $A, $0, $0, $FC
	dc.b $EE, $8, $0, $9, $EC
	dc.b $F6, $C, $0, $C, $EC
	dc.b $FE, $5, $0, $10, $EC
DATAKBWUH8984OJ_11: dc.b $3
	dc.b $ED, $9, $0, $0, $FC
	dc.b $FD, $A, $0, $6, $FC
	dc.b $F5, $7, $0, $F, $EC
DATAKBWUH8984OJ_12: dc.b $3
	dc.b $F5, $B, $0, $0, $FC
	dc.b $ED, $4, $0, $C, $4
	dc.b $F5, $7, $0, $E, $EC
DATAKBWUH8984OJ_13: dc.b $3
	dc.b $F5, $A, $0, $0, $FC
	dc.b $F5, $6, $0, $9, $EC
	dc.b $D, $0, $0, $F, $F4
DATAKBWUH8984OJ_14: dc.b $2
	dc.b $F3, $B, $0, $0, $FC
	dc.b $F3, $7, $0, $C, $EC
DATAKBWUH8984OJ_15: dc.b $3
	dc.b $EB, $4, $0, $0, $FC
	dc.b $F3, $B, $0, $2, $FC
	dc.b $F3, $7, $0, $E, $EC
DATAKBWUH8984OJ_16: dc.b $4
	dc.b $EC, $4, $0, $0, $4
	dc.b $F4, $B, $0, $2, $FC
	dc.b $F4, $6, $0, $E, $EC
	dc.b $C, $0, $0, $14, $F4
DATAKBWUH8984OJ_17: dc.b $3
	dc.b $F5, $A, $0, $0, $FC
	dc.b $F5, $6, $0, $9, $EC
	dc.b $D, $0, $0, $F, $F4
DATAKBWUH8984OJ_18: dc.b $2
	dc.b $F5, $A, $0, $0, $FC
	dc.b $F5, $7, $0, $9, $EC
DATAKBWUH8984OJ_19: dc.b $4
	dc.b $EF, $E, $0, $0, $FE
	dc.b $EF, $6, $0, $C, $EE
	dc.b $7, $C, $0, $12, $EE
	dc.b $F, $8, $0, $16, $EE
DATAKBWUH8984OJ_1A: dc.b $4
	dc.b $E7, $B, $0, $0, $0
	dc.b $E7, $1, $0, $C, $F8
	dc.b $F7, $5, $0, $E, $F0
	dc.b $7, $9, $0, $12, $F0
DATAKBWUH8984OJ_1B: dc.b $4
	dc.b $EF, $A, $0, $0, $FD
	dc.b $F7, $5, $0, $9, $ED
	dc.b $7, $C, $0, $D, $ED
	dc.b $F, $4, $0, $11, $F5
DATAKBWUH8984OJ_1C: dc.b $4
	dc.b $E7, $B, $0, $0, $0
	dc.b $F7, $5, $0, $C, $F0
	dc.b $7, $C, $0, $10, $F0
	dc.b $F, $8, $0, $14, $F0
DATAKBWUH8984OJ_1D: dc.b $4
	dc.b $EE, $E, $0, $0, $FF
	dc.b $EE, $6, $0, $C, $EF
	dc.b $6, $D, $0, $12, $EF
	dc.b $6, $0, $0, $1A, $F
DATAKBWUH8984OJ_1E: dc.b $4
	dc.b $E8, $F, $0, $0, $FF
	dc.b $E8, $2, $0, $10, $F7
	dc.b $0, $4, $0, $13, $EF
	dc.b $8, $D, $0, $15, $EF
DATAKBWUH8984OJ_1F: dc.b $4
	dc.b $EE, $A, $0, $0, $FE
	dc.b $F6, $5, $0, $9, $EE
	dc.b $6, $C, $0, $D, $EE
	dc.b $E, $8, $0, $11, $EE
DATAKBWUH8984OJ_20: dc.b $4
	dc.b $EE, $A, $0, $0, $FE
	dc.b $F6, $5, $0, $9, $EE
	dc.b $6, $C, $0, $D, $EE
	dc.b $E, $8, $0, $11, $EE
DATAKBWUH8984OJ_21: dc.b $2
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
DATAKBWUH8984OJ_22: dc.b $2
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
DATAKBWUH8984OJ_23: dc.b $2
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
DATAKBWUH8984OJ_24: dc.b $2
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
DATAKBWUH8984OJ_25: dc.b $4
	dc.b $EF, $E, $0, $0, $ED
	dc.b $FF, $0, $0, $C, $D
	dc.b $7, $C, $0, $D, $F5
	dc.b $F, $8, $0, $11, $F5
DATAKBWUH8984OJ_26: dc.b $2
	dc.b $EE, $8, $0, $0, $F0
	dc.b $F6, $F, $0, $3, $F0
DATAKBWUH8984OJ_27: dc.b $4
	dc.b $EF, $E, $0, $0, $ED
	dc.b $FF, $0, $0, $C, $D
	dc.b $7, $C, $0, $D, $F5
	dc.b $F, $8, $0, $11, $F5
DATAKBWUH8984OJ_28: dc.b $2
	dc.b $EE, $8, $0, $0, $F0
	dc.b $F6, $F, $0, $3, $F0
DATAKBWUH8984OJ_29: dc.b $2
	dc.b $F0, $2, $0, $0, $EC
	dc.b $F0, $F, $0, $3, $F4
DATAKBWUH8984OJ_2A: dc.b $2
	dc.b $F0, $2, $0, $0, $EC
	dc.b $F0, $F, $0, $3, $F4
DATAKBWUH8984OJ_2B: dc.b $2
	dc.b $F0, $2, $0, $0, $EC
	dc.b $F0, $F, $0, $3, $F4
DATAKBWUH8984OJ_2C: dc.b $2
	dc.b $F0, $2, $0, $0, $EC
	dc.b $F0, $F, $0, $3, $F4
DATAKBWUH8984OJ_2D: dc.b $3
	dc.b $EA, $4, $0, $0, $FE
	dc.b $F2, $B, $0, $2, $EE
	dc.b $F2, $6, $0, $E, $6
DATAKBWUH8984OJ_2E: dc.b $2
	dc.b $F7, $2, $0, $0, $ED
	dc.b $EF, $F, $0, $3, $F5
DATAKBWUH8984OJ_2F: dc.b $3
	dc.b $EA, $4, $0, $0, $FE
	dc.b $F2, $B, $0, $2, $EE
	dc.b $F2, $6, $0, $E, $6
DATAKBWUH8984OJ_30: dc.b $2
	dc.b $F7, $2, $0, $0, $ED
	dc.b $EF, $F, $0, $3, $F5
DATAKBWUH8984OJ_31: dc.b $3
	dc.b $EC, $8, $0, $0, $F2
	dc.b $F4, $E, $0, $3, $F2
	dc.b $C, $8, $0, $F, $F2
DATAKBWUH8984OJ_32: dc.b $4
	dc.b $EA, $9, $0, $0, $F3
	dc.b $FA, $C, $0, $6, $F3
	dc.b $2, $8, $0, $A, $F3
	dc.b $A, $4, $0, $D, $FB
DATAKBWUH8984OJ_33: dc.b $4
	dc.b $F0, $4, $0, $0, $F9
	dc.b $F8, $8, $0, $2, $F1
	dc.b $0, $C, $0, $5, $F1
	dc.b $8, $4, $0, $9, $F9
DATAKBWUH8984OJ_34: dc.b $4
	dc.b $EF, $8, $0, $0, $F9
	dc.b $F7, $C, $0, $3, $F1
	dc.b $FF, $8, $0, $7, $F1
	dc.b $7, $C, $0, $A, $F1
DATAKBWUH8984OJ_35: dc.b $4
	dc.b $EF, $4, $0, $0, $F4
	dc.b $F7, $8, $0, $2, $F4
	dc.b $FF, $C, $0, $5, $F4
	dc.b $7, $8, $0, $9, $F4
DATAKBWUH8984OJ_36: dc.b $3
	dc.b $EA, $4, $0, $0, $F9
	dc.b $F2, $D, $0, $2, $F1
	dc.b $2, $9, $0, $A, $F1
DATAKBWUH8984OJ_37: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $8, $0, $10, $F0
DATAKBWUH8984OJ_38: dc.b $2
	dc.b $EE, $B, $0, $0, $F4
	dc.b $E, $0, $0, $C, $FC
DATAKBWUH8984OJ_39: dc.b $3
	dc.b $EE, $4, $0, $0, $F0
	dc.b $F6, $D, $0, $2, $F0
	dc.b $6, $8, $0, $A, $F0
DATAKBWUH8984OJ_3A: dc.b $4
	dc.b $F0, $8, $0, $0, $F5
	dc.b $F8, $C, $0, $3, $ED
	dc.b $0, $8, $0, $7, $F5
	dc.b $8, $4, $0, $A, $F5
DATAKBWUH8984OJ_3B: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $5, $0, $9, $FC
DATAKBWUH8984OJ_3C: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAKBWUH8984OJ_3D: dc.b $3
	dc.b $E6, $0, $0, $0, $FA
	dc.b $EE, $B, $0, $1, $F2
	dc.b $E, $8, $0, $D, $F2
DATAKBWUH8984OJ_3E: dc.b $1
	dc.b $F0, $B, $0, $0, $F3
DATAKBWUH8984OJ_3F: dc.b $3
	dc.b $F1, $8, $0, $0, $EF
	dc.b $F9, $D, $0, $3, $EF
	dc.b $9, $4, $0, $B, $F7
DATAKBWUH8984OJ_40: dc.b $4
	dc.b $F2, $8, $0, $0, $F8
	dc.b $FA, $C, $0, $3, $F0
	dc.b $2, $8, $0, $7, $F0
	dc.b $A, $4, $0, $A, $F8
DATAKBWUH8984OJ_41: dc.b $4
	dc.b $EF, $9, $0, $0, $F8
	dc.b $FF, $C, $0, $6, $F0
	dc.b $7, $8, $0, $A, $F0
	dc.b $F, $4, $0, $D, $F8
DATAKBWUH8984OJ_42: dc.b $4
	dc.b $EC, $9, $0, $0, $F8
	dc.b $FC, $8, $0, $6, $F0
	dc.b $4, $C, $0, $9, $F0
	dc.b $C, $8, $0, $D, $F0
DATAKBWUH8984OJ_43: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATAKBWUH8984OJ_44: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAKBWUH8984OJ_45: dc.b $2
	dc.b $F6, $D, $0, $0, $F2
	dc.b $6, $8, $0, $8, $F2
DATAKBWUH8984OJ_46: dc.b $1
	dc.b $F3, $B, $0, $0, $F3
DATAKBWUH8984OJ_47: dc.b $2
	dc.b $EB, $4, $0, $0, $FB
	dc.b $F3, $B, $0, $2, $F3
DATAKBWUH8984OJ_48: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $9, $0, $B, $F8
DATAKBWUH8984OJ_49: dc.b $4
	dc.b $E8, $A, $0, $0, $FC
	dc.b $F0, $5, $0, $9, $EC
	dc.b $0, $C, $0, $D, $EC
	dc.b $8, $8, $0, $11, $F4
DATAKBWUH8984OJ_4A: dc.b $4
	dc.b $EA, $8, $0, $0, $FA
	dc.b $F2, $D, $0, $3, $F2
	dc.b $2, $8, $0, $B, $F2
	dc.b $A, $5, $0, $E, $F2
DATAKBWUH8984OJ_4B: dc.b $3
	dc.b $EB, $9, $0, $0, $F8
	dc.b $FB, $C, $0, $6, $F0
	dc.b $3, $8, $0, $A, $F8
DATAKBWUH8984OJ_4C: dc.b $3
	dc.b $F1, $8, $0, $0, $F3
	dc.b $F9, $D, $0, $3, $F3
	dc.b $9, $8, $0, $B, $F3
DATAKBWUH8984OJ_4D: dc.b $3
	dc.b $EE, $4, $0, $0, $FB
	dc.b $F6, $D, $0, $2, $F3
	dc.b $6, $4, $0, $A, $FB
DATAKBWUH8984OJ_4E: dc.b $1
	dc.b $F2, $F, $0, $0, $EE
DATAKBWUH8984OJ_4F: dc.b $4
	dc.b $EA, $0, $0, $0, $2
	dc.b $F2, $D, $0, $1, $F2
	dc.b $FA, $0, $0, $9, $EA
	dc.b $2, $D, $0, $A, $EA
DATAKBWUH8984OJ_50: dc.b $4
	dc.b $EC, $4, $0, $0, $FB
	dc.b $F4, $8, $0, $2, $F3
	dc.b $FC, $A, $0, $5, $EB
	dc.b $FC, $5, $0, $E, $3
DATAKBWUH8984OJ_51: dc.b $2
	dc.b $ED, $4, $0, $0, $FF
	dc.b $F5, $E, $0, $2, $EF
DATAKBWUH8984OJ_52: dc.b $3
	dc.b $EF, $4, $0, $0, $FA
	dc.b $F7, $D, $0, $2, $F2
	dc.b $7, $4, $0, $A, $FA
DATAKBWUH8984OJ_53: dc.b $3
	dc.b $ED, $0, $0, $0, $0
	dc.b $F5, $A, $0, $1, $F8
	dc.b $FD, $4, $0, $A, $E8
DATAKBWUH8984OJ_54: dc.b $2
	dc.b $F0, $F, $0, $0, $EF
	dc.b $F8, $0, $0, $10, $F
DATAKBWUH8984OJ_55: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATAKBWUH8984OJ_56: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $D, $0, $3, $EF
	dc.b $4, $9, $0, $B, $F7
DATAKBWUH8984OJ_57: dc.b $2
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $C, $0, $C, $F0
DATAKBWUH8984OJ_58: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F3
DATAKBWUH8984OJ_59: dc.b $4
	dc.b $EC, $8, $0, $0, $F7
	dc.b $F4, $C, $0, $3, $EF
	dc.b $FC, $8, $0, $7, $F7
	dc.b $4, $D, $0, $A, $EF
DATAKBWUH8984OJ_5A: dc.b $3
	dc.b $EC, $A, $0, $0, $F6
	dc.b $4, $C, $0, $9, $EE
	dc.b $C, $8, $0, $D, $F6
DATAKBWUH8984OJ_5B: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F3
DATAKBWUH8984OJ_5C: dc.b $3
	dc.b $F5, $A, $0, $0, $EC
	dc.b $F5, $9, $0, $9, $4
	dc.b $5, $0, $0, $F, $14
DATAKBWUH8984OJ_5D: dc.b $1
	dc.b $F4, $E, $0, $0, $FC
DATAKBWUH8984OJ_5E: dc.b $2
	dc.b $F4, $E, $0, $0, $E2
	dc.b $F4, $2, $0, $C, $2
DATAKBWUH8984OJ_5F: dc.b $3
	dc.b $F5, $5, $0, $0, $E5
	dc.b $F5, $E, $0, $4, $F5
	dc.b $5, $0, $0, $10, $E5
DATAKBWUH8984OJ_60: dc.b $1
	dc.b $F4, $E, $0, $0, $F6
DATAKBWUH8984OJ_61: dc.b $2
	dc.b $FC, $0, $0, $0, $DA
	dc.b $F4, $E, $0, $1, $E2
DATAKBWUH8984OJ_62: dc.b $2
	dc.b $F0, $A, $0, $0, $EC
	dc.b $F8, $6, $0, $9, $4
DATAKBWUH8984OJ_63: dc.b $3
	dc.b $E8, $A, $0, $0, $F5
	dc.b $0, $5, $0, $9, $F5
	dc.b $10, $8, $0, $D, $F5
DATAKBWUH8984OJ_64: dc.b $1
	dc.b $F1, $B, $0, $0, $F3
DATAKBWUH8984OJ_65: dc.b $2
	dc.b $EB, $B, $0, $0, $F4
	dc.b $B, $8, $0, $C, $F4
DATAKBWUH8984OJ_66: dc.b $3
	dc.b $E8, $8, $0, $0, $F4
	dc.b $F0, $4, $0, $3, $F4
	dc.b $F8, $B, $0, $5, $F4
DATAKBWUH8984OJ_67: dc.b $1
	dc.b $F0, $B, $0, $0, $F2
DATAKBWUH8984OJ_68: dc.b $2
	dc.b $E8, $0, $0, $0, $FA
	dc.b $F0, $B, $0, $1, $F2
DATAKBWUH8984OJ_69: dc.b $2
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
DATAKBWUH8984OJ_6A: dc.b $4
	dc.b $EC, $4, $0, $0, $F0
	dc.b $F4, $C, $0, $2, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $4, $0, $C, $F8
DATAKBWUH8984OJ_6B: dc.b $3
	dc.b $EC, $0, $0, $0, $FB
	dc.b $F4, $D, $0, $1, $EB
	dc.b $4, $8, $0, $9, $F3
DATAKBWUH8984OJ_6C: dc.b $3
	dc.b $F0, $0, $0, $0, $0
	dc.b $F8, $D, $0, $1, $F0
	dc.b $8, $8, $0, $9, $F0
DATAKBWUH8984OJ_6D: dc.b $2
	dc.b $F8, $6, $0, $0, $EC
	dc.b $F0, $B, $0, $6, $FC
DATAKBWUH8984OJ_6E: dc.b $3
	dc.b $F0, $0, $0, $0, $FC
	dc.b $F8, $A, $0, $1, $EC
	dc.b $F8, $5, $0, $A, $4
DATAKBWUH8984OJ_6F: dc.b $3
	dc.b $F0, $4, $0, $0, $F8
	dc.b $F8, $9, $0, $2, $F0
	dc.b $8, $C, $0, $8, $F0
DATAKBWUH8984OJ_70: dc.b $3
	dc.b $F0, $9, $0, $0, $F8
	dc.b $0, $C, $0, $6, $F0
	dc.b $8, $4, $0, $A, $0
DATAKBWUH8984OJ_71: dc.b $2
	dc.b $F0, $0, $0, $0, $0
	dc.b $F8, $E, $0, $1, $F0
DATAKBWUH8984OJ_72: dc.b $4
	dc.b $F0, $4, $0, $0, $F4
	dc.b $F8, $0, $0, $2, $EC
	dc.b $8, $0, $0, $3, $EC
	dc.b $F8, $E, $0, $4, $F4
DATAKBWUH8984OJ_73: dc.b $3
	dc.b $F0, $4, $0, $0, $FC
	dc.b $F8, $E, $0, $2, $EC
	dc.b $F8, $2, $0, $E, $C
DATAKBWUH8984OJ_74: dc.b $3
	dc.b $F0, $4, $0, $0, $F8
	dc.b $F8, $D, $0, $2, $F0
	dc.b $8, $8, $0, $A, $F8
DATAKBWUH8984OJ_75: dc.b $2
	dc.b $F0, $0, $0, $0, $F4
	dc.b $F8, $A, $0, $1, $F4
DATAKBWUH8984OJ_76: dc.b $3
	dc.b $F0, $8, $0, $0, $F0
	dc.b $F8, $D, $0, $3, $F0
	dc.b $8, $8, $0, $B, $F0
DATAKBWUH8984OJ_77: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATAKBWUH8984OJ_78: dc.b $4
	dc.b $E7, $C, $0, $0, $EE
	dc.b $EF, $8, $0, $4, $EE
	dc.b $F7, $D, $0, $7, $EE
	dc.b $7, $D, $0, $F, $F6
DATAKBWUH8984OJ_79: dc.b $4
	dc.b $E6, $4, $0, $0, $E9
	dc.b $EE, $E, $0, $2, $E1
	dc.b $F6, $6, $0, $E, $1
	dc.b $6, $8, $0, $14, $E9
DATAKBWUH8984OJ_7A: dc.b $3
	dc.b $F1, $8, $0, $0, $E6
	dc.b $F9, $E, $0, $3, $E6
	dc.b $E9, $7, $0, $F, $6
DATAKBWUH8984OJ_7B: dc.b $4
	dc.b $EE, $8, $0, $0, $F5
	dc.b $F6, $4, $0, $3, $FD
	dc.b $6, $1, $0, $5, $E5
	dc.b $FE, $F, $0, $7, $ED
DATAKBWUH8984OJ_7C: dc.b $4
	dc.b $12, $C, $18, $0, $F1
	dc.b $A, $8, $18, $4, $F9
	dc.b $FA, $D, $18, $7, $F1
	dc.b $EA, $D, $18, $F, $E9
DATAKBWUH8984OJ_7D: dc.b $4
	dc.b $13, $4, $18, $0, $4
	dc.b $FB, $E, $18, $2, $FC
	dc.b $F3, $6, $18, $E, $EC
	dc.b $F3, $8, $18, $14, $FC
DATAKBWUH8984OJ_7E: dc.b $3
	dc.b $7, $8, $18, $0, $1
	dc.b $EF, $E, $18, $3, $F9
	dc.b $F7, $7, $18, $F, $E9
DATAKBWUH8984OJ_7F: dc.b $4
	dc.b $C, $8, $18, $0, $F3
	dc.b $4, $4, $18, $3, $F3
	dc.b $EC, $1, $18, $5, $13
	dc.b $E4, $F, $18, $7, $F3
DATAKBWUH8984OJ_80: dc.b $4
	dc.b $E8, $E, $0, $0, $EF
	dc.b $E8, $0, $0, $C, $F
	dc.b $0, $4, $0, $D, $F7
	dc.b $8, $9, $0, $F, $EF
DATAKBWUH8984OJ_81: dc.b $4
	dc.b $E8, $C, $0, $0, $EE
	dc.b $F0, $D, $0, $4, $EE
	dc.b $0, $5, $0, $C, $F6
	dc.b $10, $8, $0, $10, $EE
DATAKBWUH8984OJ_82: dc.b $3
	dc.b $E8, $8, $0, $0, $F4
	dc.b $F0, $C, $0, $3, $EC
	dc.b $F8, $B, $0, $7, $F4
DATAKBWUH8984OJ_83: dc.b $4
	dc.b $E8, $0, $0, $0, $EA
	dc.b $E8, $D, $0, $1, $F2
	dc.b $F8, $8, $0, $9, $F2
	dc.b $0, $6, $0, $C, $FA
DATAKBWUH8984OJ_84: dc.b $3
	dc.b $E8, $E, $0, $0, $ED
	dc.b $0, $9, $0, $C, $F5
	dc.b $10, $4, $0, $12, $F5
DATAKBWUH8984OJ_85: dc.b $2
	dc.b $E8, $E, $0, $0, $EF
	dc.b $0, $6, $0, $C, $F7
DATAKBWUH8984OJ_86: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATAKBWUH8984OJ_87: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAKBWUH8984OJ_88: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAKBWUH8984OJ_89: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAKBWUH8984OJ_8A: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAKBWUH8984OJ_8B: dc.b $2
	dc.b $F8, $E, $0, $0, $F4
	dc.b $10, $8, $0, $C, $F4
DATAKBWUH8984OJ_8C: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F0, $2, $0, $C, $C
	dc.b $8, $8, $0, $F, $F4
DATAKBWUH8984OJ_8D: dc.b $3
	dc.b $EF, $E, $0, $0, $EC
	dc.b $EF, $2, $0, $C, $C
	dc.b $7, $8, $0, $F, $F4
DATAKBWUH8984OJ_8E: dc.b $2
	dc.b $E8, $B, $0, $0, $F1
	dc.b $8, $5, $0, $C, $F9
DATAKBWUH8984OJ_8F: dc.b $3
	dc.b $F1, $C, $0, $0, $E9
	dc.b $F9, $5, $0, $4, $E9
	dc.b $F9, $A, $0, $8, $F9
DATAKBWUH8984OJ_90: dc.b $4
	dc.b $E8, $9, $0, $0, $F0
	dc.b $F8, $C, $0, $6, $F0
	dc.b $0, $8, $0, $A, $F0
	dc.b $8, $9, $0, $D, $F8
DATAKBWUH8984OJ_91: dc.b $4
	dc.b $E6, $9, $0, $0, $F0
	dc.b $F6, $C, $0, $6, $F0
	dc.b $FE, $8, $0, $A, $F0
	dc.b $6, $D, $0, $D, $F8
DATAKBWUH8984OJ_92: dc.b $4
	dc.b $E8, $8, $0, $0, $F0
	dc.b $F0, $E, $0, $3, $F0
	dc.b $0, $0, $0, $F, $10
	dc.b $8, $4, $0, $10, $0
DATAKBWUH8984OJ_93: dc.b $2
	dc.b $E8, $8, $0, $0, $F0
	dc.b $F0, $E, $0, $3, $F0
DATAKBWUH8984OJ_94: dc.b $5
	dc.b $E8, $D, $0, $0, $F2
	dc.b $E8, $4, $0, $8, $F7
	dc.b $F0, $9, $0, $A, $F7
	dc.b $0, $5, $0, $10, $F7
	dc.b $10, $8, $0, $14, $F7
DATAKBWUH8984OJ_95: dc.b $5
	dc.b $E8, $8, $0, $0, $F6
	dc.b $E8, $4, $0, $3, $F7
	dc.b $F0, $9, $0, $5, $F7
	dc.b $0, $5, $0, $B, $F7
	dc.b $10, $8, $0, $F, $F7
DATAKBWUH8984OJ_96: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKBWUH8984OJ_97: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKBWUH8984OJ_98: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKBWUH8984OJ_99: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKBWUH8984OJ_9A: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAKBWUH8984OJ_9B: dc.b $2
	dc.b $EC, $0, $0, $0, $0
	dc.b $F4, $B, $0, $1, $F8
DATAKBWUH8984OJ_9C: dc.b $2
	dc.b $F4, $0, $0, $0, $3
	dc.b $FC, $E, $0, $1, $F3
DATAKBWUH8984OJ_9D: dc.b $4
	dc.b $EB, $A, $0, $0, $F5
	dc.b $F3, $1, $0, $9, $ED
	dc.b $3, $C, $0, $B, $F5
	dc.b $B, $8, $0, $F, $FD
DATAKBWUH8984OJ_9E: dc.b $4
	dc.b $EB, $A, $0, $0, $F6
	dc.b $F3, $1, $0, $9, $EE
	dc.b $3, $C, $0, $B, $F6
	dc.b $B, $8, $0, $F, $FE
DATAKBWUH8984OJ_9F: dc.b $4
	dc.b $EA, $8, $0, $0, $F9
	dc.b $F2, $D, $0, $3, $F1
	dc.b $2, $8, $0, $B, $F9
	dc.b $A, $4, $0, $E, $1
DATAKBWUH8984OJ_A0: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $E, $0, $3, $EF
	dc.b $C, $8, $0, $F, $F7
DATAKBWUH8984OJ_A1: dc.b $3
	dc.b $EC, $D, $0, $0, $EB
	dc.b $EC, $0, $0, $8, $B
	dc.b $FC, $A, $0, $9, $EB
DATAKBWUH8984OJ_A2: dc.b $4
	dc.b $E5, $0, $0, $0, $F4
	dc.b $ED, $E, $0, $1, $EC
	dc.b $ED, $0, $0, $D, $E4
	dc.b $5, $9, $0, $E, $EC
DATAKBWUH8984OJ_A3: dc.b $3
	dc.b $E4, $0, $0, $0, $FB
	dc.b $EC, $F, $0, $1, $EB
	dc.b $C, $8, $0, $11, $EB
DATAKBWUH8984OJ_A4: dc.b $4
	dc.b $EC, $8, $0, $0, $F2
	dc.b $F4, $E, $0, $3, $E2
	dc.b $F4, $1, $0, $F, $2
	dc.b $C, $8, $0, $11, $EA
DATAKBWUH8984OJ_A5: dc.b $3
	dc.b $EC, $F, $0, $0, $EB
	dc.b $4, $0, $0, $10, $E3
	dc.b $C, $8, $0, $11, $EB
DATAKBWUH8984OJ_A6: dc.b $4
	dc.b $ED, $8, $0, $0, $F2
	dc.b $F5, $E, $0, $3, $E2
	dc.b $F5, $1, $0, $F, $2
	dc.b $D, $8, $0, $11, $EA
DATAKBWUH8984OJ_A7: dc.b $3
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
	dc.b $F4, $0, $0, $13, $10
DATAKBWUH8984OJ_A8: dc.b $3
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $F, $0, $3, $F0
	dc.b $F4, $0, $0, $13, $10
DATAKBWUH8984OJ_A9: dc.b $3
	dc.b $EC, $4, $0, $0, $F8
	dc.b $F4, $F, $0, $2, $F0
	dc.b $F4, $0, $0, $12, $10
DATAKBWUH8984OJ_AA: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $0, $0, $C, $6
	dc.b $FC, $9, $0, $D, $6
DATAKBWUH8984OJ_AB: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $0, $0, $C, $6
	dc.b $FC, $9, $0, $D, $6
DATAKBWUH8984OJ_AC: dc.b $4
	dc.b $EC, $F, $0, $0, $EC
	dc.b $4, $0, $0, $10, $C
	dc.b $C, $4, $0, $11, $EC
	dc.b $C, $4, $0, $13, $4
DATAKBWUH8984OJ_AD: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $4, $0, $B, $F6
	dc.b $C, $8, $0, $D, $F6
DATAKBWUH8984OJ_AE: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $4, $0, $B, $F6
	dc.b $C, $8, $0, $D, $F6
DATAKBWUH8984OJ_AF: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $C, $0, $3, $E6
	dc.b $FC, $D, $0, $7, $EE
	dc.b $C, $8, $0, $F, $F6
DATAKBWUH8984OJ_B0: dc.b $2
	dc.b $EC, $D, $0, $0, $EA
	dc.b $FC, $A, $0, $8, $F2
DATAKBWUH8984OJ_B1: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $D, $0, $3, $EF
	dc.b $4, $9, $0, $B, $EF
DATAKBWUH8984OJ_B2: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $D, $0, $3, $EF
	dc.b $4, $9, $0, $B, $EF
DATAKBWUH8984OJ_B3: dc.b $3
	dc.b $EC, $8, $0, $0, $EF
	dc.b $F4, $D, $0, $3, $EF
	dc.b $4, $9, $0, $B, $EF
DATAKBWUH8984OJ_B4: dc.b $3
	dc.b $E6, $B, $0, $0, $F5
	dc.b $6, $8, $0, $C, $F5
	dc.b $E, $5, $0, $F, $F5
DATAKBWUH8984OJ_B5: dc.b $3
	dc.b $E6, $B, $0, $0, $F5
	dc.b $6, $8, $0, $C, $F5
	dc.b $E, $5, $0, $F, $F5
DATAKBWUH8984OJ_B6: dc.b $3
	dc.b $EC, $4, $0, $0, $FD
	dc.b $F4, $A, $0, $2, $F5
	dc.b $C, $C, $0, $B, $ED
DATAKBWUH8984OJ_B7: dc.b $3
	dc.b $EC, $4, $0, $0, $FD
	dc.b $F4, $A, $0, $2, $F5
	dc.b $C, $4, $0, $B, $F5
DATAKBWUH8984OJ_B8: dc.b $3
	dc.b $EC, $4, $0, $0, $FD
	dc.b $F4, $9, $0, $2, $F5
	dc.b $4, $D, $0, $8, $ED
DATAKBWUH8984OJ_B9: dc.b $3
	dc.b $EC, $4, $0, $0, $FD
	dc.b $F4, $A, $0, $2, $F5
	dc.b $C, $4, $0, $B, $F5
DATAKBWUH8984OJ_BA: dc.b $4
	dc.b $FC, $A, $0, $0, $F8
	dc.b $EC, $8, $0, $9, $F0
	dc.b $F4, $C, $0, $C, $F0
	dc.b $FC, $0, $0, $10, $F0
DATAKBWUH8984OJ_BB: dc.b $3
	dc.b $ED, $8, $0, $0, $EE
	dc.b $F5, $D, $0, $3, $EE
	dc.b $5, $9, $0, $B, $F6
DATAKBWUH8984OJ_BC: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $EE
	dc.b $C, $8, $0, $E, $F6
DATAKBWUH8984OJ_BD: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $EE
	dc.b $C, $8, $0, $E, $F6
DATAKBWUH8984OJ_BE: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $EE
	dc.b $C, $8, $0, $E, $F6
DATAKBWUH8984OJ_BF: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $EE
	dc.b $C, $8, $0, $E, $F6
DATAKBWUH8984OJ_C0: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $EE
	dc.b $C, $8, $0, $E, $F6
DATAKBWUH8984OJ_C1: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $C, $0, $C, $F3
DATAKBWUH8984OJ_C2: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $D, $0, $3, $F3
	dc.b $4, $8, $0, $B, $F3
	dc.b $C, $C, $0, $E, $F3
DATAKBWUH8984OJ_C3: dc.b $4
	dc.b $EC, $8, $0, $0, $ED
	dc.b $F4, $D, $0, $3, $ED
	dc.b $4, $8, $0, $B, $F5
	dc.b $C, $8, $0, $E, $F5
DATAKBWUH8984OJ_C4: dc.b $4
	dc.b $EE, $8, $0, $0, $ED
	dc.b $F6, $C, $0, $3, $E5
	dc.b $FE, $C, $0, $7, $ED
	dc.b $6, $9, $0, $B, $F5
DATAKBWUH8984OJ_C5: dc.b $3
	dc.b $EC, $E, $0, $0, $ED
	dc.b $4, $8, $0, $C, $F5
	dc.b $C, $8, $0, $F, $F5
DATAKBWUH8984OJ_C6: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $D, $0, $3, $EE
	dc.b $4, $8, $0, $B, $F6
	dc.b $C, $8, $0, $E, $F6
DATAKBWUH8984OJ_C7: dc.b $4
	dc.b $EC, $8, $0, $0, $F5
	dc.b $F4, $C, $0, $3, $ED
	dc.b $FC, $9, $0, $7, $F5
	dc.b $C, $8, $0, $D, $F5
DATAKBWUH8984OJ_C8: dc.b $3
	dc.b $F4, $A, $0, $0, $FB
	dc.b $FC, $4, $0, $9, $EB
	dc.b $4, $8, $0, $B, $E3
DATAKBWUH8984OJ_C9: dc.b $3
	dc.b $F4, $9, $0, $0, $F4
	dc.b $4, $C, $0, $6, $EC
	dc.b $4, $0, $0, $A, $C
DATAKBWUH8984OJ_CA: dc.b $2
	dc.b $F4, $9, $0, $0, $F7
	dc.b $4, $C, $0, $6, $EF
DATAKBWUH8984OJ_CB: dc.b $3
	dc.b $F4, $9, $8, $0, $F3
	dc.b $4, $C, $8, $6, $F3
	dc.b $4, $0, $8, $A, $EB
DATAKBWUH8984OJ_CC: dc.b $3
	dc.b $F4, $A, $8, $0, $EE
	dc.b $FC, $4, $8, $9, $6
	dc.b $4, $8, $8, $B, $6
DATAKBWUH8984OJ_CD: dc.b $2
	dc.b $F4, $E, $0, $0, $F2
	dc.b $4, $0, $0, $C, $EA
DATAKBWUH8984OJ_CE: dc.b $2
	dc.b $F4, $9, $0, $0, $F7
	dc.b $4, $C, $0, $6, $EF
DATAKBWUH8984OJ_CF: dc.b $2
	dc.b $F4, $E, $8, $0, $EF
	dc.b $4, $0, $8, $C, $F
DATAKBWUH8984OJ_D0: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F8, $2, $0, $C, $C
	dc.b $10, $8, $0, $F, $F4
DATAKBWUH8984OJ_D1: dc.b $3
	dc.b $F7, $E, $0, $0, $EC
	dc.b $F7, $2, $0, $C, $C
	dc.b $F, $8, $0, $F, $F4
DATAKBWUH8984OJ_D2: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAKBWUH8984OJ_D3: dc.b $3
	dc.b $E8, $9, $0, $0, $F3
	dc.b $F8, $D, $0, $6, $F3
	dc.b $8, $9, $0, $E, $F3
DATAKBWUH8984OJ_D4: dc.b $2
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $9, $0, $10, $F0
DATAKBWUH8984OJ_D5: dc.b $3
	dc.b $E8, $A, $0, $0, $F0
	dc.b $0, $C, $0, $9, $F0
	dc.b $8, $9, $0, $D, $F0
DATAKBWUH8984OJ_D6: dc.b $3
	dc.b $EC, $A, $0, $0, $ED
	dc.b $4, $D, $0, $9, $F4
	dc.b $FC, $4, $0, $11, $5
	even