; Sprite mappings - generated by Flex - Sonic 1 format

_Mapping69:
	dc.w 0, WQE_Frame1-_Mapping69
	dc.w URH_Frame2-_Mapping69, YVZ_Frame3-_Mapping69
	dc.w YLA_Frame4-_Mapping69, OPJ_Frame5-_Mapping69
	dc.w PKW_Frame6-_Mapping69, QDU_Frame7-_Mapping69
	dc.w QXT_Frame8-_Mapping69, KBR_Frame9-_Mapping69
	dc.w OZX_FrameA-_Mapping69, FDF_FrameB-_Mapping69
	dc.w TSM_FrameC-_Mapping69, CIF_FrameD-_Mapping69
	dc.w YEV_FrameE-_Mapping69, KWB_FrameF-_Mapping69
	dc.w REJ_Frame10-_Mapping69, JPB_Frame11-_Mapping69
	dc.w KJO_Frame12-_Mapping69, EWP_Frame13-_Mapping69
	dc.w HHF_Frame14-_Mapping69, NOY_Frame15-_Mapping69
	dc.w OTA_Frame16-_Mapping69, HZV_Frame17-_Mapping69
	dc.w GGN_Frame18-_Mapping69, YSH_Frame19-_Mapping69
	dc.w LYP_Frame1A-_Mapping69, WUV_Frame1B-_Mapping69
	dc.w RUT_Frame1C-_Mapping69, INA_Frame1D-_Mapping69
	dc.w ZMC_Frame1E-_Mapping69, TCR_Frame1F-_Mapping69
	dc.w HVU_Frame20-_Mapping69, LCC_Frame21-_Mapping69
	dc.w RZF_Frame22-_Mapping69, IAS_Frame23-_Mapping69
	dc.w BTW_Frame24-_Mapping69, VVO_Frame25-_Mapping69
	dc.w DJN_Frame26-_Mapping69, WQJ_Frame27-_Mapping69
	dc.w PWP_Frame28-_Mapping69, AFI_Frame29-_Mapping69
	dc.w KGA_Frame2A-_Mapping69, POC_Frame2B-_Mapping69
	dc.w URK_Frame2C-_Mapping69, OUF_Frame2D-_Mapping69
	dc.w BUL_Frame2E-_Mapping69, XBU_Frame2F-_Mapping69
	dc.w CMZ_Frame30-_Mapping69, VIB_Frame31-_Mapping69
	dc.w GFI_Frame32-_Mapping69, FQY_Frame33-_Mapping69
	dc.w GZW_Frame34-_Mapping69, VLQ_Frame35-_Mapping69
	dc.w VWM_Frame36-_Mapping69, ZIJ_Frame37-_Mapping69
	dc.w LGQ_Frame38-_Mapping69, XBQ_Frame39-_Mapping69
	dc.w YOC_Frame3A-_Mapping69, KHG_Frame3B-_Mapping69
	dc.w XVF_Frame3C-_Mapping69, KDV_Frame3D-_Mapping69
	dc.w QMV_Frame3E-_Mapping69, FIE_Frame3F-_Mapping69
	dc.w UDR_Frame40-_Mapping69, OKV_Frame41-_Mapping69
	dc.w BBK_Frame42-_Mapping69, UXS_Frame43-_Mapping69
	dc.w SVI_Frame44-_Mapping69, YVB_Frame45-_Mapping69
	dc.w JON_Frame46-_Mapping69, NBN_Frame47-_Mapping69
	dc.w CCM_Frame48-_Mapping69, EDK_Frame49-_Mapping69
	dc.w IJD_Frame4A-_Mapping69, SRZ_Frame4B-_Mapping69
	dc.w HYW_Frame4C-_Mapping69, NOT_Frame4D-_Mapping69
	dc.w PIV_Frame4E-_Mapping69, JVF_Frame4F-_Mapping69
	dc.w CDJ_Frame50-_Mapping69, AOE_Frame51-_Mapping69
	dc.w GWE_Frame52-_Mapping69, XFT_Frame53-_Mapping69
	dc.w EQS_Frame54-_Mapping69, FKO_Frame55-_Mapping69
	dc.w VOH_Frame56-_Mapping69, NVD_Frame57-_Mapping69
	dc.w SQX_Frame58-_Mapping69, MFS_Frame59-_Mapping69
	dc.w XXL_Frame5A-_Mapping69, JAK_Frame5B-_Mapping69
	dc.w DZW_Frame5C-_Mapping69, RCW_Frame5D-_Mapping69
	dc.w XCO_Frame5E-_Mapping69, MFM_Frame5F-_Mapping69
	dc.w CXD_Frame60-_Mapping69, ZUX_Frame61-_Mapping69
	dc.w WYD_Frame62-_Mapping69, QDH_Frame63-_Mapping69
	dc.w BFO_Frame64-_Mapping69, LWZ_Frame65-_Mapping69
	dc.w DPX_Frame66-_Mapping69, PYP_Frame67-_Mapping69
	dc.w PFL_Frame68-_Mapping69, DAL_Frame69-_Mapping69
	dc.w VTS_Frame6A-_Mapping69, AZC_Frame6B-_Mapping69
	dc.w IZF_Frame6C-_Mapping69, UZH_Frame6D-_Mapping69
	dc.w ZGS_Frame6E-_Mapping69, QLH_Frame6F-_Mapping69
	dc.w NJB_Frame70-_Mapping69, COJ_Frame71-_Mapping69
	dc.w KRP_Frame72-_Mapping69, UGX_Frame73-_Mapping69
	dc.w SCC_Frame74-_Mapping69, IUV_Frame75-_Mapping69
	dc.w HJY_Frame76-_Mapping69, FBQ_Frame77-_Mapping69
	dc.w AFH_Frame78-_Mapping69, ECD_Frame79-_Mapping69
	dc.w NAP_Frame7A-_Mapping69, QGR_Frame7B-_Mapping69
	dc.w VPD_Frame7C-_Mapping69, FRK_Frame7D-_Mapping69
	dc.w JLF_Frame7E-_Mapping69, IGH_Frame7F-_Mapping69
	dc.w OKP_Frame80-_Mapping69, SXC_Frame81-_Mapping69
	dc.w QMN_Frame82-_Mapping69, ORQ_Frame83-_Mapping69
	dc.w QJK_Frame84-_Mapping69, JKB_Frame85-_Mapping69
	dc.w SYW_Frame86-_Mapping69, XHO_Frame87-_Mapping69
	dc.w REV_Frame88-_Mapping69, LFN_Frame89-_Mapping69
	dc.w BKU_Frame8A-_Mapping69, BTB_Frame8B-_Mapping69
	dc.w PVS_Frame8C-_Mapping69, RRB_Frame8D-_Mapping69
	dc.w CDF_Frame8E-_Mapping69, TAB_Frame8F-_Mapping69
	dc.w IBL_Frame90-_Mapping69, JUH_Frame91-_Mapping69
	dc.w FXO_Frame92-_Mapping69, HGZ_Frame93-_Mapping69
	dc.w ETR_Frame94-_Mapping69, RAG_Frame95-_Mapping69
	dc.w HWA_Frame96-_Mapping69, LJJ_Frame97-_Mapping69
	dc.w HGY_Frame98-_Mapping69, BQE_Frame99-_Mapping69
	dc.w AOV_Frame9A-_Mapping69, ZBG_Frame9B-_Mapping69
	dc.w AET_Frame9C-_Mapping69, BYP_Frame9D-_Mapping69
	dc.w SSD_Frame9E-_Mapping69, KFI_Frame9F-_Mapping69
	dc.w VGB_FrameA0-_Mapping69, GOZ_FrameA1-_Mapping69
	dc.w VVG_FrameA2-_Mapping69, OLW_FrameA3-_Mapping69
	dc.w DRQ_FrameA4-_Mapping69, ZWJ_FrameA5-_Mapping69
	dc.w TEF_FrameA6-_Mapping69, OML_FrameA7-_Mapping69
	dc.w BPX_FrameA8-_Mapping69, EVZ_FrameA9-_Mapping69
	dc.w YWJ_FrameAA-_Mapping69, OTM_FrameAB-_Mapping69
	dc.w QVZ_FrameAC-_Mapping69, RQN_FrameAD-_Mapping69
	dc.w CJN_FrameAE-_Mapping69, WJH_FrameAF-_Mapping69
	dc.w QLJ_FrameB0-_Mapping69, LEF_FrameB1-_Mapping69
	dc.w VWT_FrameB2-_Mapping69, NQA_FrameB3-_Mapping69
	dc.w KRF_FrameB4-_Mapping69, FIF_FrameB5-_Mapping69
	dc.w YWS_FrameB6-_Mapping69, MTV_FrameB7-_Mapping69
	dc.w YZX_FrameB8-_Mapping69, LYM_FrameB9-_Mapping69
	dc.w EMH_FrameBA-_Mapping69, REZ_FrameBB-_Mapping69
	dc.w MDG_FrameBC-_Mapping69, HRI_FrameBD-_Mapping69
	dc.w GBR_FrameBE-_Mapping69, CGK_FrameBF-_Mapping69
	dc.w EZE_FrameC0-_Mapping69, CVO_FrameC1-_Mapping69
	dc.w EPK_FrameC2-_Mapping69, RVF_FrameC3-_Mapping69
	dc.w LDS_FrameC4-_Mapping69, MCB_FrameC5-_Mapping69
	dc.w BLC_FrameC6-_Mapping69, JLT_FrameC7-_Mapping69
	dc.w GHK_FrameC8-_Mapping69, SWY_FrameC9-_Mapping69
	dc.w SJE_FrameCA-_Mapping69, BIS_FrameCB-_Mapping69
	dc.w TMX_FrameCC-_Mapping69, SZF_FrameCD-_Mapping69
	dc.w XTS_FrameCE-_Mapping69, NYQ_FrameCF-_Mapping69
	dc.w KOK_FrameD0-_Mapping69, CSF_FrameD1-_Mapping69
	dc.w AZI_FrameD2-_Mapping69, TWL_FrameD3-_Mapping69
	dc.w ADY_FrameD4-_Mapping69, AHN_FrameD5-_Mapping69
	dc.w ZPK_FrameD6-_Mapping69, JDN_FrameD7-_Mapping69
	dc.w BSG_FrameD8-_Mapping69, BJD_FrameD9-_Mapping69
	dc.w SWS_FrameDA-_Mapping69, LQY_FrameDB-_Mapping69
	dc.w RPZ_FrameDC-_Mapping69, XLP_FrameDD-_Mapping69
	dc.w AJA_FrameDE-_Mapping69

WQE_Frame1: dc.b  $3
	dc.b  $EC, $D, $0, $0, $EC
	dc.b  $FC, $6, $0, $8, $4
	dc.b  $FC, $A, $0, $E, $EC
URH_Frame2: dc.b  $3
	dc.b  $FD, $E, $0, $0, $EC
	dc.b  $5, $1, $0, $C, $C
	dc.b  $ED, $D, $0, $E, $EC
YVZ_Frame3: dc.b  $3
	dc.b  $FE, $A, $0, $0, $F4
	dc.b  $F6, $C, $0, $9, $EC
	dc.b  $EE, $8, $0, $D, $F4
YLA_Frame4: dc.b  $2
	dc.b  $FC, $E, $0, $0, $EE
	dc.b  $EC, $9, $0, $C, $F4
OPJ_Frame5: dc.b  $3
	dc.b  $FC, $E, $0, $0, $EE
	dc.b  $FC, $1, $0, $C, $E
	dc.b  $EC, $9, $0, $E, $F4
PKW_Frame6: dc.b  $3
	dc.b  $FD, $E, $0, $0, $ED
	dc.b  $5, $1, $0, $C, $D
	dc.b  $ED, $9, $0, $E, $F4
QDU_Frame7: dc.b  $3
	dc.b  $FE, $A, $0, $0, $F4
	dc.b  $F6, $C, $0, $9, $EC
	dc.b  $EE, $8, $0, $D, $F4
QXT_Frame8: dc.b  $2
	dc.b  $FC, $A, $0, $0, $F4
	dc.b  $EC, $D, $0, $9, $EC
KBR_Frame9: dc.b  $4
	dc.b  $FD, $B, $0, $0, $FB
	dc.b  $ED, $D, $0, $C, $EB
	dc.b  $F5, $0, $0, $14, $B
	dc.b  $FD, $5, $0, $15, $EB
OZX_FrameA: dc.b  $4
	dc.b  $2, $E, $0, $0, $FC
	dc.b  $F2, $D, $0, $C, $EC
	dc.b  $FA, $4, $0, $14, $C
	dc.b  $2, $4, $0, $16, $EC
FDF_FrameB: dc.b  $4
	dc.b  $FB, $A, $0, $0, $FD
	dc.b  $EB, $4, $0, $9, $F5
	dc.b  $F3, $C, $0, $B, $ED
	dc.b  $FB, $5, $0, $F, $ED
TSM_FrameC: dc.b  $4
	dc.b  $FD, $E, $0, $0, $FC
	dc.b  $ED, $D, $0, $C, $EC
	dc.b  $FD, $4, $0, $14, $EC
	dc.b  $5, $0, $0, $16, $F4
CIF_FrameD: dc.b  $4
	dc.b  $FE, $B, $0, $0, $FC
	dc.b  $EE, $D, $0, $C, $EC
	dc.b  $EE, $1, $0, $14, $C
	dc.b  $FE, $6, $0, $16, $EC
YEV_FrameE: dc.b  $4
	dc.b  $FC, $F, $0, $0, $FB
	dc.b  $EC, $9, $0, $10, $EB
	dc.b  $F4, $8, $0, $16, $3
	dc.b  $FC, $5, $0, $19, $EB
KWB_FrameF: dc.b  $4
	dc.b  $FF, $A, $0, $0, $FA
	dc.b  $EF, $D, $0, $9, $EA
	dc.b  $FF, $4, $0, $11, $EA
	dc.b  $7, $0, $0, $13, $F2
REJ_Frame10: dc.b  $4
	dc.b  $FE, $A, $0, $0, $FC
	dc.b  $EE, $8, $0, $9, $EC
	dc.b  $F6, $C, $0, $C, $EC
	dc.b  $FE, $5, $0, $10, $EC
JPB_Frame11: dc.b  $3
	dc.b  $ED, $9, $0, $0, $FC
	dc.b  $FD, $A, $0, $6, $FC
	dc.b  $F5, $7, $0, $F, $EC
KJO_Frame12: dc.b  $3
	dc.b  $F5, $B, $0, $0, $FC
	dc.b  $ED, $4, $0, $C, $4
	dc.b  $F5, $7, $0, $E, $EC
EWP_Frame13: dc.b  $3
	dc.b  $F5, $A, $0, $0, $FC
	dc.b  $F5, $6, $0, $9, $EC
	dc.b  $D, $0, $0, $F, $F4
HHF_Frame14: dc.b  $2
	dc.b  $F3, $B, $0, $0, $FC
	dc.b  $F3, $7, $0, $C, $EC
NOY_Frame15: dc.b  $3
	dc.b  $EB, $4, $0, $0, $FC
	dc.b  $F3, $B, $0, $2, $FC
	dc.b  $F3, $7, $0, $E, $EC
OTA_Frame16: dc.b  $4
	dc.b  $EC, $4, $0, $0, $4
	dc.b  $F4, $B, $0, $2, $FC
	dc.b  $F4, $6, $0, $E, $EC
	dc.b  $C, $0, $0, $14, $F4
HZV_Frame17: dc.b  $3
	dc.b  $F5, $A, $0, $0, $FC
	dc.b  $F5, $6, $0, $9, $EC
	dc.b  $D, $0, $0, $F, $F4
GGN_Frame18: dc.b  $2
	dc.b  $F5, $A, $0, $0, $FC
	dc.b  $F5, $7, $0, $9, $EC
YSH_Frame19: dc.b  $4
	dc.b  $EF, $E, $0, $0, $FE
	dc.b  $EF, $6, $0, $C, $EE
	dc.b  $7, $C, $0, $12, $EE
	dc.b  $F, $8, $0, $16, $EE
LYP_Frame1A: dc.b  $4
	dc.b  $E7, $B, $0, $0, $0
	dc.b  $E7, $1, $0, $C, $F8
	dc.b  $F7, $5, $0, $E, $F0
	dc.b  $7, $9, $0, $12, $F0
WUV_Frame1B: dc.b  $4
	dc.b  $EF, $A, $0, $0, $FD
	dc.b  $F7, $5, $0, $9, $ED
	dc.b  $7, $C, $0, $D, $ED
	dc.b  $F, $4, $0, $11, $F5
RUT_Frame1C: dc.b  $4
	dc.b  $E7, $B, $0, $0, $0
	dc.b  $F7, $5, $0, $C, $F0
	dc.b  $7, $C, $0, $10, $F0
	dc.b  $F, $8, $0, $14, $F0
INA_Frame1D: dc.b  $4
	dc.b  $EE, $E, $0, $0, $FF
	dc.b  $EE, $6, $0, $C, $EF
	dc.b  $6, $D, $0, $12, $EF
	dc.b  $6, $0, $0, $1A, $F
ZMC_Frame1E: dc.b  $4
	dc.b  $E8, $F, $0, $0, $FF
	dc.b  $E8, $2, $0, $10, $F7
	dc.b  $0, $4, $0, $13, $EF
	dc.b  $8, $D, $0, $15, $EF
TCR_Frame1F: dc.b  $4
	dc.b  $EE, $A, $0, $0, $FE
	dc.b  $F6, $5, $0, $9, $EE
	dc.b  $6, $C, $0, $D, $EE
	dc.b  $E, $8, $0, $11, $EE
HVU_Frame20: dc.b  $4
	dc.b  $EE, $A, $0, $0, $FE
	dc.b  $F6, $5, $0, $9, $EE
	dc.b  $6, $C, $0, $D, $EE
	dc.b  $E, $8, $0, $11, $EE
LCC_Frame21: dc.b  $2
	dc.b  $EC, $8, $0, $0, $F8
	dc.b  $F4, $F, $0, $3, $F0
RZF_Frame22: dc.b  $2
	dc.b  $EC, $8, $0, $0, $F8
	dc.b  $F4, $F, $0, $3, $F0
IAS_Frame23: dc.b  $2
	dc.b  $EC, $8, $0, $0, $F8
	dc.b  $F4, $F, $0, $3, $F0
BTW_Frame24: dc.b  $2
	dc.b  $EC, $8, $0, $0, $F8
	dc.b  $F4, $F, $0, $3, $F0
VVO_Frame25: dc.b  $4
	dc.b  $EF, $E, $0, $0, $ED
	dc.b  $FF, $0, $0, $C, $D
	dc.b  $7, $C, $0, $D, $F5
	dc.b  $F, $8, $0, $11, $F5
DJN_Frame26: dc.b  $2
	dc.b  $EE, $8, $0, $0, $F0
	dc.b  $F6, $F, $0, $3, $F0
WQJ_Frame27: dc.b  $4
	dc.b  $EF, $E, $0, $0, $ED
	dc.b  $FF, $0, $0, $C, $D
	dc.b  $7, $C, $0, $D, $F5
	dc.b  $F, $8, $0, $11, $F5
PWP_Frame28: dc.b  $2
	dc.b  $EE, $8, $0, $0, $F0
	dc.b  $F6, $F, $0, $3, $F0
AFI_Frame29: dc.b  $2
	dc.b  $F0, $2, $0, $0, $EC
	dc.b  $F0, $F, $0, $3, $F4
KGA_Frame2A: dc.b  $2
	dc.b  $F0, $2, $0, $0, $EC
	dc.b  $F0, $F, $0, $3, $F4
POC_Frame2B: dc.b  $2
	dc.b  $F0, $2, $0, $0, $EC
	dc.b  $F0, $F, $0, $3, $F4
URK_Frame2C: dc.b  $2
	dc.b  $F0, $2, $0, $0, $EC
	dc.b  $F0, $F, $0, $3, $F4
OUF_Frame2D: dc.b  $3
	dc.b  $EA, $4, $0, $0, $FE
	dc.b  $F2, $B, $0, $2, $EE
	dc.b  $F2, $6, $0, $E, $6
BUL_Frame2E: dc.b  $2
	dc.b  $F7, $2, $0, $0, $ED
	dc.b  $EF, $F, $0, $3, $F5
XBU_Frame2F: dc.b  $3
	dc.b  $EA, $4, $0, $0, $FE
	dc.b  $F2, $B, $0, $2, $EE
	dc.b  $F2, $6, $0, $E, $6
CMZ_Frame30: dc.b  $2
	dc.b  $F7, $2, $0, $0, $ED
	dc.b  $EF, $F, $0, $3, $F5
VIB_Frame31: dc.b  $3
	dc.b  $EC, $8, $0, $0, $F2
	dc.b  $F4, $E, $0, $3, $F2
	dc.b  $C, $8, $0, $F, $F2
GFI_Frame32: dc.b  $4
	dc.b  $EA, $9, $0, $0, $F3
	dc.b  $FA, $C, $0, $6, $F3
	dc.b  $2, $8, $0, $A, $F3
	dc.b  $A, $4, $0, $D, $FB
FQY_Frame33: dc.b  $4
	dc.b  $F0, $4, $0, $0, $F9
	dc.b  $F8, $8, $0, $2, $F1
	dc.b  $0, $C, $0, $5, $F1
	dc.b  $8, $4, $0, $9, $F9
GZW_Frame34: dc.b  $4
	dc.b  $EF, $8, $0, $0, $F9
	dc.b  $F7, $C, $0, $3, $F1
	dc.b  $FF, $8, $0, $7, $F1
	dc.b  $7, $C, $0, $A, $F1
VLQ_Frame35: dc.b  $4
	dc.b  $EF, $4, $0, $0, $F4
	dc.b  $F7, $8, $0, $2, $F4
	dc.b  $FF, $C, $0, $5, $F4
	dc.b  $7, $8, $0, $9, $F4
VWM_Frame36: dc.b  $3
	dc.b  $EA, $4, $0, $0, $F9
	dc.b  $F2, $D, $0, $2, $F1
	dc.b  $2, $9, $0, $A, $F1
ZIJ_Frame37: dc.b  $2
	dc.b  $EC, $F, $0, $0, $F0
	dc.b  $C, $8, $0, $10, $F0
LGQ_Frame38: dc.b  $2
	dc.b  $EE, $B, $0, $0, $F4
	dc.b  $E, $0, $0, $C, $FC
XBQ_Frame39: dc.b  $3
	dc.b  $EE, $4, $0, $0, $F0
	dc.b  $F6, $D, $0, $2, $F0
	dc.b  $6, $8, $0, $A, $F0
YOC_Frame3A: dc.b  $4
	dc.b  $F0, $8, $0, $0, $F5
	dc.b  $F8, $C, $0, $3, $ED
	dc.b  $0, $8, $0, $7, $F5
	dc.b  $8, $4, $0, $A, $F5
KHG_Frame3B: dc.b  $2
	dc.b  $EC, $A, $0, $0, $F4
	dc.b  $4, $5, $0, $9, $FC
XVF_Frame3C: dc.b  $2
	dc.b  $EC, $B, $0, $0, $F4
	dc.b  $C, $8, $0, $C, $F4
KDV_Frame3D: dc.b  $3
	dc.b  $E6, $0, $0, $0, $FA
	dc.b  $EE, $B, $0, $1, $F2
	dc.b  $E, $8, $0, $D, $F2
QMV_Frame3E: dc.b  $1
	dc.b  $F0, $B, $0, $0, $F3
FIE_Frame3F: dc.b  $3
	dc.b  $F1, $8, $0, $0, $EF
	dc.b  $F9, $D, $0, $3, $EF
	dc.b  $9, $4, $0, $B, $F7
UDR_Frame40: dc.b  $4
	dc.b  $F2, $8, $0, $0, $F8
	dc.b  $FA, $C, $0, $3, $F0
	dc.b  $2, $8, $0, $7, $F0
	dc.b  $A, $4, $0, $A, $F8
OKV_Frame41: dc.b  $4
	dc.b  $EF, $9, $0, $0, $F8
	dc.b  $FF, $C, $0, $6, $F0
	dc.b  $7, $8, $0, $A, $F0
	dc.b  $F, $4, $0, $D, $F8
BBK_Frame42: dc.b  $4
	dc.b  $EC, $9, $0, $0, $F8
	dc.b  $FC, $8, $0, $6, $F0
	dc.b  $4, $C, $0, $9, $F0
	dc.b  $C, $8, $0, $D, $F0
UXS_Frame43: dc.b  $2
	dc.b  $EC, $B, $0, $0, $F5
	dc.b  $C, $8, $0, $C, $F5
SVI_Frame44: dc.b  $1
	dc.b  $F0, $B, $0, $0, $F4
YVB_Frame45: dc.b  $2
	dc.b  $F6, $D, $0, $0, $F2
	dc.b  $6, $8, $0, $8, $F2
JON_Frame46: dc.b  $1
	dc.b  $F3, $B, $0, $0, $F3
NBN_Frame47: dc.b  $2
	dc.b  $EB, $4, $0, $0, $FB
	dc.b  $F3, $B, $0, $2, $F3
CCM_Frame48: dc.b  $3
	dc.b  $EC, $8, $0, $0, $F0
	dc.b  $F4, $D, $0, $3, $F0
	dc.b  $4, $9, $0, $B, $F8
EDK_Frame49: dc.b  $4
	dc.b  $E8, $A, $0, $0, $FC
	dc.b  $F0, $5, $0, $9, $EC
	dc.b  $0, $C, $0, $D, $EC
	dc.b  $8, $8, $0, $11, $F4
IJD_Frame4A: dc.b  $4
	dc.b  $EA, $8, $0, $0, $FA
	dc.b  $F2, $D, $0, $3, $F2
	dc.b  $2, $8, $0, $B, $F2
	dc.b  $A, $5, $0, $E, $F2
SRZ_Frame4B: dc.b  $3
	dc.b  $EB, $9, $0, $0, $F8
	dc.b  $FB, $C, $0, $6, $F0
	dc.b  $3, $8, $0, $A, $F8
HYW_Frame4C: dc.b  $3
	dc.b  $F1, $8, $0, $0, $F3
	dc.b  $F9, $D, $0, $3, $F3
	dc.b  $9, $8, $0, $B, $F3
NOT_Frame4D: dc.b  $3
	dc.b  $EE, $4, $0, $0, $FB
	dc.b  $F6, $D, $0, $2, $F3
	dc.b  $6, $4, $0, $A, $FB
PIV_Frame4E: dc.b  $1
	dc.b  $F2, $F, $0, $0, $EE
JVF_Frame4F: dc.b  $4
	dc.b  $EA, $0, $0, $0, $2
	dc.b  $F2, $D, $0, $1, $F2
	dc.b  $FA, $0, $0, $9, $EA
	dc.b  $2, $D, $0, $A, $EA
CDJ_Frame50: dc.b  $4
	dc.b  $EC, $4, $0, $0, $FB
	dc.b  $F4, $8, $0, $2, $F3
	dc.b  $FC, $A, $0, $5, $EB
	dc.b  $FC, $5, $0, $E, $3
AOE_Frame51: dc.b  $2
	dc.b  $ED, $4, $0, $0, $FF
	dc.b  $F5, $E, $0, $2, $EF
GWE_Frame52: dc.b  $3
	dc.b  $EF, $4, $0, $0, $FA
	dc.b  $F7, $D, $0, $2, $F2
	dc.b  $7, $4, $0, $A, $FA
XFT_Frame53: dc.b  $3
	dc.b  $ED, $0, $0, $0, $0
	dc.b  $F5, $A, $0, $1, $F8
	dc.b  $FD, $4, $0, $A, $E8
EQS_Frame54: dc.b  $2
	dc.b  $F0, $F, $0, $0, $EF
	dc.b  $F8, $0, $0, $10, $F
FKO_Frame55: dc.b  $4
	dc.b  $EC, $8, $0, $0, $F0
	dc.b  $F4, $D, $0, $3, $F0
	dc.b  $4, $8, $0, $B, $F0
	dc.b  $C, $8, $0, $E, $F8
VOH_Frame56: dc.b  $3
	dc.b  $EC, $8, $0, $0, $EF
	dc.b  $F4, $D, $0, $3, $EF
	dc.b  $4, $9, $0, $B, $F7
NVD_Frame57: dc.b  $2
	dc.b  $EC, $B, $0, $0, $F0
	dc.b  $C, $C, $0, $C, $F0
SQX_Frame58: dc.b  $2
	dc.b  $EC, $B, $0, $0, $F3
	dc.b  $C, $8, $0, $C, $F3
MFS_Frame59: dc.b  $4
	dc.b  $EC, $8, $0, $0, $F7
	dc.b  $F4, $C, $0, $3, $EF
	dc.b  $FC, $8, $0, $7, $F7
	dc.b  $4, $D, $0, $A, $EF
XXL_Frame5A: dc.b  $3
	dc.b  $EC, $A, $0, $0, $F6
	dc.b  $4, $C, $0, $9, $EE
	dc.b  $C, $8, $0, $D, $F6
JAK_Frame5B: dc.b  $2
	dc.b  $EC, $B, $0, $0, $F3
	dc.b  $C, $8, $0, $C, $F3
DZW_Frame5C: dc.b  $3
	dc.b  $F5, $A, $0, $0, $EC
	dc.b  $F5, $9, $0, $9, $4
	dc.b  $5, $0, $0, $F, $14
RCW_Frame5D: dc.b  $1
	dc.b  $F4, $E, $0, $0, $FC
XCO_Frame5E: dc.b  $2
	dc.b  $F4, $E, $0, $0, $E2
	dc.b  $F4, $2, $0, $C, $2
MFM_Frame5F: dc.b  $3
	dc.b  $F5, $5, $0, $0, $E5
	dc.b  $F5, $E, $0, $4, $F5
	dc.b  $5, $0, $0, $10, $E5
CXD_Frame60: dc.b  $1
	dc.b  $F4, $E, $0, $0, $F6
ZUX_Frame61: dc.b  $2
	dc.b  $FC, $0, $0, $0, $DA
	dc.b  $F4, $E, $0, $1, $E2
WYD_Frame62: dc.b  $2
	dc.b  $F8, $A, $0, $0, $EC
	dc.b  $0, $6, $0, $9, $4
QDH_Frame63: dc.b  $3
	dc.b  $E8, $A, $0, $0, $F5
	dc.b  $0, $5, $0, $9, $F5
	dc.b  $10, $8, $0, $D, $F5
BFO_Frame64: dc.b  $1
	dc.b  $F1, $B, $0, $0, $F3
LWZ_Frame65: dc.b  $2
	dc.b  $EB, $B, $0, $0, $F4
	dc.b  $B, $8, $0, $C, $F4
DPX_Frame66: dc.b  $3
	dc.b  $E8, $8, $0, $0, $F4
	dc.b  $F0, $4, $0, $3, $F4
	dc.b  $F8, $B, $0, $5, $F4
PYP_Frame67: dc.b  $1
	dc.b  $F0, $B, $0, $0, $F2
PFL_Frame68: dc.b  $2
	dc.b  $E8, $0, $0, $0, $FA
	dc.b  $F0, $B, $0, $1, $F2
DAL_Frame69: dc.b  $2
	dc.b  $EC, $B, $0, $0, $F0
	dc.b  $C, $8, $0, $C, $F8
VTS_Frame6A: dc.b  $4
	dc.b  $EC, $4, $0, $0, $F0
	dc.b  $F4, $C, $0, $2, $F0
	dc.b  $FC, $9, $0, $6, $F0
	dc.b  $C, $4, $0, $C, $F8
AZC_Frame6B: dc.b  $3
	dc.b  $EC, $0, $0, $0, $FB
	dc.b  $F4, $D, $0, $1, $EB
	dc.b  $4, $8, $0, $9, $F3
IZF_Frame6C: dc.b  $3
	dc.b  $F0, $0, $0, $0, $0
	dc.b  $F8, $D, $0, $1, $F0
	dc.b  $8, $8, $0, $9, $F0
UZH_Frame6D: dc.b  $2
	dc.b  $F8, $6, $0, $0, $EC
	dc.b  $F0, $B, $0, $6, $FC
ZGS_Frame6E: dc.b  $3
	dc.b  $F0, $0, $0, $0, $FC
	dc.b  $F8, $A, $0, $1, $EC
	dc.b  $F8, $5, $0, $A, $4
QLH_Frame6F: dc.b  $3
	dc.b  $F0, $4, $0, $0, $F8
	dc.b  $F8, $9, $0, $2, $F0
	dc.b  $8, $C, $0, $8, $F0
NJB_Frame70: dc.b  $3
	dc.b  $F0, $9, $0, $0, $F8
	dc.b  $0, $C, $0, $6, $F0
	dc.b  $8, $4, $0, $A, $0
COJ_Frame71: dc.b  $2
	dc.b  $F0, $0, $0, $0, $0
	dc.b  $F8, $E, $0, $1, $F0
KRP_Frame72: dc.b  $4
	dc.b  $F0, $4, $0, $0, $F4
	dc.b  $F8, $0, $0, $2, $EC
	dc.b  $8, $0, $0, $3, $EC
	dc.b  $F8, $E, $0, $4, $F4
UGX_Frame73: dc.b  $3
	dc.b  $F0, $4, $0, $0, $FC
	dc.b  $F8, $E, $0, $2, $EC
	dc.b  $F8, $2, $0, $E, $C
SCC_Frame74: dc.b  $3
	dc.b  $F0, $4, $0, $0, $F8
	dc.b  $F8, $D, $0, $2, $F0
	dc.b  $8, $8, $0, $A, $F8
IUV_Frame75: dc.b  $2
	dc.b  $F0, $0, $0, $0, $F4
	dc.b  $F8, $A, $0, $1, $F4
HJY_Frame76: dc.b  $3
	dc.b  $F0, $8, $0, $0, $F0
	dc.b  $F8, $D, $0, $3, $F0
	dc.b  $8, $8, $0, $B, $F0
FBQ_Frame77: dc.b  $1
	dc.b  $F4, $E, $0, $0, $F0
AFH_Frame78: dc.b  $4
	dc.b  $E7, $C, $0, $0, $EE
	dc.b  $EF, $8, $0, $4, $EE
	dc.b  $F7, $D, $0, $7, $EE
	dc.b  $7, $D, $0, $F, $F6
ECD_Frame79: dc.b  $4
	dc.b  $E6, $4, $0, $0, $E9
	dc.b  $EE, $E, $0, $2, $E1
	dc.b  $F6, $6, $0, $E, $1
	dc.b  $6, $8, $0, $14, $E9
NAP_Frame7A: dc.b  $3
	dc.b  $F1, $8, $0, $0, $E6
	dc.b  $F9, $E, $0, $3, $E6
	dc.b  $E9, $7, $0, $F, $6
QGR_Frame7B: dc.b  $4
	dc.b  $EE, $8, $0, $0, $F5
	dc.b  $F6, $4, $0, $3, $FD
	dc.b  $6, $1, $0, $5, $E5
	dc.b  $FE, $F, $0, $7, $ED
VPD_Frame7C: dc.b  $4
	dc.b  $12, $C, $18, $0, $F1
	dc.b  $A, $8, $18, $4, $F9
	dc.b  $FA, $D, $18, $7, $F1
	dc.b  $EA, $D, $18, $F, $E9
FRK_Frame7D: dc.b  $4
	dc.b  $13, $4, $18, $0, $4
	dc.b  $FB, $E, $18, $2, $FC
	dc.b  $F3, $6, $18, $E, $EC
	dc.b  $F3, $8, $18, $14, $FC
JLF_Frame7E: dc.b  $3
	dc.b  $7, $8, $18, $0, $1
	dc.b  $EF, $E, $18, $3, $F9
	dc.b  $F7, $7, $18, $F, $E9
IGH_Frame7F: dc.b  $4
	dc.b  $C, $8, $18, $0, $F3
	dc.b  $4, $4, $18, $3, $F3
	dc.b  $EC, $1, $18, $5, $13
	dc.b  $E4, $F, $18, $7, $F3
OKP_Frame80: dc.b  $4
	dc.b  $E8, $E, $0, $0, $EF
	dc.b  $E8, $0, $0, $C, $F
	dc.b  $0, $4, $0, $D, $F7
	dc.b  $8, $9, $0, $F, $EF
SXC_Frame81: dc.b  $4
	dc.b  $E8, $C, $0, $0, $EE
	dc.b  $F0, $D, $0, $4, $EE
	dc.b  $0, $5, $0, $C, $F6
	dc.b  $10, $8, $0, $10, $EE
QMN_Frame82: dc.b  $3
	dc.b  $E8, $8, $0, $0, $F4
	dc.b  $F0, $C, $0, $3, $EC
	dc.b  $F8, $B, $0, $7, $F4
ORQ_Frame83: dc.b  $4
	dc.b  $E8, $0, $0, $0, $EA
	dc.b  $E8, $D, $0, $1, $F2
	dc.b  $F8, $8, $0, $9, $F2
	dc.b  $0, $6, $0, $C, $FA
QJK_Frame84: dc.b  $3
	dc.b  $E8, $E, $0, $0, $ED
	dc.b  $0, $9, $0, $C, $F5
	dc.b  $10, $4, $0, $12, $F5
JKB_Frame85: dc.b  $2
	dc.b  $E8, $E, $0, $0, $EF
	dc.b  $0, $6, $0, $C, $F7
SYW_Frame86: dc.b  $3
	dc.b  $F8, $8, $0, $0, $FC
	dc.b  $0, $D, $0, $3, $F4
	dc.b  $10, $8, $0, $B, $F4
XHO_Frame87: dc.b  $2
	dc.b  $F8, $E, $0, $0, $F4
	dc.b  $10, $8, $0, $C, $F4
REV_Frame88: dc.b  $2
	dc.b  $F8, $E, $0, $0, $F4
	dc.b  $10, $8, $0, $C, $F4
LFN_Frame89: dc.b  $2
	dc.b  $F8, $E, $0, $0, $F4
	dc.b  $10, $8, $0, $C, $F4
BKU_Frame8A: dc.b  $2
	dc.b  $F8, $E, $0, $0, $F4
	dc.b  $10, $8, $0, $C, $F4
BTB_Frame8B: dc.b  $2
	dc.b  $F8, $E, $0, $0, $F4
	dc.b  $10, $8, $0, $C, $F4
PVS_Frame8C: dc.b  $3
	dc.b  $F0, $E, $0, $0, $EC
	dc.b  $F0, $2, $0, $C, $C
	dc.b  $8, $8, $0, $F, $F4
RRB_Frame8D: dc.b  $3
	dc.b  $EF, $E, $0, $0, $EC
	dc.b  $EF, $2, $0, $C, $C
	dc.b  $7, $8, $0, $F, $F4
CDF_Frame8E: dc.b  $2
	dc.b  $E8, $B, $0, $0, $F1
	dc.b  $8, $5, $0, $C, $F9
TAB_Frame8F: dc.b  $3
	dc.b  $F1, $C, $0, $0, $E9
	dc.b  $F9, $5, $0, $4, $E9
	dc.b  $F9, $A, $0, $8, $F9
IBL_Frame90: dc.b  $4
	dc.b  $E8, $9, $0, $0, $F0
	dc.b  $F8, $C, $0, $6, $F0
	dc.b  $0, $8, $0, $A, $F0
	dc.b  $8, $9, $0, $D, $F8
JUH_Frame91: dc.b  $4
	dc.b  $E6, $9, $0, $0, $F0
	dc.b  $F6, $C, $0, $6, $F0
	dc.b  $FE, $8, $0, $A, $F0
	dc.b  $6, $D, $0, $D, $F8
FXO_Frame92: dc.b  $4
	dc.b  $E8, $8, $0, $0, $F0
	dc.b  $F0, $E, $0, $3, $F0
	dc.b  $0, $0, $0, $F, $10
	dc.b  $8, $4, $0, $10, $0
HGZ_Frame93: dc.b  $2
	dc.b  $E8, $8, $0, $0, $F0
	dc.b  $F0, $E, $0, $3, $F0
ETR_Frame94: dc.b  $5
	dc.b  $E8, $D, $0, $0, $F2
	dc.b  $E8, $4, $0, $8, $F7
	dc.b  $F0, $9, $0, $A, $F7
	dc.b  $0, $5, $0, $10, $F7
	dc.b  $10, $8, $0, $14, $F7
RAG_Frame95: dc.b  $5
	dc.b  $E8, $8, $0, $0, $F6
	dc.b  $E8, $4, $0, $3, $F7
	dc.b  $F0, $9, $0, $5, $F7
	dc.b  $0, $5, $0, $B, $F7
	dc.b  $10, $8, $0, $F, $F7
HWA_Frame96: dc.b  $1
	dc.b  $F0, $F, $0, $0, $F0
LJJ_Frame97: dc.b  $1
	dc.b  $F0, $F, $0, $0, $F0
HGY_Frame98: dc.b  $1
	dc.b  $F0, $F, $0, $0, $F0
BQE_Frame99: dc.b  $1
	dc.b  $F0, $F, $0, $0, $F0
AOV_Frame9A: dc.b  $1
	dc.b  $F0, $F, $0, $0, $F0
ZBG_Frame9B: dc.b  $2
	dc.b  $EC, $0, $0, $0, $0
	dc.b  $F4, $B, $0, $1, $F8
AET_Frame9C: dc.b  $2
	dc.b  $F4, $0, $0, $0, $3
	dc.b  $FC, $E, $0, $1, $F3
BYP_Frame9D: dc.b  $4
	dc.b  $EB, $A, $0, $0, $F5
	dc.b  $F3, $1, $0, $9, $ED
	dc.b  $3, $C, $0, $B, $F5
	dc.b  $B, $8, $0, $F, $FD
SSD_Frame9E: dc.b  $4
	dc.b  $EB, $A, $0, $0, $F6
	dc.b  $F3, $1, $0, $9, $EE
	dc.b  $3, $C, $0, $B, $F6
	dc.b  $B, $8, $0, $F, $FE
KFI_Frame9F: dc.b  $4
	dc.b  $EA, $8, $0, $0, $F9
	dc.b  $F2, $D, $0, $3, $F1
	dc.b  $2, $8, $0, $B, $F9
	dc.b  $A, $4, $0, $E, $1
VGB_FrameA0: dc.b  $3
	dc.b  $EC, $8, $0, $0, $EF
	dc.b  $F4, $E, $0, $3, $EF
	dc.b  $C, $8, $0, $F, $F7
GOZ_FrameA1: dc.b  $3
	dc.b  $EC, $D, $0, $0, $EB
	dc.b  $EC, $0, $0, $8, $B
	dc.b  $FC, $A, $0, $9, $EB
VVG_FrameA2: dc.b  $4
	dc.b  $E5, $0, $0, $0, $F4
	dc.b  $ED, $E, $0, $1, $EC
	dc.b  $ED, $0, $0, $D, $E4
	dc.b  $5, $9, $0, $E, $EC
OLW_FrameA3: dc.b  $3
	dc.b  $E4, $0, $0, $0, $FB
	dc.b  $EC, $F, $0, $1, $EB
	dc.b  $C, $8, $0, $11, $EB
DRQ_FrameA4: dc.b  $4
	dc.b  $EC, $8, $0, $0, $FA
	dc.b  $F4, $E, $0, $3, $EA
	dc.b  $F4, $1, $0, $F, $A
	dc.b  $C, $8, $0, $11, $F2
ZWJ_FrameA5: dc.b  $3
	dc.b  $EC, $F, $0, $0, $F3
	dc.b  $4, $0, $0, $10, $EB
	dc.b  $C, $8, $0, $11, $F3
TEF_FrameA6: dc.b  $4
	dc.b  $ED, $8, $0, $0, $FA
	dc.b  $F5, $E, $0, $3, $EA
	dc.b  $F5, $1, $0, $F, $A
	dc.b  $D, $8, $0, $11, $F2
OML_FrameA7: dc.b  $3
	dc.b  $EC, $8, $0, $0, $F8
	dc.b  $F4, $F, $0, $3, $F0
	dc.b  $F4, $0, $0, $13, $10
BPX_FrameA8: dc.b  $3
	dc.b  $EC, $8, $0, $0, $F8
	dc.b  $F4, $F, $0, $3, $F0
	dc.b  $F4, $0, $0, $13, $10
EVZ_FrameA9: dc.b  $3
	dc.b  $EC, $4, $0, $0, $F8
	dc.b  $F4, $F, $0, $2, $F0
	dc.b  $F4, $0, $0, $12, $10
YWJ_FrameAA: dc.b  $3
	dc.b  $F4, $E, $0, $0, $E6
	dc.b  $F4, $0, $0, $C, $6
	dc.b  $FC, $9, $0, $D, $6
OTM_FrameAB: dc.b  $3
	dc.b  $F4, $E, $0, $0, $E6
	dc.b  $F4, $0, $0, $C, $6
	dc.b  $FC, $9, $0, $D, $6
QVZ_FrameAC: dc.b  $4
	dc.b  $EC, $F, $0, $0, $EC
	dc.b  $4, $0, $0, $10, $C
	dc.b  $C, $4, $0, $11, $EC
	dc.b  $C, $4, $0, $13, $4
RQN_FrameAD: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $D, $0, $3, $EE
	dc.b  $4, $4, $0, $B, $F6
	dc.b  $C, $8, $0, $D, $F6
CJN_FrameAE: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $D, $0, $3, $EE
	dc.b  $4, $4, $0, $B, $F6
	dc.b  $C, $8, $0, $D, $F6
WJH_FrameAF: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $C, $0, $3, $E6
	dc.b  $FC, $D, $0, $7, $EE
	dc.b  $C, $8, $0, $F, $F6
QLJ_FrameB0: dc.b  $2
	dc.b  $EC, $D, $0, $0, $EA
	dc.b  $FC, $A, $0, $8, $F2
LEF_FrameB1: dc.b  $3
	dc.b  $EC, $8, $0, $0, $EF
	dc.b  $F4, $D, $0, $3, $EF
	dc.b  $4, $9, $0, $B, $EF
VWT_FrameB2: dc.b  $3
	dc.b  $EC, $8, $0, $0, $EF
	dc.b  $F4, $D, $0, $3, $EF
	dc.b  $4, $9, $0, $B, $EF
NQA_FrameB3: dc.b  $3
	dc.b  $EC, $8, $0, $0, $EF
	dc.b  $F4, $D, $0, $3, $EF
	dc.b  $4, $9, $0, $B, $EF
KRF_FrameB4: dc.b  $3
	dc.b  $E6, $B, $0, $0, $F5
	dc.b  $6, $8, $0, $C, $F5
	dc.b  $E, $5, $0, $F, $F5
FIF_FrameB5: dc.b  $3
	dc.b  $E6, $B, $0, $0, $F5
	dc.b  $6, $8, $0, $C, $F5
	dc.b  $E, $5, $0, $F, $F5
YWS_FrameB6: dc.b  $3
	dc.b  $EC, $4, $0, $0, $FB
	dc.b  $F4, $A, $0, $2, $F3
	dc.b  $C, $C, $0, $B, $EB
MTV_FrameB7: dc.b  $3
	dc.b  $EC, $4, $0, $0, $FB
	dc.b  $F4, $A, $0, $2, $F3
	dc.b  $C, $4, $0, $B, $F3
YZX_FrameB8: dc.b  $3
	dc.b  $EC, $4, $0, $0, $FB
	dc.b  $F4, $9, $0, $2, $F3
	dc.b  $4, $D, $0, $8, $EB
LYM_FrameB9: dc.b  $3
	dc.b  $EC, $4, $0, $0, $FB
	dc.b  $F4, $A, $0, $2, $F3
	dc.b  $C, $4, $0, $B, $F3
EMH_FrameBA: dc.b  $4
	dc.b  $FC, $A, $0, $0, $F8
	dc.b  $EC, $8, $0, $9, $F0
	dc.b  $F4, $C, $0, $C, $F0
	dc.b  $FC, $0, $0, $10, $F0
REZ_FrameBB: dc.b  $3
	dc.b  $ED, $8, $0, $0, $EE
	dc.b  $F5, $D, $0, $3, $EE
	dc.b  $5, $9, $0, $B, $F6
MDG_FrameBC: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $D, $0, $3, $EE
	dc.b  $4, $8, $0, $B, $EE
	dc.b  $C, $8, $0, $E, $F6
HRI_FrameBD: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $D, $0, $3, $EE
	dc.b  $4, $8, $0, $B, $EE
	dc.b  $C, $8, $0, $E, $F6
GBR_FrameBE: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $D, $0, $3, $EE
	dc.b  $4, $8, $0, $B, $EE
	dc.b  $C, $8, $0, $E, $F6
CGK_FrameBF: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $D, $0, $3, $EE
	dc.b  $4, $8, $0, $B, $EE
	dc.b  $C, $8, $0, $E, $F6
EZE_FrameC0: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $D, $0, $3, $EE
	dc.b  $4, $8, $0, $B, $EE
	dc.b  $C, $8, $0, $E, $F6
CVO_FrameC1: dc.b  $2
	dc.b  $EC, $B, $0, $0, $F3
	dc.b  $C, $C, $0, $C, $F3
EPK_FrameC2: dc.b  $4
	dc.b  $EC, $8, $0, $0, $F3
	dc.b  $F4, $D, $0, $3, $F3
	dc.b  $4, $8, $0, $B, $F3
	dc.b  $C, $C, $0, $E, $F3
RVF_FrameC3: dc.b  $4
	dc.b  $EC, $8, $0, $0, $ED
	dc.b  $F4, $D, $0, $3, $ED
	dc.b  $4, $8, $0, $B, $F5
	dc.b  $C, $8, $0, $E, $F5
LDS_FrameC4: dc.b  $4
	dc.b  $EE, $8, $0, $0, $ED
	dc.b  $F6, $C, $0, $3, $E5
	dc.b  $FE, $C, $0, $7, $ED
	dc.b  $6, $9, $0, $B, $F5
MCB_FrameC5: dc.b  $3
	dc.b  $EC, $E, $0, $0, $ED
	dc.b  $4, $8, $0, $C, $F5
	dc.b  $C, $8, $0, $F, $F5
BLC_FrameC6: dc.b  $4
	dc.b  $EC, $8, $0, $0, $EE
	dc.b  $F4, $D, $0, $3, $EE
	dc.b  $4, $8, $0, $B, $F6
	dc.b  $C, $8, $0, $E, $F6
JLT_FrameC7: dc.b  $4
	dc.b  $EC, $8, $0, $0, $F5
	dc.b  $F4, $C, $0, $3, $ED
	dc.b  $FC, $9, $0, $7, $F5
	dc.b  $C, $8, $0, $D, $F5
GHK_FrameC8: dc.b  $3
	dc.b  $F4, $A, $0, $0, $FB
	dc.b  $FC, $4, $0, $9, $EB
	dc.b  $4, $8, $0, $B, $E3
SWY_FrameC9: dc.b  $3
	dc.b  $F4, $9, $0, $0, $F4
	dc.b  $4, $C, $0, $6, $EC
	dc.b  $4, $0, $0, $A, $C
SJE_FrameCA: dc.b  $2
	dc.b  $F4, $9, $0, $0, $F7
	dc.b  $4, $C, $0, $6, $EF
BIS_FrameCB: dc.b  $3
	dc.b  $F4, $9, $8, $0, $F3
	dc.b  $4, $C, $8, $6, $F3
	dc.b  $4, $0, $8, $A, $EB
TMX_FrameCC: dc.b  $3
	dc.b  $F4, $A, $8, $0, $EE
	dc.b  $FC, $4, $8, $9, $6
	dc.b  $4, $8, $8, $B, $6
SZF_FrameCD: dc.b  $2
	dc.b  $F4, $E, $0, $0, $F2
	dc.b  $4, $0, $0, $C, $EA
XTS_FrameCE: dc.b  $2
	dc.b  $F4, $9, $0, $0, $F7
	dc.b  $4, $C, $0, $6, $EF
NYQ_FrameCF: dc.b  $2
	dc.b  $F4, $E, $8, $0, $EF
	dc.b  $4, $0, $8, $C, $F
KOK_FrameD0: dc.b  $3
	dc.b  $F8, $E, $0, $0, $EC
	dc.b  $F8, $2, $0, $C, $C
	dc.b  $10, $8, $0, $F, $F4
CSF_FrameD1: dc.b  $3
	dc.b  $F7, $E, $0, $0, $EC
	dc.b  $F7, $2, $0, $C, $C
	dc.b  $F, $8, $0, $F, $F4
AZI_FrameD2: dc.b  $1
	dc.b  $F0, $B, $0, $0, $F4
TWL_FrameD3: dc.b  $3
	dc.b  $E8, $9, $0, $0, $F3
	dc.b  $F8, $D, $0, $6, $F3
	dc.b  $8, $9, $0, $E, $F3
ADY_FrameD4: dc.b  $2
	dc.b  $E8, $F, $0, $0, $F0
	dc.b  $8, $9, $0, $10, $F0
AHN_FrameD5: dc.b  $3
	dc.b  $E8, $A, $0, $0, $F0
	dc.b  $0, $C, $0, $9, $F0
	dc.b  $8, $9, $0, $D, $F0
ZPK_FrameD6: dc.b  $3
	dc.b  $E8, $A, $0, $0, $F0
	dc.b  $0, $C, $0, $9, $F0
	dc.b  $8, $9, $0, $D, $F0
JDN_FrameD7: dc.b  $3
	dc.b  $F4, $E, $0, $0, $E8
	dc.b  $F4, $2, $0, $C, $8
	dc.b  $C, $8, $0, $F, $F0
BSG_FrameD8: dc.b  $3
	dc.b  $F3, $E, $0, $0, $E8
	dc.b  $F3, $2, $0, $C, $8
	dc.b  $B, $8, $0, $F, $F0
BJD_FrameD9: dc.b  $4
	dc.b  $EC, $E, $0, $0, $E8
	dc.b  $FC, $0, $0, $C, $8
	dc.b  $4, $C, $0, $D, $F0
	dc.b  $C, $8, $0, $11, $F8
SWS_FrameDA: dc.b  $7
	dc.b  $14, $4, $0, $0, $F0
	dc.b  $C, $4, $0, $2, $F0
	dc.b  $4, $C, $0, $4, $E8
	dc.b  $FC, $C, $0, $8, $E8
	dc.b  $FC, $0, $0, $C, $8
	dc.b  $F4, $C, $0, $D, $F0
	dc.b  $EC, $8, $0, $11, $F0
LQY_FrameDB: dc.b  $3
	dc.b  $EF, $B, $0, $0, $EE
	dc.b  $F7, $2, $0, $C, $6
	dc.b  $F7, $0, $0, $F, $E6
RPZ_FrameDC: dc.b  $4
	dc.b  $F2, $E, $0, $0, $EB
	dc.b  $A, $8, $0, $C, $F3
	dc.b  $EA, $4, $0, $F, $FB
	dc.b  $F2, $2, $0, $11, $B
XLP_FrameDD: dc.b  $3
	dc.b  $F0, $B, $10, $0, $EE
	dc.b  $F0, $2, $10, $C, $6
	dc.b  $0, $0, $10, $F, $E6
AJA_FrameDE: dc.b  $4
	dc.b  $F5, $E, $10, $0, $EB
	dc.b  $ED, $8, $10, $C, $F3
	dc.b  $D, $4, $10, $F, $FB
	dc.b  $F5, $2, $10, $11, $B
