; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Jun 14 2020 11:44:56 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAPIUMRKMWAM9:
	dc.w $0, DATAPIUMRKMWAM9_1-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_2-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_3-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_4-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_5-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_6-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_7-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_8-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_9-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_10-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_11-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_12-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_13-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_14-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_15-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_16-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_17-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_18-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_19-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_1A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_1B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_1C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_1D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_1E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_1F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_20-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_21-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_22-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_23-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_24-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_25-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_26-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_27-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_28-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_29-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_2A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_2B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_2C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_2D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_2E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_2F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_30-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_31-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_32-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_33-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_34-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_35-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_36-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_37-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_38-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_39-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_3A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_3B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_3C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_3D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_3E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_3F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_40-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_41-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_42-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_43-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_44-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_45-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_46-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_47-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_48-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_49-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_4A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_4B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_4C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_4D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_4E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_4F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_50-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_51-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_52-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_53-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_54-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_55-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_56-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_57-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_58-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_59-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_5A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_5B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_5C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_5D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_5E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_5F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_60-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_61-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_62-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_63-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_64-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_65-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_66-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_67-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_68-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_69-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_6A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_6B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_6C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_6D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_6E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_6F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_70-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_71-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_72-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_73-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_74-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_75-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_76-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_77-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_78-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_79-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_7A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_7B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_7C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_7D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_7E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_7F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_80-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_81-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_82-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_83-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_84-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_85-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_86-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_87-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_88-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_89-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_8A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_8B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_8C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_8D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_8E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_8F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_90-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_91-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_92-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_93-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_94-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_95-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_96-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_97-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_98-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_99-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_9A-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_9B-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_9C-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_9D-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_9E-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_9F-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_A0-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_A1-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_A2-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_A3-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_A4-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_A5-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_A6-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_A7-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_A8-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_A9-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_AA-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_AB-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_AC-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_AD-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_AE-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_AF-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_B0-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_B1-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_B2-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_B3-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_B4-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_B5-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_B6-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_B7-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_B8-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_B9-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_BA-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_BB-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_BC-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_BD-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_BE-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_BF-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_C0-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_C1-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_C2-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_C3-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_C4-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_C5-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_C6-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_C7-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_C8-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_C9-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_CA-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_CB-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_CC-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_CD-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_CE-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_CF-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_D0-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_D1-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_D2-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_D3-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_D4-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_D5-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_D6-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_D7-DATAPIUMRKMWAM9
	dc.w DATAPIUMRKMWAM9_D8-DATAPIUMRKMWAM9, DATAPIUMRKMWAM9_D9-DATAPIUMRKMWAM9
DATAPIUMRKMWAM9_1: dc.b $4
	dc.b $0, $9, $0, $0, $E4
	dc.b $EC, $4, $0, $6, $F9
	dc.b $F4, $9, $0, $8, $F1
	dc.b $4, $D, $0, $E, $F1
DATAPIUMRKMWAM9_2: dc.b $4
	dc.b $0, $9, $0, $0, $E2
	dc.b $F0, $D, $0, $6, $ED
	dc.b $0, $8, $0, $E, $ED
	dc.b $8, $C, $0, $11, $ED
DATAPIUMRKMWAM9_3: dc.b $3
	dc.b $FC, $9, $0, $0, $E6
	dc.b $F0, $A, $0, $6, $FB
	dc.b $8, $8, $0, $F, $F3
DATAPIUMRKMWAM9_4: dc.b $4
	dc.b $FE, $9, $0, $0, $E4
	dc.b $F0, $D, $0, $6, $F0
	dc.b $0, $8, $0, $E, $F0
	dc.b $8, $C, $0, $11, $F0
DATAPIUMRKMWAM9_5: dc.b $4
	dc.b $0, $9, $0, $0, $E4
	dc.b $EC, $4, $0, $6, $F8
	dc.b $F4, $9, $0, $8, $F0
	dc.b $4, $D, $0, $E, $F0
DATAPIUMRKMWAM9_6: dc.b $4
	dc.b $0, $9, $0, $0, $E4
	dc.b $F0, $D, $0, $6, $F0
	dc.b $0, $8, $0, $E, $F0
	dc.b $8, $C, $0, $11, $F0
DATAPIUMRKMWAM9_7: dc.b $3
	dc.b $FE, $9, $0, $0, $E4
	dc.b $F0, $A, $0, $6, $F8
	dc.b $8, $8, $0, $F, $F0
DATAPIUMRKMWAM9_8: dc.b $4
	dc.b $FE, $9, $0, $0, $E4
	dc.b $F0, $D, $0, $6, $F0
	dc.b $0, $8, $0, $E, $F0
	dc.b $8, $C, $0, $11, $F0
DATAPIUMRKMWAM9_9: dc.b $4
	dc.b $EE, $4, $0, $0, $F2
	dc.b $F6, $D, $0, $2, $F2
	dc.b $6, $8, $0, $A, $FA
	dc.b $E, $8, $0, $D, $F2
DATAPIUMRKMWAM9_A: dc.b $3
	dc.b $F0, $B, $0, $0, $F1
	dc.b $F8, $6, $0, $C, $9
	dc.b $10, $8, $0, $12, $F1
DATAPIUMRKMWAM9_B: dc.b $4
	dc.b $EA, $4, $0, $0, $F8
	dc.b $F2, $D, $0, $2, $F0
	dc.b $2, $8, $0, $A, $F8
	dc.b $A, $D, $0, $D, $F0
DATAPIUMRKMWAM9_C: dc.b $3
	dc.b $EF, $4, $0, $0, $F6
	dc.b $F7, $F, $0, $2, $EE
	dc.b $FF, $0, $0, $12, $E
DATAPIUMRKMWAM9_D: dc.b $3
	dc.b $ED, $8, $0, $0, $F2
	dc.b $F5, $D, $0, $3, $F2
	dc.b $5, $9, $0, $B, $F2
DATAPIUMRKMWAM9_E: dc.b $3
	dc.b $F2, $4, $0, $0, $F7
	dc.b $FA, $B, $0, $2, $EF
	dc.b $2, $5, $0, $E, $7
DATAPIUMRKMWAM9_F: dc.b $3
	dc.b $F0, $4, $0, $0, $F7
	dc.b $F8, $8, $0, $2, $EF
	dc.b $0, $E, $0, $5, $EF
DATAPIUMRKMWAM9_10: dc.b $4
	dc.b $EC, $0, $0, $0, $FC
	dc.b $F4, $9, $0, $1, $F4
	dc.b $4, $C, $0, $7, $F4
	dc.b $C, $C, $0, $B, $EC
DATAPIUMRKMWAM9_11: dc.b $3
	dc.b $6, $6, $0, $0, $FC
	dc.b $EE, $4, $0, $6, $0
	dc.b $F6, $E, $0, $8, $F0
DATAPIUMRKMWAM9_12: dc.b $3
	dc.b $4, $6, $0, $0, $FC
	dc.b $F2, $E, $0, $6, $F0
	dc.b $A, $0, $0, $12, $8
DATAPIUMRKMWAM9_13: dc.b $3
	dc.b $4, $6, $0, $0, $FC
	dc.b $F2, $8, $0, $6, $F0
	dc.b $FA, $D, $0, $9, $F0
DATAPIUMRKMWAM9_14: dc.b $2
	dc.b $6, $6, $0, $0, $FC
	dc.b $F4, $E, $0, $6, $F0
DATAPIUMRKMWAM9_15: dc.b $3
	dc.b $4, $6, $0, $0, $FC
	dc.b $ED, $4, $0, $6, $0
	dc.b $F5, $E, $0, $8, $F0
DATAPIUMRKMWAM9_16: dc.b $2
	dc.b $6, $6, $0, $0, $FC
	dc.b $F4, $E, $0, $6, $F0
DATAPIUMRKMWAM9_17: dc.b $3
	dc.b $4, $6, $0, $0, $FC
	dc.b $F1, $8, $0, $6, $F0
	dc.b $F9, $D, $0, $9, $F0
DATAPIUMRKMWAM9_18: dc.b $2
	dc.b $2, $6, $0, $0, $FC
	dc.b $F4, $E, $0, $6, $F0
DATAPIUMRKMWAM9_19: dc.b $3
	dc.b $EF, $8, $0, $0, $F5
	dc.b $F7, $E, $0, $3, $F5
	dc.b $FF, $1, $0, $F, $ED
DATAPIUMRKMWAM9_1A: dc.b $4
	dc.b $E8, $4, $0, $0, $F8
	dc.b $F0, $8, $0, $2, $F8
	dc.b $F8, $E, $0, $5, $F0
	dc.b $F8, $2, $0, $11, $10
DATAPIUMRKMWAM9_1B: dc.b $4
	dc.b $F0, $C, $0, $0, $F1
	dc.b $F8, $C, $0, $4, $E9
	dc.b $0, $9, $0, $8, $F1
	dc.b $F8, $6, $0, $E, $9
DATAPIUMRKMWAM9_1C: dc.b $3
	dc.b $EA, $0, $0, $0, $FE
	dc.b $F2, $F, $0, $1, $F6
	dc.b $FA, $1, $0, $11, $EE
DATAPIUMRKMWAM9_1D: dc.b $3
	dc.b $EF, $4, $0, $0, $F7
	dc.b $F7, $E, $0, $2, $EF
	dc.b $F7, $2, $0, $E, $F
DATAPIUMRKMWAM9_1E: dc.b $4
	dc.b $E9, $0, $0, $0, $0
	dc.b $F1, $4, $0, $1, $0
	dc.b $F9, $E, $0, $3, $F8
	dc.b $F9, $1, $0, $F, $F0
DATAPIUMRKMWAM9_1F: dc.b $3
	dc.b $F1, $8, $0, $0, $0
	dc.b $F9, $E, $0, $3, $F8
	dc.b $F9, $1, $0, $F, $F0
DATAPIUMRKMWAM9_20: dc.b $4
	dc.b $EC, $0, $0, $0, $4
	dc.b $F4, $E, $0, $1, $F4
	dc.b $FC, $0, $0, $D, $EC
	dc.b $C, $0, $0, $E, $C
DATAPIUMRKMWAM9_21: dc.b $4
	dc.b $F0, $7, $0, $0, $EA
	dc.b $F0, $9, $0, $8, $F8
	dc.b $0, $C, $0, $E, $F0
	dc.b $8, $4, $0, $12, $F0
DATAPIUMRKMWAM9_22: dc.b $4
	dc.b $FC, $4, $0, $0, $EA
	dc.b $F0, $9, $0, $2, $F8
	dc.b $0, $C, $0, $8, $F0
	dc.b $8, $4, $0, $C, $F0
DATAPIUMRKMWAM9_23: dc.b $4
	dc.b $F8, $5, $0, $0, $EA
	dc.b $F0, $9, $0, $4, $F8
	dc.b $0, $C, $0, $A, $F0
	dc.b $8, $4, $0, $E, $F0
DATAPIUMRKMWAM9_24: dc.b $4
	dc.b $F0, $7, $0, $0, $EA
	dc.b $F0, $9, $0, $8, $F8
	dc.b $0, $C, $0, $E, $F0
	dc.b $8, $4, $0, $12, $F0
DATAPIUMRKMWAM9_25: dc.b $4
	dc.b $FD, $B, $0, $0, $E7
	dc.b $EC, $4, $0, $C, $F8
	dc.b $F4, $9, $0, $E, $F0
	dc.b $4, $5, $0, $14, $F8
DATAPIUMRKMWAM9_26: dc.b $4
	dc.b $1, $9, $0, $0, $E3
	dc.b $ED, $4, $0, $6, $F8
	dc.b $F5, $9, $0, $8, $F0
	dc.b $5, $5, $0, $E, $F8
DATAPIUMRKMWAM9_27: dc.b $4
	dc.b $1, $5, $0, $0, $EF
	dc.b $EC, $4, $0, $4, $F8
	dc.b $F4, $9, $0, $6, $F0
	dc.b $4, $5, $0, $C, $F8
DATAPIUMRKMWAM9_28: dc.b $4
	dc.b $1, $6, $0, $0, $EE
	dc.b $ED, $4, $0, $6, $F8
	dc.b $F5, $9, $0, $8, $F0
	dc.b $5, $5, $0, $E, $F8
DATAPIUMRKMWAM9_29: dc.b $4
	dc.b $6, $D, $0, $0, $F0
	dc.b $F0, $9, $0, $8, $F0
	dc.b $0, $C, $0, $E, $F0
	dc.b $8, $4, $0, $12, $0
DATAPIUMRKMWAM9_2A: dc.b $4
	dc.b $6, $1, $0, $0, $FC
	dc.b $F0, $9, $0, $2, $F0
	dc.b $0, $C, $0, $8, $F0
	dc.b $8, $4, $0, $C, $0
DATAPIUMRKMWAM9_2B: dc.b $4
	dc.b $6, $5, $0, $0, $F8
	dc.b $F0, $9, $0, $4, $F0
	dc.b $0, $C, $0, $A, $F0
	dc.b $8, $4, $0, $E, $0
DATAPIUMRKMWAM9_2C: dc.b $4
	dc.b $6, $D, $0, $0, $F0
	dc.b $F0, $9, $0, $8, $F0
	dc.b $0, $C, $0, $E, $F0
	dc.b $8, $4, $0, $12, $0
DATAPIUMRKMWAM9_2D: dc.b $4
	dc.b $2, $E, $0, $0, $FD
	dc.b $F8, $D, $0, $C, $EC
	dc.b $F8, $1, $0, $14, $C
	dc.b $8, $4, $0, $16, $F4
DATAPIUMRKMWAM9_2E: dc.b $4
	dc.b $3, $6, $0, $0, $1
	dc.b $F8, $D, $0, $6, $EB
	dc.b $F8, $1, $0, $E, $B
	dc.b $8, $4, $0, $10, $F3
DATAPIUMRKMWAM9_2F: dc.b $4
	dc.b $2, $5, $0, $0, $0
	dc.b $F8, $D, $0, $4, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $4, $0, $E, $F4
DATAPIUMRKMWAM9_30: dc.b $4
	dc.b $3, $9, $0, $0, $0
	dc.b $F8, $D, $0, $6, $EB
	dc.b $F8, $1, $0, $E, $B
	dc.b $8, $4, $0, $10, $F3
DATAPIUMRKMWAM9_31: dc.b $1
	dc.b $F0, $B, $0, $0, $F1
DATAPIUMRKMWAM9_32: dc.b $2
	dc.b $EC, $B, $0, $0, $F1
	dc.b $C, $4, $0, $C, $F1
DATAPIUMRKMWAM9_33: dc.b $1
	dc.b $ED, $B, $0, $0, $F3
DATAPIUMRKMWAM9_34: dc.b $1
	dc.b $F8, $A, $0, $0, $F3
DATAPIUMRKMWAM9_35: dc.b $2
	dc.b $F3, $A, $0, $0, $F3
	dc.b $B, $0, $0, $9, $3
DATAPIUMRKMWAM9_36: dc.b $2
	dc.b $EF, $4, $0, $0, $F2
	dc.b $F7, $A, $0, $2, $F2
DATAPIUMRKMWAM9_37: dc.b $2
	dc.b $F2, $4, $0, $0, $F2
	dc.b $FA, $A, $0, $2, $F2
DATAPIUMRKMWAM9_38: dc.b $2
	dc.b $F0, $4, $0, $0, $F4
	dc.b $F8, $A, $0, $2, $F4
DATAPIUMRKMWAM9_39: dc.b $2
	dc.b $EE, $4, $0, $0, $F4
	dc.b $F6, $A, $0, $2, $F4
DATAPIUMRKMWAM9_3A: dc.b $2
	dc.b $F4, $9, $0, $0, $F1
	dc.b $4, $4, $0, $6, $F9
DATAPIUMRKMWAM9_3B: dc.b $2
	dc.b $F4, $A, $0, $0, $F1
	dc.b $C, $0, $0, $9, $F1
DATAPIUMRKMWAM9_3C: dc.b $2
	dc.b $F1, $9, $0, $0, $F4
	dc.b $1, $5, $0, $6, $F4
DATAPIUMRKMWAM9_3D: dc.b $2
	dc.b $F1, $A, $0, $0, $F2
	dc.b $9, $4, $0, $9, $FA
DATAPIUMRKMWAM9_3E: dc.b $2
	dc.b $ED, $0, $0, $0, $1
	dc.b $F5, $A, $0, $1, $F1
DATAPIUMRKMWAM9_3F: dc.b $1
	dc.b $F3, $A, $0, $0, $F3
DATAPIUMRKMWAM9_40: dc.b $3
	dc.b $EE, $4, $0, $0, $F2
	dc.b $F6, $9, $0, $2, $F2
	dc.b $6, $4, $0, $8, $FA
DATAPIUMRKMWAM9_41: dc.b $1
	dc.b $F0, $B, $0, $0, $F1
DATAPIUMRKMWAM9_42: dc.b $1
	dc.b $F1, $B, $0, $0, $F0
DATAPIUMRKMWAM9_43: dc.b $3
	dc.b $F0, $8, $0, $0, $F4
	dc.b $F8, $4, $0, $3, $F4
	dc.b $0, $9, $0, $5, $F4
DATAPIUMRKMWAM9_44: dc.b $2
	dc.b $EC, $0, $0, $0, $F9
	dc.b $F4, $A, $0, $1, $F1
DATAPIUMRKMWAM9_45: dc.b $2
	dc.b $F4, $9, $0, $0, $F1
	dc.b $4, $0, $0, $6, $F1
DATAPIUMRKMWAM9_46: dc.b $2
	dc.b $F2, $4, $0, $0, $F7
	dc.b $FA, $9, $0, $2, $EF
DATAPIUMRKMWAM9_47: dc.b $3
	dc.b $ED, $4, $0, $0, $F5
	dc.b $F5, $9, $0, $2, $F5
	dc.b $5, $4, $0, $8, $F5
DATAPIUMRKMWAM9_48: dc.b $2
	dc.b $EF, $A, $0, $0, $F1
	dc.b $7, $4, $0, $9, $F9
DATAPIUMRKMWAM9_49: dc.b $3
	dc.b $F2, $8, $0, $0, $F5
	dc.b $FA, $D, $0, $3, $ED
	dc.b $FA, $0, $0, $B, $D
DATAPIUMRKMWAM9_4A: dc.b $2
	dc.b $F2, $8, $0, $0, $F8
	dc.b $FA, $D, $0, $3, $F0
DATAPIUMRKMWAM9_4B: dc.b $3
	dc.b $F2, $4, $0, $0, $F7
	dc.b $FA, $8, $0, $2, $F7
	dc.b $2, $C, $0, $5, $EF
DATAPIUMRKMWAM9_4C: dc.b $2
	dc.b $F0, $4, $0, $0, $FC
	dc.b $F8, $A, $0, $2, $F4
DATAPIUMRKMWAM9_4D: dc.b $3
	dc.b $F0, $4, $0, $0, $FC
	dc.b $F8, $9, $0, $2, $F4
	dc.b $8, $4, $0, $8, $F4
DATAPIUMRKMWAM9_4E: dc.b $4
	dc.b $EA, $0, $0, $0, $0
	dc.b $F2, $4, $0, $1, $0
	dc.b $FA, $C, $0, $3, $F0
	dc.b $2, $9, $0, $7, $F0
DATAPIUMRKMWAM9_4F: dc.b $4
	dc.b $ED, $4, $0, $0, $0
	dc.b $F5, $C, $0, $2, $F0
	dc.b $FD, $9, $0, $6, $F0
	dc.b $D, $4, $0, $C, $F8
DATAPIUMRKMWAM9_50: dc.b $4
	dc.b $EB, $4, $0, $0, $F9
	dc.b $F3, $C, $0, $2, $F1
	dc.b $FB, $9, $0, $6, $F1
	dc.b $B, $0, $0, $C, $F9
DATAPIUMRKMWAM9_51: dc.b $3
	dc.b $EF, $4, $0, $0, $FA
	dc.b $F7, $9, $0, $2, $F2
	dc.b $7, $4, $0, $8, $FA
DATAPIUMRKMWAM9_52: dc.b $3
	dc.b $F4, $4, $0, $0, $F8
	dc.b $FC, $C, $0, $2, $F0
	dc.b $4, $4, $0, $6, $F8
DATAPIUMRKMWAM9_53: dc.b $2
	dc.b $F4, $D, $0, $0, $F0
	dc.b $4, $8, $0, $8, $F0
DATAPIUMRKMWAM9_54: dc.b $2
	dc.b $F3, $8, $0, $0, $F6
	dc.b $FB, $D, $0, $3, $EE
DATAPIUMRKMWAM9_55: dc.b $3
	dc.b $F0, $8, $0, $0, $F8
	dc.b $F8, $C, $0, $3, $F0
	dc.b $0, $9, $0, $7, $F0
DATAPIUMRKMWAM9_56: dc.b $1
	dc.b $F0, $B, $0, $0, $F3
DATAPIUMRKMWAM9_57: dc.b $3
	dc.b $F0, $8, $0, $0, $F7
	dc.b $F8, $5, $0, $3, $F7
	dc.b $8, $8, $0, $7, $F7
DATAPIUMRKMWAM9_58: dc.b $1
	dc.b $F0, $B, $0, $0, $F3
DATAPIUMRKMWAM9_59: dc.b $1
	dc.b $F0, $B, $0, $0, $F3
DATAPIUMRKMWAM9_5A: dc.b $3
	dc.b $F0, $4, $0, $0, $F7
	dc.b $F8, $9, $0, $2, $F7
	dc.b $8, $4, $0, $8, $F7
DATAPIUMRKMWAM9_5B: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_5C: dc.b $4
	dc.b $F4, $8, $0, $0, $F0
	dc.b $F4, $4, $0, $3, $10
	dc.b $FC, $D, $0, $5, $F0
	dc.b $FC, $5, $0, $D, $10
DATAPIUMRKMWAM9_5D: dc.b $1
	dc.b $F4, $E, $0, $0, $FD
DATAPIUMRKMWAM9_5E: dc.b $3
	dc.b $F4, $E, $0, $0, $F1
	dc.b $F4, $0, $0, $C, $E9
	dc.b $4, $0, $0, $D, $E9
DATAPIUMRKMWAM9_5F: dc.b $2
	dc.b $F4, $E, $0, $0, $F1
	dc.b $F4, $6, $0, $C, $E1
DATAPIUMRKMWAM9_60: dc.b $1
	dc.b $F4, $E, $0, $0, $F4
DATAPIUMRKMWAM9_61: dc.b $1
	dc.b $F4, $E, $0, $0, $E6
DATAPIUMRKMWAM9_62: dc.b $3
	dc.b $F4, $8, $0, $0, $F4
	dc.b $FC, $D, $0, $3, $EC
	dc.b $FC, $1, $0, $B, $C
DATAPIUMRKMWAM9_63: dc.b $4
	dc.b $E8, $A, $0, $0, $F5
	dc.b $0, $4, $0, $9, $F5
	dc.b $8, $8, $0, $B, $F5
	dc.b $10, $8, $0, $E, $F5
DATAPIUMRKMWAM9_64: dc.b $1
	dc.b $F1, $B, $0, $0, $F4
DATAPIUMRKMWAM9_65: dc.b $2
	dc.b $E9, $B, $0, $0, $F4
	dc.b $9, $8, $0, $C, $F4
DATAPIUMRKMWAM9_66: dc.b $2
	dc.b $E7, $B, $0, $0, $F4
	dc.b $7, $9, $0, $C, $F4
DATAPIUMRKMWAM9_67: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_68: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_69: dc.b $3
	dc.b $EF, $8, $0, $0, $F7
	dc.b $F7, $E, $0, $3, $EF
	dc.b $7, $0, $0, $F, $F
DATAPIUMRKMWAM9_6A: dc.b $3
	dc.b $EE, $4, $0, $0, $F7
	dc.b $F6, $D, $0, $2, $EF
	dc.b $6, $8, $0, $A, $F7
DATAPIUMRKMWAM9_6B: dc.b $2
	dc.b $EE, $4, $0, $0, $F3
	dc.b $F6, $A, $0, $2, $F3
DATAPIUMRKMWAM9_6C: dc.b $2
	dc.b $F1, $8, $0, $0, $EE
	dc.b $F9, $D, $0, $3, $EE
DATAPIUMRKMWAM9_6D: dc.b $2
	dc.b $F3, $8, $0, $0, $EF
	dc.b $FB, $D, $0, $3, $EF
DATAPIUMRKMWAM9_6E: dc.b $2
	dc.b $F8, $D, $0, $0, $F1
	dc.b $8, $8, $0, $8, $F9
DATAPIUMRKMWAM9_6F: dc.b $2
	dc.b $F6, $9, $0, $0, $F4
	dc.b $6, $4, $0, $6, $FC
DATAPIUMRKMWAM9_70: dc.b $2
	dc.b $F6, $9, $0, $0, $F4
	dc.b $6, $C, $0, $6, $EC
DATAPIUMRKMWAM9_71: dc.b $2
	dc.b $F7, $D, $0, $0, $EF
	dc.b $7, $8, $0, $8, $EF
DATAPIUMRKMWAM9_72: dc.b $1
	dc.b $F6, $E, $0, $0, $EF
DATAPIUMRKMWAM9_73: dc.b $2
	dc.b $F6, $E, $0, $0, $F7
	dc.b $FE, $1, $0, $C, $EF
DATAPIUMRKMWAM9_74: dc.b $1
	dc.b $F5, $E, $0, $0, $F2
DATAPIUMRKMWAM9_75: dc.b $1
	dc.b $F7, $A, $0, $0, $F2
DATAPIUMRKMWAM9_76: dc.b $2
	dc.b $F4, $8, $0, $0, $F2
	dc.b $FC, $D, $0, $3, $F2
DATAPIUMRKMWAM9_77: dc.b $2
	dc.b $F3, $8, $0, $0, $F0
	dc.b $FB, $D, $0, $3, $F0
DATAPIUMRKMWAM9_78: dc.b $4
	dc.b $E6, $C, $0, $0, $F2
	dc.b $EE, $9, $0, $4, $F2
	dc.b $FE, $C, $0, $A, $F2
	dc.b $6, $8, $0, $E, $FA
DATAPIUMRKMWAM9_79: dc.b $4
	dc.b $E2, $4, $0, $0, $EE
	dc.b $EA, $9, $0, $2, $E6
	dc.b $F2, $1, $0, $8, $6
	dc.b $FA, $9, $0, $A, $EE
DATAPIUMRKMWAM9_7A: dc.b $4
	dc.b $EE, $0, $0, $0, $E4
	dc.b $EE, $6, $0, $1, $FC
	dc.b $F6, $9, $0, $7, $E4
	dc.b $6, $C, $0, $D, $E4
DATAPIUMRKMWAM9_7B: dc.b $4
	dc.b $F4, $4, $0, $0, $F1
	dc.b $FC, $6, $0, $2, $F9
	dc.b $4, $9, $0, $8, $E1
	dc.b $14, $4, $0, $E, $E9
DATAPIUMRKMWAM9_7C: dc.b $4
	dc.b $14, $C, $18, $0, $EE
	dc.b $4, $9, $18, $4, $F6
	dc.b $FC, $C, $18, $A, $EE
	dc.b $F4, $8, $18, $E, $EE
DATAPIUMRKMWAM9_7D: dc.b $4
	dc.b $16, $4, $18, $0, $3
	dc.b $6, $9, $18, $2, $3
	dc.b $FE, $1, $18, $8, $F3
	dc.b $F6, $9, $18, $A, $FB
DATAPIUMRKMWAM9_7E: dc.b $4
	dc.b $A, $0, $18, $0, $15
	dc.b $FA, $6, $18, $1, $F5
	dc.b $FA, $9, $0, $7, $5
	dc.b $F2, $C, $18, $D, $FD
DATAPIUMRKMWAM9_7F: dc.b $4
	dc.b $5, $4, $18, $0, $1
	dc.b $ED, $6, $18, $2, $F9
	dc.b $ED, $9, $18, $8, $9
	dc.b $E5, $4, $18, $E, $9
DATAPIUMRKMWAM9_80: dc.b $2
	dc.b $E8, $D, $0, $0, $EF
	dc.b $F8, $A, $0, $8, $EF
DATAPIUMRKMWAM9_81: dc.b $4
	dc.b $E9, $C, $0, $0, $EE
	dc.b $F1, $8, $0, $4, $EE
	dc.b $F9, $E, $0, $7, $E6
	dc.b $11, $4, $0, $13, $EE
DATAPIUMRKMWAM9_82: dc.b $4
	dc.b $E9, $A, $0, $0, $F6
	dc.b $F9, $4, $0, $9, $E6
	dc.b $1, $C, $0, $B, $E6
	dc.b $9, $5, $0, $F, $F6
DATAPIUMRKMWAM9_83: dc.b $3
	dc.b $E8, $F, $0, $0, $EC
	dc.b $E8, $0, $0, $10, $C
	dc.b $8, $8, $0, $11, $F4
DATAPIUMRKMWAM9_84: dc.b $3
	dc.b $E9, $9, $0, $0, $F6
	dc.b $F9, $D, $0, $6, $E6
	dc.b $9, $5, $0, $E, $F6
DATAPIUMRKMWAM9_85: dc.b $4
	dc.b $E9, $9, $0, $0, $F5
	dc.b $F9, $C, $0, $6, $ED
	dc.b $1, $8, $0, $A, $ED
	dc.b $9, $5, $0, $D, $F5
DATAPIUMRKMWAM9_86: dc.b $2
	dc.b $F8, $C, $0, $0, $F8
	dc.b $0, $9, $0, $4, $F8
DATAPIUMRKMWAM9_87: dc.b $2
	dc.b $F8, $D, $0, $0, $F8
	dc.b $8, $8, $0, $8, $F8
DATAPIUMRKMWAM9_88: dc.b $2
	dc.b $F8, $C, $0, $0, $F8
	dc.b $0, $9, $0, $4, $F8
DATAPIUMRKMWAM9_89: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAPIUMRKMWAM9_8A: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAPIUMRKMWAM9_8B: dc.b $2
	dc.b $E9, $5, $0, $0, $F9
	dc.b $F9, $B, $0, $4, $F1
DATAPIUMRKMWAM9_8C: dc.b $2
	dc.b $E9, $5, $0, $0, $F9
	dc.b $F9, $B, $0, $4, $F1
DATAPIUMRKMWAM9_8D: dc.b $2
	dc.b $EE, $4, $0, $0, $F6
	dc.b $F6, $E, $0, $2, $EE
DATAPIUMRKMWAM9_8E: dc.b $3
	dc.b $F0, $9, $0, $0, $F0
	dc.b $0, $C, $0, $6, $F0
	dc.b $8, $8, $0, $A, $F8
DATAPIUMRKMWAM9_8F: dc.b $3
	dc.b $F0, $9, $0, $0, $F0
	dc.b $0, $C, $0, $6, $F0
	dc.b $8, $8, $0, $A, $F8
DATAPIUMRKMWAM9_90: dc.b $2
	dc.b $E9, $B, $0, $0, $F5
	dc.b $7, $4, $0, $C, $FD
DATAPIUMRKMWAM9_91: dc.b $2
	dc.b $E9, $9, $0, $0, $F5
	dc.b $F9, $D, $0, $6, $F5
DATAPIUMRKMWAM9_92: dc.b $2
	dc.b $E9, $9, $0, $0, $F5
	dc.b $F9, $D, $0, $6, $F5
DATAPIUMRKMWAM9_93: dc.b $1
	dc.b $E9, $A, $0, $0, $F5
DATAPIUMRKMWAM9_94: dc.b $3
	dc.b $E9, $D, $0, $0, $F1
	dc.b $EC, $B, $0, $8, $F4
	dc.b $C, $8, $0, $14, $F4
DATAPIUMRKMWAM9_95: dc.b $3
	dc.b $E8, $9, $0, $0, $F5
	dc.b $EC, $B, $0, $6, $F4
	dc.b $C, $8, $0, $12, $F4
DATAPIUMRKMWAM9_96: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAPIUMRKMWAM9_97: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAPIUMRKMWAM9_98: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAPIUMRKMWAM9_99: dc.b $1
	dc.b $F8, $A, $0, $0, $FA
DATAPIUMRKMWAM9_9A: dc.b $3
	dc.b $F0, $8, $0, $0, $F2
	dc.b $F8, $D, $0, $3, $EA
	dc.b $8, $4, $0, $B, $F2
DATAPIUMRKMWAM9_9B: dc.b $3
	dc.b $F0, $9, $0, $0, $F1
	dc.b $0, $C, $0, $6, $E9
	dc.b $8, $8, $0, $A, $E9
DATAPIUMRKMWAM9_9C: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAPIUMRKMWAM9_9D: dc.b $2
	dc.b $EE, $7, $0, $0, $E6
	dc.b $F6, $A, $0, $8, $F6
DATAPIUMRKMWAM9_9E: dc.b $3
	dc.b $EE, $4, $0, $0, $EE
	dc.b $F6, $E, $0, $2, $E6
	dc.b $F6, $2, $0, $E, $6
DATAPIUMRKMWAM9_9F: dc.b $3
	dc.b $F1, $8, $0, $0, $F6
	dc.b $F9, $D, $0, $3, $EE
	dc.b $9, $8, $0, $B, $EE
DATAPIUMRKMWAM9_A0: dc.b $2
	dc.b $ED, $8, $0, $0, $F3
	dc.b $F5, $E, $0, $3, $EB
DATAPIUMRKMWAM9_A1: dc.b $2
	dc.b $ED, $8, $0, $0, $F3
	dc.b $F5, $E, $0, $3, $EB
DATAPIUMRKMWAM9_A2: dc.b $2
	dc.b $ED, $8, $0, $0, $F3
	dc.b $F5, $E, $0, $3, $EB
DATAPIUMRKMWAM9_A3: dc.b $2
	dc.b $ED, $8, $0, $0, $F3
	dc.b $F5, $E, $0, $3, $EB
DATAPIUMRKMWAM9_A4: dc.b $2
	dc.b $ED, $8, $0, $0, $F3
	dc.b $F5, $E, $0, $3, $EB
DATAPIUMRKMWAM9_A5: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_A6: dc.b $4
	dc.b $E8, $0, $0, $0, $FE
	dc.b $F0, $D, $0, $1, $EE
	dc.b $0, $D, $0, $9, $E6
	dc.b $8, $0, $0, $11, $6
DATAPIUMRKMWAM9_A7: dc.b $2
	dc.b $ED, $D, $0, $0, $F2
	dc.b $FD, $A, $0, $8, $F2
DATAPIUMRKMWAM9_A8: dc.b $3
	dc.b $ED, $8, $0, $0, $F2
	dc.b $F5, $D, $0, $3, $F2
	dc.b $5, $9, $0, $B, $F2
DATAPIUMRKMWAM9_A9: dc.b $2
	dc.b $F0, $A, $0, $0, $F6
	dc.b $8, $C, $0, $9, $EE
DATAPIUMRKMWAM9_AA: dc.b $1
	dc.b $F0, $B, $0, $0, $F6
DATAPIUMRKMWAM9_AB: dc.b $1
	dc.b $F0, $B, $0, $0, $F6
DATAPIUMRKMWAM9_AC: dc.b $1
	dc.b $F0, $B, $0, $0, $F6
DATAPIUMRKMWAM9_AD: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_AE: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_AF: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_B0: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_B1: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_B2: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_B3: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_B4: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAPIUMRKMWAM9_B5: dc.b $3
	dc.b $F0, $0, $0, $0, $0
	dc.b $F8, $D, $0, $1, $E8
	dc.b $F8, $5, $0, $9, $8
DATAPIUMRKMWAM9_B6: dc.b $2
	dc.b $F0, $A, $0, $0, $FC
	dc.b $F8, $5, $0, $9, $EC
DATAPIUMRKMWAM9_B7: dc.b $1
	dc.b $F0, $E, $0, $0, $F0
DATAPIUMRKMWAM9_B8: dc.b $2
	dc.b $F0, $A, $8, $0, $EC
	dc.b $F8, $5, $8, $9, $4
DATAPIUMRKMWAM9_B9: dc.b $3
	dc.b $F0, $0, $8, $0, $F8
	dc.b $F8, $D, $8, $1, $F8
	dc.b $F8, $5, $8, $9, $E8
DATAPIUMRKMWAM9_BA: dc.b $3
	dc.b $F0, $4, $0, $0, $F4
	dc.b $F8, $D, $0, $2, $EC
	dc.b $F8, $1, $0, $A, $C
DATAPIUMRKMWAM9_BB: dc.b $2
	dc.b $F0, $9, $0, $0, $F0
	dc.b $0, $C, $0, $6, $F0
DATAPIUMRKMWAM9_BC: dc.b $3
	dc.b $F0, $4, $8, $0, $FC
	dc.b $F8, $D, $8, $2, $F4
	dc.b $F8, $1, $8, $A, $EC
DATAPIUMRKMWAM9_BD: dc.b $3
	dc.b $F2, $1, $0, $0, $EA
	dc.b $F2, $E, $0, $2, $F2
	dc.b $A, $8, $0, $E, $F2
DATAPIUMRKMWAM9_BE: dc.b $3
	dc.b $F2, $E, $0, $0, $F4
	dc.b $F2, $1, $0, $C, $EC
	dc.b $A, $8, $0, $E, $F4
DATAPIUMRKMWAM9_BF: dc.b $2
	dc.b $F2, $F, $0, $0, $EE
	dc.b $2, $0, $0, $10, $E
DATAPIUMRKMWAM9_C0: dc.b $4
	dc.b $F2, $D, $0, $0, $F2
	dc.b $F2, $0, $0, $8, $EA
	dc.b $2, $D, $0, $9, $EA
	dc.b $2, $0, $0, $11, $A
DATAPIUMRKMWAM9_C1: dc.b $2
	dc.b $F2, $F, $0, $0, $ED
	dc.b $F2, $1, $0, $10, $D
DATAPIUMRKMWAM9_C2: dc.b $3
	dc.b $F5, $E, $0, $0, $F3
	dc.b $F5, $2, $0, $C, $EB
	dc.b $ED, $4, $0, $F, $EB
DATAPIUMRKMWAM9_C3: dc.b $1
	dc.b $F8, $F, $0, $0, $F0
DATAPIUMRKMWAM9_C4: dc.b $1
	dc.b $F8, $F, $0, $0, $F0
DATAPIUMRKMWAM9_C5: dc.b $3
	dc.b $ED, $4, $0, $0, $EB
	dc.b $F5, $E, $0, $2, $F3
	dc.b $5, $0, $0, $E, $EB
DATAPIUMRKMWAM9_C6: dc.b $3
	dc.b $ED, $4, $0, $0, $F3
	dc.b $F5, $E, $0, $2, $F3
	dc.b $5, $0, $0, $E, $EB
DATAPIUMRKMWAM9_C7: dc.b $2
	dc.b $E6, $4, $0, $0, $F4
	dc.b $EE, $B, $0, $2, $F4
DATAPIUMRKMWAM9_C8: dc.b $2
	dc.b $E6, $4, $0, $0, $F4
	dc.b $EE, $B, $0, $2, $F4
DATAPIUMRKMWAM9_C9: dc.b $3
	dc.b $EF, $B, $0, $0, $F0
	dc.b $F, $0, $0, $C, $F8
	dc.b $F7, $2, $0, $D, $8
DATAPIUMRKMWAM9_CA: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $10, $0, $0, $10, $F8
DATAPIUMRKMWAM9_CB: dc.b $2
	dc.b $F1, $B, $0, $0, $F2
	dc.b $F9, $6, $0, $C, $E2
DATAPIUMRKMWAM9_CC: dc.b $2
	dc.b $F1, $B, $0, $0, $F4
	dc.b $F9, $6, $0, $C, $E4
DATAPIUMRKMWAM9_CD: dc.b $2
	dc.b $F1, $F, $0, $0, $EF
	dc.b $1, $1, $0, $10, $F
DATAPIUMRKMWAM9_CE: dc.b $3
	dc.b $EF, $A, $0, $0, $F2
	dc.b $7, $5, $0, $9, $FA
	dc.b $FF, $D, $0, $D, $A
DATAPIUMRKMWAM9_CF: dc.b $3
	dc.b $EC, $A, $0, $0, $F2
	dc.b $4, $5, $0, $9, $FA
	dc.b $F4, $A, $0, $D, $A
DATAPIUMRKMWAM9_D0: dc.b $3
	dc.b $F0, $E, $0, $0, $F2
	dc.b $8, $8, $0, $C, $F2
	dc.b $F0, $1, $0, $F, $12
DATAPIUMRKMWAM9_D1: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $9, $0, $C, $F2
	dc.b $FE, $1, $0, $12, $A
DATAPIUMRKMWAM9_D2: dc.b $4
	dc.b $F0, $9, $0, $8, $F8
	dc.b $0, $C, $0, $E, $F0
	dc.b $8, $4, $0, $12, $F0
	dc.b $F0, $7, $10, $0, $EA
DATAPIUMRKMWAM9_D3: dc.b $4
	dc.b $F0, $9, $0, $8, $F8
	dc.b $0, $C, $0, $E, $F0
	dc.b $8, $4, $0, $12, $F0
	dc.b $F0, $7, $0, $0, $EA
DATAPIUMRKMWAM9_D4: dc.b $4
	dc.b $EC, $4, $0, $9, $F8
	dc.b $F4, $9, $0, $B, $F0
	dc.b $4, $5, $0, $11, $F8
	dc.b $0, $A, $0, $0, $EB
DATAPIUMRKMWAM9_D5: dc.b $4
	dc.b $F5, $9, $0, $2, $F0
	dc.b $5, $5, $0, $8, $F8
	dc.b $0, $A, $0, $C, $EB
	dc.b $ED, $4, $0, $0, $F8
DATAPIUMRKMWAM9_D6: dc.b $4
	dc.b $F0, $9, $0, $8, $F0
	dc.b $0, $C, $0, $E, $F0
	dc.b $8, $4, $0, $12, $0
	dc.b $6, $D, $8, $0, $F0
DATAPIUMRKMWAM9_D7: dc.b $4
	dc.b $F0, $9, $0, $8, $F0
	dc.b $0, $C, $0, $E, $F0
	dc.b $8, $4, $0, $12, $0
	dc.b $6, $D, $0, $0, $F0
DATAPIUMRKMWAM9_D8: dc.b $4
	dc.b $F8, $D, $0, $0, $EB
	dc.b $F8, $1, $0, $8, $B
	dc.b $8, $4, $0, $A, $F3
	dc.b $FD, $A, $10, $C, $FE
DATAPIUMRKMWAM9_D9: dc.b $4
	dc.b $F8, $D, $0, $9, $EC
	dc.b $F8, $1, $0, $11, $C
	dc.b $8, $4, $0, $13, $F4
	dc.b $FD, $A, $10, $0, $FE
	even