; ---------------------------------------------------------------------------
; Collision index pointers
; ---------------------------------------------------------------------------
	dc.l Col_AAZ_1
	dc.l Col_AAZ_2
	dc.l Col_BBZ_1
	dc.l Col_BBZ_2
	dc.l Col_CCZ_1
	dc.l Col_CCZ_2
	dc.l Col_DDZ_1
	dc.l Col_DDZ_2
	dc.l Col_EEZ_1
	dc.l Col_EEZ_2
	dc.l Col_FFZ_1
	dc.l Col_FFZ_2
	dc.l Col_AAZ_1
	dc.l Col_AAZ_2
	dc.l Col_SSZ_1
	dc.l Col_SSZ_2