; ================================================================================
; Sprite DPLCs - generated by Flex 2 Mon Apr 09 2018 20:48:02 GMT-0400 (Eastern Daylight Time)
; ================================================================================

GoalDPLC:
	dc.w GoalDPLC_0-GoalDPLC, GoalDPLC_1-GoalDPLC
	dc.w GoalDPLC_2-GoalDPLC, GoalDPLC_3-GoalDPLC
	dc.w GoalDPLC_4-GoalDPLC
GoalDPLC_0: dc.b $5
	dc.b $F0, $0
	dc.b $F0, $10
	dc.b $F0, $20
	dc.b $D0, $30
	dc.b $60, $C3
GoalDPLC_1: dc.b $4
	dc.b $F0, $3E
	dc.b $F0, $4E
	dc.b $B0, $5E
	dc.b $D0, $CA
GoalDPLC_2: dc.b $2
	dc.b $F0, $6A
	dc.b $70, $7A
GoalDPLC_3: dc.b $4
	dc.b $F0, $3E
	dc.b $F0, $4E
	dc.b $B0, $5E
	dc.b $D0, $CA
GoalDPLC_4: dc.b $1
	dc.b $D0, $CA
	even