; ================================================================================
; Sprite DPLCs - generated by Flex 2 Tue Mar 13 2018 13:07:48 GMT-0500 (Eastern Standard Time)
; ================================================================================

GoalDPLC:
	dc.w GoalDPLC_0-GoalDPLC, GoalDPLC_1-GoalDPLC
	dc.w GoalDPLC_2-GoalDPLC, GoalDPLC_3-GoalDPLC
	dc.w GoalDPLC_4-GoalDPLC, GoalDPLC_5-GoalDPLC
	dc.w GoalDPLC_6-GoalDPLC, GoalDPLC_7-GoalDPLC
	dc.w GoalDPLC_8-GoalDPLC
GoalDPLC_0: dc.b $5
	dc.b $F0, $0
	dc.b $F0, $10
	dc.b $F0, $20
	dc.b $D0, $30
	dc.b $90, $C3
GoalDPLC_1: dc.b $4
	dc.b $F0, $3E
	dc.b $F0, $4E
	dc.b $B0, $5E
	dc.b $D0, $CD
GoalDPLC_2: dc.b $2
	dc.b $F0, $6A
	dc.b $70, $7A
GoalDPLC_3: dc.b $1
	dc.b $F0, $82
GoalDPLC_4: dc.b $2
	dc.b $F0, $92
	dc.b $50, $A2
GoalDPLC_5: dc.b $2
	dc.b $F0, $A8
	dc.b $A0, $B8
GoalDPLC_6: dc.b $2
	dc.b $F0, $A8
	dc.b $A0, $B8
GoalDPLC_7: dc.b $2
	dc.b $F0, $92
	dc.b $50, $A2
GoalDPLC_8: dc.b $1
	dc.b $F0, $82
	even