; DPLCs - generated by Flex - Sonic 1 format

_DPLC:
	dc.w AUJ_Frame0-_DPLC

AUJ_Frame0: dc.b  $15
	dc.b  $0, $0
	dc.b  $70, $1
	dc.b  $20, $9
	dc.b  $0, $C
	dc.b  $20, $D
	dc.b  $F0, $10
	dc.b  $F0, $20
	dc.b  $F0, $30
	dc.b  $B0, $40
	dc.b  $B0, $4C
	dc.b  $20, $58
	dc.b  $10, $5B
	dc.b  $20, $5D
	dc.b  $0, $60
	dc.b  $0, $61
	dc.b  $10, $62
	dc.b  $B0, $64
	dc.b  $20, $70
	dc.b  $30, $73
	dc.b  $30, $77
	dc.b  $0, $7B
